export interface CiiuCode {
  code: string;
  description: string;
  section: string;
}

export const CIIU_CODES: CiiuCode[] = [
  // SECCIÓN A - AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA
  { code: "0111", description: "Cultivo de cereales y otros cultivos n.c.p.", section: "A" },
  { code: "0112", description: "Cultivo de arroz", section: "A" },
  { code: "0113", description: "Cultivo de hortalizas, raíces y tubérculos", section: "A" },
  { code: "0114", description: "Cultivo de tabaco", section: "A" },
  { code: "0115", description: "Cultivo de plantas textiles", section: "A" },
  { code: "0119", description: "Otros cultivos transitorios n.c.p.", section: "A" },
  { code: "0121", description: "Cultivo de frutas tropicales y subtropicales", section: "A" },
  { code: "0122", description: "Cultivo de plátano y banano", section: "A" },
  { code: "0123", description: "Cultivo de café", section: "A" },
  { code: "0124", description: "Cultivo de caña de azúcar", section: "A" },
  { code: "0125", description: "Cultivo de flor de corte", section: "A" },
  { code: "0126", description: "Cultivo de palma para aceite", section: "A" },
  { code: "0127", description: "Cultivo de plantas con las que se preparan bebidas", section: "A" },
  { code: "0128", description: "Cultivo de especias y de plantas aromáticas y medicinales", section: "A" },
  { code: "0129", description: "Otros cultivos permanentes n.c.p.", section: "A" },
  { code: "0130", description: "Propagación de plantas", section: "A" },
  { code: "0141", description: "Cría de ganado bovino y bufalino", section: "A" },
  { code: "0142", description: "Cría de caballos y otros equinos", section: "A" },
  { code: "0143", description: "Cría de ovejas y cabras", section: "A" },
  { code: "0144", description: "Cría de ganado porcino", section: "A" },
  { code: "0145", description: "Cría de aves de corral", section: "A" },
  { code: "0149", description: "Cría de otros animales n.c.p.", section: "A" },
  { code: "0150", description: "Explotación mixta (agrícola y pecuaria)", section: "A" },
  { code: "0161", description: "Actividades de apoyo a la agricultura", section: "A" },
  { code: "0162", description: "Actividades de apoyo a la ganadería", section: "A" },
  { code: "0163", description: "Actividades posteriores a la cosecha", section: "A" },
  { code: "0164", description: "Tratamiento de semillas para propagación", section: "A" },
  { code: "0170", description: "Caza ordinaria y mediante trampas y actividades de servicios conexas", section: "A" },
  { code: "0210", description: "Silvicultura y otras actividades forestales", section: "A" },
  { code: "0220", description: "Extracción de madera", section: "A" },
  { code: "0230", description: "Recolección de productos forestales diferentes a la madera", section: "A" },
  { code: "0240", description: "Servicios de apoyo a la silvicultura", section: "A" },
  { code: "0311", description: "Pesca marítima", section: "A" },
  { code: "0312", description: "Pesca de agua dulce", section: "A" },
  { code: "0321", description: "Acuicultura marítima", section: "A" },
  { code: "0322", description: "Acuicultura de agua dulce", section: "A" },

  // SECCIÓN B - EXPLOTACIÓN DE MINAS Y CANTERAS
  { code: "0510", description: "Extracción de hulla (carbón de piedra)", section: "B" },
  { code: "0520", description: "Extracción de carbón lignito", section: "B" },
  { code: "0610", description: "Extracción de petróleo crudo", section: "B" },
  { code: "0620", description: "Extracción de gas natural", section: "B" },
  { code: "0710", description: "Extracción de minerales de hierro", section: "B" },
  { code: "0721", description: "Extracción de minerales de uranio y de torio", section: "B" },
  { code: "0722", description: "Extracción de oro y otros metales preciosos", section: "B" },
  { code: "0723", description: "Extracción de minerales de níquel", section: "B" },
  { code: "0729", description: "Extracción de otros minerales metalíferos no ferrosos n.c.p.", section: "B" },
  { code: "0811", description: "Extracción de piedra, arena, arcillas", section: "B" },
  { code: "0812", description: "Extracción de arcillas de uso industrial, caliza, caolín y bentonitas", section: "B" },
  { code: "0820", description: "Extracción de esmeraldas, piedras preciosas y semipreciosas", section: "B" },
  { code: "0891", description: "Extracción de minerales para la fabricación de abonos y productos químicos", section: "B" },
  { code: "0892", description: "Extracción de halita (sal)", section: "B" },
  { code: "0899", description: "Extracción de otros minerales no metálicos n.c.p.", section: "B" },
  { code: "0910", description: "Actividades de apoyo para la extracción de petróleo y de gas natural", section: "B" },
  { code: "0990", description: "Actividades de apoyo para otras actividades de explotación de minas y canteras", section: "B" },

  // SECCIÓN C - INDUSTRIAS MANUFACTURERAS
  { code: "1011", description: "Procesamiento y conservación de carne y productos cárnicos", section: "C" },
  { code: "1012", description: "Procesamiento y conservación de pescados, crustáceos y moluscos", section: "C" },
  { code: "1020", description: "Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos", section: "C" },
  { code: "1030", description: "Elaboración de aceites y grasas de origen vegetal y animal", section: "C" },
  { code: "1040", description: "Elaboración de productos lácteos", section: "C" },
  { code: "1051", description: "Elaboración de productos de molinería", section: "C" },
  { code: "1052", description: "Elaboración de almidones y productos derivados del almidón", section: "C" },
  { code: "1061", description: "Trilla de café", section: "C" },
  { code: "1062", description: "Descafeinado, tostión y molienda del café", section: "C" },
  { code: "1063", description: "Otros derivados del café", section: "C" },
  { code: "1071", description: "Elaboración y refinación de azúcar", section: "C" },
  { code: "1072", description: "Elaboración de panela", section: "C" },
  { code: "1081", description: "Elaboración de productos de panadería", section: "C" },
  { code: "1082", description: "Elaboración de cacao, chocolate y productos de confitería", section: "C" },
  { code: "1083", description: "Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares", section: "C" },
  { code: "1084", description: "Elaboración de comidas y platos preparados", section: "C" },
  { code: "1089", description: "Elaboración de otros productos alimenticios n.c.p.", section: "C" },
  { code: "1090", description: "Elaboración de alimentos preparados para animales", section: "C" },
  { code: "1101", description: "Destilación, rectificación y mezcla de bebidas alcohólicas", section: "C" },
  { code: "1102", description: "Elaboración de bebidas fermentadas no destiladas", section: "C" },
  { code: "1103", description: "Producción de malta, elaboración de cervezas y otras bebidas malteadas", section: "C" },
  { code: "1104", description: "Elaboración de bebidas no alcohólicas, producción de aguas minerales", section: "C" },
  { code: "1200", description: "Elaboración de productos de tabaco", section: "C" },
  { code: "1311", description: "Preparación e hilatura de fibras textiles", section: "C" },
  { code: "1312", description: "Tejeduría de productos textiles", section: "C" },
  { code: "1313", description: "Acabado de productos textiles", section: "C" },
  { code: "1391", description: "Fabricación de tejidos de punto y ganchillo", section: "C" },
  { code: "1392", description: "Confección de artículos con materiales textiles, excepto prendas de vestir", section: "C" },
  { code: "1393", description: "Fabricación de tapetes y alfombras para pisos", section: "C" },
  { code: "1394", description: "Fabricación de cuerdas, cordeles, cables, bramantes y redes", section: "C" },
  { code: "1399", description: "Fabricación de otros artículos textiles n.c.p.", section: "C" },
  { code: "1410", description: "Confección de prendas de vestir, excepto prendas de piel", section: "C" },
  { code: "1420", description: "Fabricación de artículos de piel", section: "C" },
  { code: "1430", description: "Fabricación de artículos de punto y ganchillo", section: "C" },
  { code: "1511", description: "Curtido y recurtido de cueros; recurtido y teñido de pieles", section: "C" },
  { code: "1512", description: "Fabricación de artículos de viaje, bolsos de mano", section: "C" },
  { code: "1513", description: "Fabricación de artículos de talabartería y guarnicionería", section: "C" },
  { code: "1521", description: "Fabricación de calzado de cuero y piel", section: "C" },
  { code: "1522", description: "Fabricación de otros tipos de calzado", section: "C" },
  { code: "1523", description: "Fabricación de partes del calzado", section: "C" },
  { code: "1610", description: "Aserrado, acepillado e impregnación de la madera", section: "C" },
  { code: "1620", description: "Fabricación de hojas de madera para enchapado", section: "C" },
  { code: "1630", description: "Fabricación de partes y piezas de madera, de carpintería y ebanistería", section: "C" },
  { code: "1640", description: "Fabricación de recipientes de madera", section: "C" },
  { code: "1690", description: "Fabricación de otros productos de madera", section: "C" },
  { code: "1701", description: "Fabricación de pulpas (pastas) celulósicas; papel y cartón", section: "C" },
  { code: "1702", description: "Fabricación de papel y cartón ondulado; fabricación de envases, empaques", section: "C" },
  { code: "1709", description: "Fabricación de otros artículos de papel y cartón", section: "C" },
  { code: "1811", description: "Actividades de impresión", section: "C" },
  { code: "1812", description: "Actividades de servicios relacionados con la impresión", section: "C" },
  { code: "1820", description: "Producción de copias a partir de grabaciones originales", section: "C" },
  { code: "1910", description: "Fabricación de productos de hornos de coque", section: "C" },
  { code: "1921", description: "Fabricación de productos de la refinación del petróleo", section: "C" },
  { code: "1922", description: "Actividad de mezcla de combustibles", section: "C" },
  { code: "2011", description: "Fabricación de sustancias y productos químicos básicos", section: "C" },
  { code: "2012", description: "Fabricación de abonos y compuestos inorgánicos nitrogenados", section: "C" },
  { code: "2013", description: "Fabricación de plásticos en formas primarias", section: "C" },
  { code: "2014", description: "Fabricación de caucho sintético en formas primarias", section: "C" },
  { code: "2021", description: "Fabricación de plaguicidas y otros productos químicos de uso agropecuario", section: "C" },
  { code: "2022", description: "Fabricación de pinturas, barnices y revestimientos similares", section: "C" },
  { code: "2023", description: "Fabricación de jabones y detergentes, preparados para limpiar y pulir", section: "C" },
  { code: "2029", description: "Fabricación de otros productos químicos n.c.p.", section: "C" },
  { code: "2030", description: "Fabricación de fibras sintéticas y artificiales", section: "C" },
  { code: "2100", description: "Fabricación de productos farmacéuticos, sustancias químicas medicinales", section: "C" },
  { code: "2211", description: "Fabricación de llantas y neumáticos de caucho", section: "C" },
  { code: "2212", description: "Reencauche de llantas usadas", section: "C" },
  { code: "2219", description: "Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.", section: "C" },
  { code: "2221", description: "Fabricación de formas básicas de plástico", section: "C" },
  { code: "2229", description: "Fabricación de artículos de plástico n.c.p.", section: "C" },
  { code: "2310", description: "Fabricación de vidrio y productos de vidrio", section: "C" },
  { code: "2391", description: "Fabricación de productos refractarios", section: "C" },
  { code: "2392", description: "Fabricación de materiales de arcilla para la construcción", section: "C" },
  { code: "2393", description: "Fabricación de otros productos de cerámica y porcelana", section: "C" },
  { code: "2394", description: "Fabricación de cemite, cal y yeso", section: "C" },
  { code: "2395", description: "Fabricación de artículos de hormigón, cemento y yeso", section: "C" },
  { code: "2396", description: "Corte, tallado y acabado de la piedra", section: "C" },
  { code: "2399", description: "Fabricación de otros productos minerales no metálicos n.c.p.", section: "C" },
  { code: "2410", description: "Industrias básicas de hierro y de acero", section: "C" },
  { code: "2421", description: "Industrias básicas de metales preciosos", section: "C" },
  { code: "2429", description: "Industrias básicas de otros metales no ferrosos", section: "C" },
  { code: "2431", description: "Fundición de hierro y de acero", section: "C" },
  { code: "2432", description: "Fundición de metales no ferrosos", section: "C" },
  { code: "2511", description: "Fabricación de productos metálicos para uso estructural", section: "C" },
  { code: "2512", description: "Fabricación de tanques, depósitos y recipientes de metal", section: "C" },
  { code: "2513", description: "Fabricación de generadores de vapor, excepto calderas de agua caliente", section: "C" },
  { code: "2520", description: "Fabricación de armas y municiones", section: "C" },
  { code: "2591", description: "Forja, prensado, estampado y laminado de metal; pulvimetalurgia", section: "C" },
  { code: "2592", description: "Tratamiento y revestimiento de metales; mecanizado", section: "C" },
  { code: "2593", description: "Fabricación de artículos de cuchillería, herramientas de mano", section: "C" },
  { code: "2599", description: "Fabricación de otros productos elaborados de metal n.c.p.", section: "C" },
  { code: "2610", description: "Fabricación de componentes y tableros electrónicos", section: "C" },
  { code: "2620", description: "Fabricación de computadoras y de equipo periférico", section: "C" },
  { code: "2630", description: "Fabricación de equipos de comunicación", section: "C" },
  { code: "2640", description: "Fabricación de aparatos electrónicos de consumo", section: "C" },
  { code: "2651", description: "Fabricación de equipo de medición, prueba, navegación y control", section: "C" },
  { code: "2652", description: "Fabricación de relojes", section: "C" },
  { code: "2660", description: "Fabricación de equipo de irradiación y equipo electrónico de uso médico", section: "C" },
  { code: "2670", description: "Fabricación de instrumentos ópticos y equipo fotográfico", section: "C" },
  { code: "2680", description: "Fabricación de medios magnéticos y ópticos para almacenamiento de datos", section: "C" },
  { code: "2711", description: "Fabricación de motores, generadores y transformadores eléctricos", section: "C" },
  { code: "2712", description: "Fabricación de aparatos de distribución y control de la energía eléctrica", section: "C" },
  { code: "2720", description: "Fabricación de pilas, baterías y acumuladores eléctricos", section: "C" },
  { code: "2731", description: "Fabricación de hilos y cables eléctricos y de fibra óptica", section: "C" },
  { code: "2732", description: "Fabricación de dispositivos de cableado", section: "C" },
  { code: "2740", description: "Fabricación de equipos eléctricos de iluminación", section: "C" },
  { code: "2750", description: "Fabricación de aparatos de uso doméstico", section: "C" },
  { code: "2790", description: "Fabricación de otros tipos de equipo eléctrico n.c.p.", section: "C" },
  { code: "2811", description: "Fabricación de motores, turbinas, y partes para motores de combustión interna", section: "C" },
  { code: "2812", description: "Fabricación de equipos de potencia hidráulica y neumática", section: "C" },
  { code: "2813", description: "Fabricación de otras bombas, compresores, grifos y válvulas", section: "C" },
  { code: "2814", description: "Fabricación de cojinetes, engranajes, trenes de engranajes", section: "C" },
  { code: "2815", description: "Fabricación de hornos, hogares y quemadores industriales", section: "C" },
  { code: "2816", description: "Fabricación de equipo de elevación y manipulación", section: "C" },
  { code: "2817", description: "Fabricación de maquinaria y equipo de oficina (excepto computadoras)", section: "C" },
  { code: "2818", description: "Fabricación de herramientas manuales con motor", section: "C" },
  { code: "2819", description: "Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.", section: "C" },
  { code: "2821", description: "Fabricación de maquinaria agropecuaria y forestal", section: "C" },
  { code: "2822", description: "Fabricación de máquinas formadoras de metal y de máquinas herramienta", section: "C" },
  { code: "2823", description: "Fabricación de maquinaria para la metalurgia", section: "C" },
  { code: "2824", description: "Fabricación de maquinaria para explotación de minas y canteras", section: "C" },
  { code: "2825", description: "Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco", section: "C" },
  { code: "2826", description: "Fabricación de maquinaria para la elaboración de productos textiles", section: "C" },
  { code: "2829", description: "Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.", section: "C" },
  { code: "2910", description: "Fabricación de vehículos automotores y sus motores", section: "C" },
  { code: "2920", description: "Fabricación de carrocerías para vehículos automotores", section: "C" },
  { code: "2930", description: "Fabricación de partes, piezas (autopartes) y accesorios para vehículos", section: "C" },
  { code: "3011", description: "Construcción de barcos y de estructuras flotantes", section: "C" },
  { code: "3012", description: "Construcción de embarcaciones de recreo y deporte", section: "C" },
  { code: "3020", description: "Fabricación de locomotoras y de material rodante para ferrocarriles", section: "C" },
  { code: "3030", description: "Fabricación de aeronaves, naves espaciales y de maquinaria conexa", section: "C" },
  { code: "3040", description: "Fabricación de vehículos militares de combate", section: "C" },
  { code: "3091", description: "Fabricación de motocicletas", section: "C" },
  { code: "3092", description: "Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad", section: "C" },
  { code: "3099", description: "Fabricación de otros tipos de equipo de transporte n.c.p.", section: "C" },
  { code: "3110", description: "Fabricación de muebles", section: "C" },
  { code: "3120", description: "Fabricación de colchones y somieres", section: "C" },
  { code: "3210", description: "Fabricación de joyas, bisutería y artículos conexos", section: "C" },
  { code: "3220", description: "Fabricación de instrumentos musicales", section: "C" },
  { code: "3230", description: "Fabricación de artículos y equipo para la práctica del deporte", section: "C" },
  { code: "3240", description: "Fabricación de juegos, juguetes y rompecabezas", section: "C" },
  { code: "3250", description: "Fabricación de instrumentos, aparatos y materiales médicos y odontológicos", section: "C" },
  { code: "3290", description: "Otras industrias manufactureras n.c.p.", section: "C" },
  { code: "3311", description: "Mantenimiento y reparación especializado de productos elaborados en metal", section: "C" },
  { code: "3312", description: "Mantenimiento y reparación especializado de maquinaria y equipo", section: "C" },
  { code: "3313", description: "Mantenimiento y reparación especializado de equipo electrónico y óptico", section: "C" },
  { code: "3314", description: "Mantenimiento y reparación especializado de equipo eléctrico", section: "C" },
  { code: "3315", description: "Mantenimiento y reparación especializado de equipo de transporte", section: "C" },
  { code: "3319", description: "Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.", section: "C" },
  { code: "3320", description: "Instalación especializada de maquinaria y equipo industrial", section: "C" },

  // SECCIÓN D - SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO
  { code: "3511", description: "Generación de energía eléctrica", section: "D" },
  { code: "3512", description: "Transmisión de energía eléctrica", section: "D" },
  { code: "3513", description: "Distribución de energía eléctrica", section: "D" },
  { code: "3514", description: "Comercialización de energía eléctrica", section: "D" },
  { code: "3520", description: "Producción de gas; distribución de combustibles gaseosos por tuberías", section: "D" },
  { code: "3530", description: "Suministro de vapor y aire acondicionado", section: "D" },

  // SECCIÓN E - DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES
  { code: "3600", description: "Captación, tratamiento y distribución de agua", section: "E" },
  { code: "3700", description: "Evacuación y tratamiento de aguas residuales", section: "E" },
  { code: "3811", description: "Recolección de desechos no peligrosos", section: "E" },
  { code: "3812", description: "Recolección de desechos peligrosos", section: "E" },
  { code: "3821", description: "Tratamiento y disposición de desechos no peligrosos", section: "E" },
  { code: "3822", description: "Tratamiento y disposición de desechos peligrosos", section: "E" },
  { code: "3830", description: "Recuperación de materiales", section: "E" },
  { code: "3900", description: "Actividades de saneamiento ambiental y otros servicios de gestión de desechos", section: "E" },

  // SECCIÓN F - CONSTRUCCIÓN
  { code: "4111", description: "Construcción de edificios residenciales", section: "F" },
  { code: "4112", description: "Construcción de edificios no residenciales", section: "F" },
  { code: "4210", description: "Construcción de carreteras y vías de ferrocarril", section: "F" },
  { code: "4220", description: "Construcción de proyectos de servicio público", section: "F" },
  { code: "4290", description: "Construcción de otras obras de ingeniería civil", section: "F" },
  { code: "4311", description: "Demolición", section: "F" },
  { code: "4312", description: "Preparación del terreno", section: "F" },
  { code: "4321", description: "Instalaciones eléctricas", section: "F" },
  { code: "4322", description: "Instalaciones de fontanería, calefacción y aire acondicionado", section: "F" },
  { code: "4329", description: "Otras instalaciones especializadas", section: "F" },
  { code: "4330", description: "Terminación y acabado de edificios y obras de ingeniería civil", section: "F" },
  { code: "4390", description: "Otras actividades especializadas para la construcción de edificios", section: "F" },

  // SECCIÓN G - COMERCIO AL POR MAYOR Y AL POR MENOR
  { code: "4511", description: "Comercio de vehículos automotores nuevos", section: "G" },
  { code: "4512", description: "Comercio de vehículos automotores usados", section: "G" },
  { code: "4520", description: "Mantenimiento y reparación de vehículos automotores", section: "G" },
  { code: "4530", description: "Comercio de partes, piezas (autopartes) y accesorios para vehículos", section: "G" },
  { code: "4541", description: "Comercio de motocicletas y de sus partes, piezas y accesorios", section: "G" },
  { code: "4542", description: "Mantenimiento y reparación de motocicletas y de sus partes y piezas", section: "G" },
  { code: "4610", description: "Comercio al por mayor a cambio de una retribución o por contrata", section: "G" },
  { code: "4620", description: "Comercio al por mayor de materias primas agropecuarias", section: "G" },
  { code: "4631", description: "Comercio al por mayor de productos alimenticios", section: "G" },
  { code: "4632", description: "Comercio al por mayor de bebidas y tabaco", section: "G" },
  { code: "4641", description: "Comercio al por mayor de productos textiles, productos confeccionados", section: "G" },
  { code: "4642", description: "Comercio al por mayor de calzado", section: "G" },
  { code: "4643", description: "Comercio al por mayor de aparatos y equipo de uso doméstico", section: "G" },
  { code: "4644", description: "Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos", section: "G" },
  { code: "4645", description: "Comercio al por mayor de productos de perfumería, artículos de uso personal", section: "G" },
  { code: "4649", description: "Comercio al por mayor de otros utensilios domésticos n.c.p.", section: "G" },
  { code: "4651", description: "Comercio al por mayor de computadores, equipo periférico y programas", section: "G" },
  { code: "4652", description: "Comercio al por mayor de equipo, partes y piezas electrónicos", section: "G" },
  { code: "4653", description: "Comercio al por mayor de maquinaria y equipo agropecuarios", section: "G" },
  { code: "4659", description: "Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.", section: "G" },
  { code: "4661", description: "Comercio al por mayor de combustibles sólidos, líquidos, gaseosos", section: "G" },
  { code: "4662", description: "Comercio al por mayor de metales y minerales metalíferos", section: "G" },
  { code: "4663", description: "Comercio al por mayor de materiales de construcción, artículos de ferretería", section: "G" },
  { code: "4664", description: "Comercio al por mayor de productos químicos básicos, cauchos y plásticos", section: "G" },
  { code: "4665", description: "Comercio al por mayor de desperdicios, desechos y chatarra", section: "G" },
  { code: "4669", description: "Comercio al por mayor de otros productos n.c.p.", section: "G" },
  { code: "4690", description: "Comercio al por mayor no especializado", section: "G" },
  { code: "4711", description: "Comercio al por menor en establecimientos no especializados con surtido de alimentos", section: "G" },
  { code: "4719", description: "Comercio al por menor en establecimientos no especializados, con surtido diverso", section: "G" },
  { code: "4721", description: "Comercio al por menor de productos agrícolas para el consumo", section: "G" },
  { code: "4722", description: "Comercio al por menor de leche, productos lácteos y huevos", section: "G" },
  { code: "4723", description: "Comercio al por menor de carnes, productos cárnicos, pescados y productos de mar", section: "G" },
  { code: "4724", description: "Comercio al por menor de bebidas y productos del tabaco", section: "G" },
  { code: "4729", description: "Comercio al por menor de otros productos alimenticios n.c.p.", section: "G" },
  { code: "4731", description: "Comercio al por menor de combustible para automotores", section: "G" },
  { code: "4732", description: "Comercio al por menor de lubricantes, aditivos y productos de limpieza", section: "G" },
  { code: "4741", description: "Comercio al por menor de computadores, equipos periféricos", section: "G" },
  { code: "4742", description: "Comercio al por menor de equipos y aparatos de sonido y de video", section: "G" },
  { code: "4751", description: "Comercio al por menor de productos textiles", section: "G" },
  { code: "4752", description: "Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio", section: "G" },
  { code: "4753", description: "Comercio al por menor de tapices, alfombras y cubrimientos", section: "G" },
  { code: "4754", description: "Comercio al por menor de electrodomésticos y gasodomésticos", section: "G" },
  { code: "4755", description: "Comercio al por menor de artículos y utensilios de uso doméstico", section: "G" },
  { code: "4759", description: "Comercio al por menor de otros artículos domésticos", section: "G" },
  { code: "4761", description: "Comercio al por menor de libros, periódicos, materiales y artículos de papelería", section: "G" },
  { code: "4762", description: "Comercio al por menor de artículos deportivos", section: "G" },
  { code: "4769", description: "Comercio al por menor de otros artículos culturales y de entretenimiento", section: "G" },
  { code: "4771", description: "Comercio al por menor de prendas de vestir en establecimientos especializados", section: "G" },
  { code: "4772", description: "Comercio al por menor de todo tipo de calzado y artículos de cuero", section: "G" },
  { code: "4773", description: "Comercio al por menor de productos farmacéuticos y medicinales", section: "G" },
  { code: "4774", description: "Comercio al por menor de otros productos nuevos", section: "G" },
  { code: "4775", description: "Comercio al por menor de artículos de segunda mano", section: "G" },
  { code: "4781", description: "Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles", section: "G" },
  { code: "4782", description: "Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles", section: "G" },
  { code: "4789", description: "Comercio al por menor de otros productos en puestos de venta móviles", section: "G" },
  { code: "4791", description: "Comercio al por menor realizado a través de internet", section: "G" },
  { code: "4792", description: "Comercio al por menor realizado a través de casas de venta o por correo", section: "G" },
  { code: "4799", description: "Otros tipos de comercio al por menor no realizado en establecimientos", section: "G" },

  // SECCIÓN H - TRANSPORTE Y ALMACENAMIENTO
  { code: "4911", description: "Transporte férreo de pasajeros", section: "H" },
  { code: "4912", description: "Transporte férreo de carga", section: "H" },
  { code: "4921", description: "Transporte de pasajeros", section: "H" },
  { code: "4922", description: "Transporte mixto", section: "H" },
  { code: "4923", description: "Transporte de carga por carretera", section: "H" },
  { code: "4930", description: "Transporte por tuberías", section: "H" },
  { code: "5011", description: "Transporte de pasajeros marítimo y de cabotaje", section: "H" },
  { code: "5012", description: "Transporte de carga marítimo y de cabotaje", section: "H" },
  { code: "5021", description: "Transporte fluvial de pasajeros", section: "H" },
  { code: "5022", description: "Transporte fluvial de carga", section: "H" },
  { code: "5111", description: "Transporte aéreo de pasajeros", section: "H" },
  { code: "5112", description: "Transporte aéreo de carga", section: "H" },
  { code: "5210", description: "Almacenamiento y depósito", section: "H" },
  { code: "5221", description: "Actividades de estaciones, vías y servicios complementarios para el transporte terrestre", section: "H" },
  { code: "5222", description: "Actividades de puertos y servicios complementarios para el transporte acuático", section: "H" },
  { code: "5223", description: "Actividades de aeropuertos, servicios de navegación aérea", section: "H" },
  { code: "5224", description: "Manipulación de carga", section: "H" },
  { code: "5229", description: "Otras actividades complementarias al transporte", section: "H" },
  { code: "5310", description: "Actividades postales nacionales", section: "H" },
  { code: "5320", description: "Actividades de mensajería", section: "H" },

  // SECCIÓN I - ALOJAMIENTO Y SERVICIOS DE COMIDA
  { code: "5511", description: "Alojamiento en hoteles", section: "I" },
  { code: "5512", description: "Alojamiento en apartahoteles", section: "I" },
  { code: "5513", description: "Alojamiento en centros vacacionales", section: "I" },
  { code: "5514", description: "Alojamiento rural", section: "I" },
  { code: "5519", description: "Otros tipos de alojamiento para visitantes", section: "I" },
  { code: "5520", description: "Actividades de zonas de camping y parques para vehículos recreacionales", section: "I" },
  { code: "5530", description: "Servicio por horas", section: "I" },
  { code: "5590", description: "Otros tipos de alojamiento n.c.p.", section: "I" },
  { code: "5611", description: "Expendio a la mesa de comidas preparadas", section: "I" },
  { code: "5612", description: "Expendio por autoservicio de comidas preparadas", section: "I" },
  { code: "5613", description: "Expendio de comidas preparadas en cafeterías", section: "I" },
  { code: "5619", description: "Otros tipos de expendio de comidas preparadas n.c.p.", section: "I" },
  { code: "5621", description: "Catering para eventos", section: "I" },
  { code: "5629", description: "Actividades de otros servicios de comidas", section: "I" },
  { code: "5630", description: "Expendio de bebidas alcohólicas para el consumo dentro del establecimiento", section: "I" },

  // SECCIÓN J - INFORMACIÓN Y COMUNICACIONES
  { code: "5811", description: "Edición de libros", section: "J" },
  { code: "5812", description: "Edición de directorios y listas de correo", section: "J" },
  { code: "5813", description: "Edición de periódicos, revistas y otras publicaciones periódicas", section: "J" },
  { code: "5819", description: "Otros trabajos de edición", section: "J" },
  { code: "5820", description: "Edición de programas de informática (software)", section: "J" },
  { code: "5911", description: "Actividades de producción de películas cinematográficas, videos", section: "J" },
  { code: "5912", description: "Actividades de postproducción de películas cinematográficas, videos", section: "J" },
  { code: "5913", description: "Actividades de distribución de películas cinematográficas, videos", section: "J" },
  { code: "5914", description: "Actividades de exhibición de películas cinematográficas y videos", section: "J" },
  { code: "5920", description: "Actividades de grabación de sonido y edición de música", section: "J" },
  { code: "6010", description: "Actividades de programación y transmisión en el servicio de radiodifusión sonora", section: "J" },
  { code: "6020", description: "Actividades de programación y transmisión de televisión", section: "J" },
  { code: "6110", description: "Actividades de telecomunicaciones alámbricas", section: "J" },
  { code: "6120", description: "Actividades de telecomunicaciones inalámbricas", section: "J" },
  { code: "6130", description: "Actividades de telecomunicación satelital", section: "J" },
  { code: "6190", description: "Otras actividades de telecomunicaciones", section: "J" },
  { code: "6201", description: "Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño)", section: "J" },
  { code: "6202", description: "Actividades de consultoría informática y actividades de administración de instalaciones informáticas", section: "J" },
  { code: "6209", description: "Otras actividades de tecnologías de información y actividades de servicios informáticos", section: "J" },
  { code: "6311", description: "Procesamiento de datos, alojamiento (hosting) y actividades relacionadas", section: "J" },
  { code: "6312", description: "Portales web", section: "J" },
  { code: "6391", description: "Actividades de agencias de noticias", section: "J" },
  { code: "6399", description: "Otras actividades de servicio de información n.c.p.", section: "J" },

  // SECCIÓN K - ACTIVIDADES FINANCIERAS Y DE SEGUROS
  { code: "6411", description: "Banco Central", section: "K" },
  { code: "6412", description: "Bancos comerciales", section: "K" },
  { code: "6421", description: "Actividades de las corporaciones financieras", section: "K" },
  { code: "6422", description: "Actividades de las compañías de financiamiento", section: "K" },
  { code: "6423", description: "Banca de segundo piso", section: "K" },
  { code: "6424", description: "Actividades de las cooperativas financieras", section: "K" },
  { code: "6431", description: "Fideicomisos, fondos y entidades financieras similares", section: "K" },
  { code: "6432", description: "Fondos de cesantías", section: "K" },
  { code: "6491", description: "Leasing financiero (arrendamiento financiero)", section: "K" },
  { code: "6492", description: "Actividades financieras de fondos de empleados y otras formas asociativas", section: "K" },
  { code: "6493", description: "Actividades de compra de cartera o factoring", section: "K" },
  { code: "6494", description: "Otras actividades de distribución de fondos", section: "K" },
  { code: "6495", description: "Instituciones especiales oficiales", section: "K" },
  { code: "6499", description: "Otras actividades de servicio financiero, excepto las de seguros", section: "K" },
  { code: "6511", description: "Seguros generales", section: "K" },
  { code: "6512", description: "Seguros de vida", section: "K" },
  { code: "6513", description: "Reaseguros", section: "K" },
  { code: "6514", description: "Capitalización", section: "K" },
  { code: "6521", description: "Servicios de seguros sociales de salud", section: "K" },
  { code: "6522", description: "Servicios de seguros sociales de riesgos profesionales", section: "K" },
  { code: "6531", description: "Régimen de prima media con prestación definida (RPM)", section: "K" },
  { code: "6532", description: "Régimen de ahorro individual (RAI)", section: "K" },
  { code: "6611", description: "Administración de mercados financieros", section: "K" },
  { code: "6612", description: "Corretaje de valores y de contratos de productos básicos", section: "K" },
  { code: "6613", description: "Otras actividades relacionadas con el mercado de valores", section: "K" },
  { code: "6614", description: "Actividades de las casas de cambio", section: "K" },
  { code: "6615", description: "Actividades de los profesionales de compra y venta de divisas", section: "K" },
  { code: "6619", description: "Otras actividades auxiliares de las actividades de servicios financieros n.c.p.", section: "K" },
  { code: "6621", description: "Actividades de agentes y corredores de seguros", section: "K" },
  { code: "6629", description: "Evaluación de riesgos y daños, y otras actividades de servicios auxiliares", section: "K" },
  { code: "6630", description: "Actividades de administración de fondos", section: "K" },

  // SECCIÓN L - ACTIVIDADES INMOBILIARIAS
  { code: "6810", description: "Actividades inmobiliarias realizadas con bienes propios o arrendados", section: "L" },
  { code: "6820", description: "Actividades inmobiliarias realizadas a cambio de una retribución o por contrata", section: "L" },

  // SECCIÓN M - ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS
  { code: "6910", description: "Actividades jurídicas", section: "M" },
  { code: "6920", description: "Actividades de contabilidad, teneduría de libros, auditoría financiera", section: "M" },
  { code: "7010", description: "Actividades de administración empresarial", section: "M" },
  { code: "7020", description: "Actividades de consultaría de gestión", section: "M" },
  { code: "7110", description: "Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica", section: "M" },
  { code: "7120", description: "Ensayos y análisis técnicos", section: "M" },
  { code: "7210", description: "Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería", section: "M" },
  { code: "7220", description: "Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades", section: "M" },
  { code: "7310", description: "Publicidad", section: "M" },
  { code: "7320", description: "Estudios de mercado y realización de encuestas de opinión pública", section: "M" },
  { code: "7410", description: "Actividades especializadas de diseño", section: "M" },
  { code: "7420", description: "Actividades de fotografía", section: "M" },
  { code: "7490", description: "Otras actividades profesionales, científicas y técnicas n.c.p.", section: "M" },
  { code: "7500", description: "Actividades veterinarias", section: "M" },

  // SECCIÓN N - ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO
  { code: "7710", description: "Alquiler y arrendamiento de vehículos automotores", section: "N" },
  { code: "7721", description: "Alquiler y arrendamiento de equipo recreativo y deportivo", section: "N" },
  { code: "7722", description: "Alquiler de videos y discos", section: "N" },
  { code: "7729", description: "Alquiler y arrendamiento de otros efectos personales y enseres domésticos", section: "N" },
  { code: "7730", description: "Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.", section: "N" },
  { code: "7740", description: "Arrendamiento de propiedad intelectual y productos similares", section: "N" },
  { code: "7810", description: "Actividades de agencias de empleo", section: "N" },
  { code: "7820", description: "Actividades de agencias de empleo temporal", section: "N" },
  { code: "7830", description: "Otras actividades de suministro de recurso humano", section: "N" },
  { code: "7911", description: "Actividades de las agencias de viaje", section: "N" },
  { code: "7912", description: "Actividades de operadores turísticos", section: "N" },
  { code: "7990", description: "Otros servicios de reserva y actividades relacionadas", section: "N" },
  { code: "8010", description: "Actividades de seguridad privada", section: "N" },
  { code: "8020", description: "Actividades de servicios de sistemas de seguridad", section: "N" },
  { code: "8030", description: "Actividades de detectives e investigadores privados", section: "N" },
  { code: "8110", description: "Actividades combinadas de apoyo a instalaciones", section: "N" },
  { code: "8121", description: "Limpieza general interior de edificios", section: "N" },
  { code: "8129", description: "Otras actividades de limpieza de edificios e instalaciones industriales", section: "N" },
  { code: "8130", description: "Actividades de paisajismo y servicios de mantenimiento conexos", section: "N" },
  { code: "8211", description: "Actividades combinadas de servicios administrativos de oficina", section: "N" },
  { code: "8219", description: "Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina", section: "N" },
  { code: "8220", description: "Actividades de centros de llamadas (Call center)", section: "N" },
  { code: "8230", description: "Organización de convenciones y eventos comerciales", section: "N" },
  { code: "8291", description: "Actividades de agencias de cobranza y oficinas de calificación crediticia", section: "N" },
  { code: "8292", description: "Actividades de envase y empaque", section: "N" },
  { code: "8299", description: "Otras actividades de servicio de apoyo a las empresas n.c.p.", section: "N" },

  // SECCIÓN O - ADMINISTRACIÓN PÚBLICA Y DEFENSA
  { code: "8411", description: "Actividades legislativas de la administración pública", section: "O" },
  { code: "8412", description: "Actividades ejecutivas de la administración pública", section: "O" },
  { code: "8413", description: "Regulación de las actividades de organismos que prestan servicios de salud, educativos", section: "O" },
  { code: "8414", description: "Actividades reguladoras y facilitadoras de la actividad económica", section: "O" },
  { code: "8415", description: "Actividades de los otros órganos de control", section: "O" },
  { code: "8421", description: "Relaciones exteriores", section: "O" },
  { code: "8422", description: "Actividades de defensa", section: "O" },
  { code: "8423", description: "Orden público y actividades de seguridad", section: "O" },
  { code: "8424", description: "Administración de justicia", section: "O" },
  { code: "8430", description: "Actividades de planes de seguridad social de afiliación obligatoria", section: "O" },

  // SECCIÓN P - EDUCACIÓN
  { code: "8511", description: "Educación de la primera infancia", section: "P" },
  { code: "8512", description: "Educación preescolar", section: "P" },
  { code: "8513", description: "Educación básica primaria", section: "P" },
  { code: "8521", description: "Educación básica secundaria", section: "P" },
  { code: "8522", description: "Educación media académica", section: "P" },
  { code: "8523", description: "Educación media técnica y de formación laboral", section: "P" },
  { code: "8530", description: "Establecimientos que combinan diferentes niveles de educación", section: "P" },
  { code: "8541", description: "Educación técnica profesional", section: "P" },
  { code: "8542", description: "Educación tecnológica", section: "P" },
  { code: "8543", description: "Educación de instituciones universitarias o de escuelas tecnológicas", section: "P" },
  { code: "8544", description: "Educación de universidades", section: "P" },
  { code: "8551", description: "Formación para el trabajo", section: "P" },
  { code: "8552", description: "Enseñanza deportiva y recreativa", section: "P" },
  { code: "8553", description: "Enseñanza cultural", section: "P" },
  { code: "8559", description: "Otros tipos de educación n.c.p.", section: "P" },
  { code: "8560", description: "Actividades de apoyo a la educación", section: "P" },

  // SECCIÓN Q - ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL
  { code: "8610", description: "Actividades de hospitales y clínicas, con internación", section: "Q" },
  { code: "8621", description: "Actividades de la práctica médica, sin internación", section: "Q" },
  { code: "8622", description: "Actividades de la práctica odontológica", section: "Q" },
  { code: "8691", description: "Actividades de apoyo diagnóstico", section: "Q" },
  { code: "8692", description: "Actividades de apoyo terapéutico", section: "Q" },
  { code: "8699", description: "Otras actividades de atención de la salud humana", section: "Q" },
  { code: "8710", description: "Actividades de atención residencial medicalizada de tipo general", section: "Q" },
  { code: "8720", description: "Actividades de atención residencial, para el cuidado de pacientes con retardo mental", section: "Q" },
  { code: "8730", description: "Actividades de atención en instituciones para el cuidado de personas mayores", section: "Q" },
  { code: "8790", description: "Otras actividades de atención en instituciones con alojamiento", section: "Q" },
  { code: "8810", description: "Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas", section: "Q" },
  { code: "8890", description: "Otras actividades de asistencia social sin alojamiento", section: "Q" },

  // SECCIÓN R - ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN
  { code: "9001", description: "Creación literaria", section: "R" },
  { code: "9002", description: "Creación musical", section: "R" },
  { code: "9003", description: "Creación teatral", section: "R" },
  { code: "9004", description: "Creación audiovisual", section: "R" },
  { code: "9005", description: "Artes plásticas y visuales", section: "R" },
  { code: "9006", description: "Actividades teatrales", section: "R" },
  { code: "9007", description: "Actividades de espectáculos musicales en vivo", section: "R" },
  { code: "9008", description: "Otras actividades de espectáculos en vivo", section: "R" },
  { code: "9101", description: "Actividades de bibliotecas y archivos", section: "R" },
  { code: "9102", description: "Actividades y funcionamiento de museos, conservación de edificios y sitios históricos", section: "R" },
  { code: "9103", description: "Actividades de jardines botánicos, zoológicos y reservas naturales", section: "R" },
  { code: "9200", description: "Actividades de juegos de azar y apuestas", section: "R" },
  { code: "9311", description: "Gestión de instalaciones deportivas", section: "R" },
  { code: "9312", description: "Actividades de clubes deportivos", section: "R" },
  { code: "9319", description: "Otras actividades deportivas", section: "R" },
  { code: "9321", description: "Actividades de parques de atracciones y parques temáticos", section: "R" },
  { code: "9329", description: "Otras actividades recreativas y de esparcimiento n.c.p.", section: "R" },

  // SECCIÓN S - OTRAS ACTIVIDADES DE SERVICIOS
  { code: "9411", description: "Actividades de asociaciones empresariales y de empleadores", section: "S" },
  { code: "9412", description: "Actividades de asociaciones profesionales", section: "S" },
  { code: "9420", description: "Actividades de sindicatos de empleados", section: "S" },
  { code: "9491", description: "Actividades de asociaciones religiosas", section: "S" },
  { code: "9492", description: "Actividades de asociaciones políticas", section: "S" },
  { code: "9499", description: "Actividades de otras asociaciones n.c.p.", section: "S" },
  { code: "9511", description: "Mantenimiento y reparación de computadores y de equipo periférico", section: "S" },
  { code: "9512", description: "Mantenimiento y reparación de equipos de comunicación", section: "S" },
  { code: "9521", description: "Mantenimiento y reparación de aparatos electrónicos de consumo", section: "S" },
  { code: "9522", description: "Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería", section: "S" },
  { code: "9523", description: "Reparación de calzado y artículos de cuero", section: "S" },
  { code: "9524", description: "Reparación de muebles y accesorios para el hogar", section: "S" },
  { code: "9529", description: "Mantenimiento y reparación de otros efectos personales y enseres domésticos", section: "S" },
  { code: "9601", description: "Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel", section: "S" },
  { code: "9602", description: "Peluquería y otros tratamientos de belleza", section: "S" },
  { code: "9603", description: "Pompas fúnebres y actividades relacionadas", section: "S" },
  { code: "9609", description: "Otras actividades de servicios personales n.c.p.", section: "S" },

  // SECCIÓN T - ACTIVIDADES DE LOS HOGARES INDIVIDUALES COMO EMPLEADORES
  { code: "9700", description: "Actividades de los hogares individuales como empleadores de personal doméstico", section: "T" },
  { code: "9810", description: "Actividades no diferenciadas de los hogares individuales como productores de bienes", section: "T" },
  { code: "9820", description: "Actividades no diferenciadas de los hogares individuales como productores de servicios", section: "T" },

  // SECCIÓN U - ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTRATERRITORIALES
  { code: "9900", description: "Actividades de organizaciones y entidades extraterritoriales", section: "U" },
];

export const CIIU_SECTIONS: Record<string, string> = {
  "A": "Agricultura, ganadería, caza, silvicultura y pesca",
  "B": "Explotación de minas y canteras",
  "C": "Industrias manufactureras",
  "D": "Suministro de electricidad, gas, vapor y aire acondicionado",
  "E": "Distribución de agua; evacuación y tratamiento de aguas residuales",
  "F": "Construcción",
  "G": "Comercio al por mayor y al por menor",
  "H": "Transporte y almacenamiento",
  "I": "Alojamiento y servicios de comida",
  "J": "Información y comunicaciones",
  "K": "Actividades financieras y de seguros",
  "L": "Actividades inmobiliarias",
  "M": "Actividades profesionales, científicas y técnicas",
  "N": "Actividades de servicios administrativos y de apoyo",
  "O": "Administración pública y defensa",
  "P": "Educación",
  "Q": "Actividades de atención de la salud humana",
  "R": "Actividades artísticas, de entretenimiento y recreación",
  "S": "Otras actividades de servicios",
  "T": "Actividades de los hogares individuales",
  "U": "Actividades de organizaciones extraterritoriales",
};

export function getCiiuLabel(code: string): string {
  const ciiu = CIIU_CODES.find(c => c.code === code);
  return ciiu ? `${ciiu.code} - ${ciiu.description}` : code;
}

export function getCiiuBySection(section: string): CiiuCode[] {
  return CIIU_CODES.filter(c => c.section === section);
}
