export interface DailyChallenge {
  dragEmoji: string;
  dropEmoji: string;
  dragName: string;
  successEmoji: string;
  successMessage: string;
}

export const ALL_CHALLENGES: DailyChallenge[] = [
  { dragEmoji: "⛑️", dropEmoji: "👷", dragName: "Casco de Seguridad", successEmoji: "👷‍♂️", successMessage: "EPP listo. A trabajar seguro!" },
  { dragEmoji: "🍎", dropEmoji: "❤️", dragName: "Manzana Saludable", successEmoji: "💪", successMessage: "Salud ocupacional al dia!" },
  { dragEmoji: "🧯", dropEmoji: "🔥", dragName: "Extintor", successEmoji: "✅", successMessage: "Emergencia controlada!" },
  { dragEmoji: "📋", dropEmoji: "🎓", dragName: "Plan de Capacitacion", successEmoji: "🏆", successMessage: "Capacitacion registrada!" },
  { dragEmoji: "🛡️", dropEmoji: "⚠️", dragName: "Escudo de Prevencion", successEmoji: "🦺", successMessage: "Riesgos bajo control!" },
  { dragEmoji: "📊", dropEmoji: "📈", dragName: "Informe de Gestion", successEmoji: "💯", successMessage: "Indicadores al dia!" },
  { dragEmoji: "🚗", dropEmoji: "🛣️", dragName: "Vehiculo Seguro", successEmoji: "🏁", successMessage: "PESV: Seguridad vial activa!" },
  { dragEmoji: "🥾", dropEmoji: "🦶", dragName: "Bota de Seguridad", successEmoji: "🚶", successMessage: "Pisando firme y seguro!" },
  { dragEmoji: "🧤", dropEmoji: "🤚", dragName: "Guantes de Proteccion", successEmoji: "👐", successMessage: "Manos protegidas!" },
  { dragEmoji: "🥽", dropEmoji: "👀", dragName: "Gafas de Seguridad", successEmoji: "👓", successMessage: "Vision protegida!" },
  { dragEmoji: "🔔", dropEmoji: "📢", dragName: "Alarma de Emergencia", successEmoji: "🔊", successMessage: "Alerta activada!" },
  { dragEmoji: "💉", dropEmoji: "🏥", dragName: "Vacuna Ocupacional", successEmoji: "💊", successMessage: "Salud preventiva al dia!" },
  { dragEmoji: "🩺", dropEmoji: "👨‍⚕️", dragName: "Estetoscopio Medico", successEmoji: "🏥", successMessage: "Examen medico completado!" },
  { dragEmoji: "📝", dropEmoji: "📂", dragName: "Acta de Reunion", successEmoji: "✅", successMessage: "Acta del COPASST archivada!" },
  { dragEmoji: "🔧", dropEmoji: "⚙️", dragName: "Herramienta Segura", successEmoji: "🛠️", successMessage: "Mantenimiento preventivo OK!" },
  { dragEmoji: "🪜", dropEmoji: "🏗️", dragName: "Escalera Certificada", successEmoji: "🏢", successMessage: "Trabajo en alturas seguro!" },
  { dragEmoji: "🎒", dropEmoji: "🧰", dragName: "Kit de Emergencia", successEmoji: "🆘", successMessage: "Brigada preparada!" },
  { dragEmoji: "📖", dropEmoji: "👨‍🏫", dragName: "Manual de SST", successEmoji: "📚", successMessage: "Conocimiento es prevencion!" },
  { dragEmoji: "🔦", dropEmoji: "🌑", dragName: "Linterna de Emergencia", successEmoji: "💡", successMessage: "Ruta de evacuacion iluminada!" },
  { dragEmoji: "🪪", dropEmoji: "🏢", dragName: "Carnet de Seguridad", successEmoji: "🎫", successMessage: "Acceso autorizado!" },
  { dragEmoji: "🧹", dropEmoji: "🏭", dragName: "Limpieza Industrial", successEmoji: "✨", successMessage: "Orden y aseo impecable!" },
  { dragEmoji: "🗺️", dropEmoji: "🚪", dragName: "Plano de Evacuacion", successEmoji: "🏃", successMessage: "Ruta de evacuacion lista!" },
  { dragEmoji: "📻", dropEmoji: "🎙️", dragName: "Radio de Emergencia", successEmoji: "📡", successMessage: "Comunicacion de crisis activa!" },
  { dragEmoji: "🧲", dropEmoji: "⚡", dragName: "Proteccion Electrica", successEmoji: "🔌", successMessage: "Riesgo electrico controlado!" },
  { dragEmoji: "🌡️", dropEmoji: "🥵", dragName: "Monitor de Temperatura", successEmoji: "❄️", successMessage: "Estres termico bajo control!" },
  { dragEmoji: "🫁", dropEmoji: "😷", dragName: "Respirador N95", successEmoji: "🌬️", successMessage: "Aire limpio garantizado!" },
  { dragEmoji: "🎯", dropEmoji: "📌", dragName: "Meta de Seguridad", successEmoji: "🏅", successMessage: "Objetivo SST cumplido!" },
  { dragEmoji: "📐", dropEmoji: "🪑", dragName: "Evaluacion Ergonomica", successEmoji: "💺", successMessage: "Puesto de trabajo ajustado!" },
  { dragEmoji: "🔒", dropEmoji: "🚧", dragName: "Candado de Bloqueo", successEmoji: "🔐", successMessage: "LOTO aplicado correctamente!" },
  { dragEmoji: "🩹", dropEmoji: "🤕", dragName: "Botiquin de Primeros Auxilios", successEmoji: "🏥", successMessage: "Primeros auxilios listos!" },
  { dragEmoji: "📣", dropEmoji: "👥", dragName: "Charla de Seguridad", successEmoji: "🗣️", successMessage: "Charla de 5 minutos completada!" },
  { dragEmoji: "🪧", dropEmoji: "🚫", dragName: "Senal de Prohibicion", successEmoji: "🚷", successMessage: "Zona restringida senalizada!" },
  { dragEmoji: "🔬", dropEmoji: "🧪", dragName: "Muestra de Laboratorio", successEmoji: "🧫", successMessage: "Monitoreo ambiental OK!" },
  { dragEmoji: "🎓", dropEmoji: "📜", dragName: "Certificacion SST", successEmoji: "🏆", successMessage: "Profesional certificado!" },
  { dragEmoji: "🚑", dropEmoji: "🏨", dragName: "Ambulancia", successEmoji: "⛑️", successMessage: "Plan de emergencia activo!" },
  { dragEmoji: "🗂️", dropEmoji: "🗄️", dragName: "Expediente del Trabajador", successEmoji: "📁", successMessage: "Documentacion completa!" },
  { dragEmoji: "📅", dropEmoji: "✏️", dragName: "Cronograma de Actividades", successEmoji: "📆", successMessage: "Plan anual actualizado!" },
  { dragEmoji: "🔊", dropEmoji: "👂", dragName: "Proteccion Auditiva", successEmoji: "🎧", successMessage: "Audiometria al dia!" },
  { dragEmoji: "🧴", dropEmoji: "☀️", dragName: "Protector Solar", successEmoji: "🌤️", successMessage: "Piel protegida del sol!" },
  { dragEmoji: "💧", dropEmoji: "🚰", dragName: "Agua Potable", successEmoji: "🥤", successMessage: "Hidratacion garantizada!" },
  { dragEmoji: "🪣", dropEmoji: "☣️", dragName: "Kit Antiderrames", successEmoji: "🧽", successMessage: "Derrame contenido!" },
  { dragEmoji: "📷", dropEmoji: "🔍", dragName: "Inspeccion Fotografica", successEmoji: "📸", successMessage: "Evidencia registrada!" },
  { dragEmoji: "🧯", dropEmoji: "🏢", dragName: "Recarga del Extintor", successEmoji: "✅", successMessage: "Extintor vigente!" },
  { dragEmoji: "🪖", dropEmoji: "🏗️", dragName: "Casco para Alturas", successEmoji: "⛑️", successMessage: "Trabajo en alturas aprobado!" },
  { dragEmoji: "📱", dropEmoji: "🆘", dragName: "App de Emergencia", successEmoji: "📲", successMessage: "Reporte inmediato enviado!" },
  { dragEmoji: "🧪", dropEmoji: "💨", dragName: "Medicion de Gases", successEmoji: "🌿", successMessage: "Atmosfera segura!" },
  { dragEmoji: "🪢", dropEmoji: "🧗", dragName: "Arnes de Seguridad", successEmoji: "🦺", successMessage: "Anclaje verificado!" },
  { dragEmoji: "🔋", dropEmoji: "💡", dragName: "Luz de Emergencia", successEmoji: "🔦", successMessage: "Iluminacion de respaldo OK!" },
  { dragEmoji: "🗓️", dropEmoji: "🩺", dragName: "Cita Medica Ocupacional", successEmoji: "👨‍⚕️", successMessage: "Control medico programado!" },
  { dragEmoji: "🚿", dropEmoji: "👁️", dragName: "Ducha Lavaojos", successEmoji: "💧", successMessage: "Estacion de emergencia lista!" },
  { dragEmoji: "📦", dropEmoji: "🏷️", dragName: "Etiqueta SGA", successEmoji: "⚗️", successMessage: "Quimico identificado!" },
  { dragEmoji: "🚜", dropEmoji: "🅿️", dragName: "Vehiculo Industrial", successEmoji: "🏁", successMessage: "Operador certificado!" },
  { dragEmoji: "🌊", dropEmoji: "🏖️", dragName: "Plan de Inundacion", successEmoji: "🌈", successMessage: "Riesgo natural mitigado!" },
  { dragEmoji: "🦠", dropEmoji: "🧫", dragName: "Control Biologico", successEmoji: "🔬", successMessage: "Riesgo biologico controlado!" },
  { dragEmoji: "🎪", dropEmoji: "🏟️", dragName: "Simulacro General", successEmoji: "🎖️", successMessage: "Simulacro exitoso!" },
  { dragEmoji: "🪞", dropEmoji: "🧑‍💼", dragName: "Autoevaluacion SST", successEmoji: "📊", successMessage: "Autoevaluacion completada!" },
  { dragEmoji: "🌿", dropEmoji: "🏞️", dragName: "Plan Ambiental", successEmoji: "🌍", successMessage: "Ambiente laboral saludable!" },
  { dragEmoji: "🎭", dropEmoji: "🧠", dragName: "Evaluacion Psicosocial", successEmoji: "😊", successMessage: "Bienestar emocional OK!" },
  { dragEmoji: "🪶", dropEmoji: "📝", dragName: "Politica de SST", successEmoji: "📄", successMessage: "Politica firmada y vigente!" },
  { dragEmoji: "🔑", dropEmoji: "🚪", dragName: "Llave de Seguridad", successEmoji: "🔓", successMessage: "Area asegurada!" },
  { dragEmoji: "🎬", dropEmoji: "📺", dragName: "Video de Induccion", successEmoji: "🎥", successMessage: "Induccion completada!" },
  { dragEmoji: "🌐", dropEmoji: "💻", dragName: "Reporte Digital SST", successEmoji: "🖥️", successMessage: "Reporte enviado al sistema!" },
  { dragEmoji: "🧊", dropEmoji: "🥶", dragName: "Proteccion contra Frio", successEmoji: "🧣", successMessage: "Trabajador abrigado!" },
  { dragEmoji: "🪤", dropEmoji: "🐀", dragName: "Control de Plagas", successEmoji: "🧹", successMessage: "Instalaciones libres de plagas!" },
  { dragEmoji: "🔩", dropEmoji: "🏗️", dragName: "Tornillo de Anclaje", successEmoji: "🔨", successMessage: "Estructura asegurada!" },
  { dragEmoji: "🧬", dropEmoji: "🏥", dragName: "Perfil Epidemiologico", successEmoji: "📊", successMessage: "Perfil de salud actualizado!" },
  { dragEmoji: "🎤", dropEmoji: "👨‍💼", dragName: "Rendicion de Cuentas", successEmoji: "📢", successMessage: "Gestion transparente!" },
  { dragEmoji: "🧭", dropEmoji: "🗺️", dragName: "Brujula de Prevencion", successEmoji: "🧭", successMessage: "Rumbo seguro establecido!" },
  { dragEmoji: "💼", dropEmoji: "🏢", dragName: "Maletin del Inspector", successEmoji: "🔍", successMessage: "Inspeccion programada!" },
  { dragEmoji: "🪚", dropEmoji: "🪵", dragName: "Sierra Protegida", successEmoji: "🛡️", successMessage: "Herramienta con guarda!" },
  { dragEmoji: "🧰", dropEmoji: "🔧", dragName: "Caja de Herramientas", successEmoji: "🛠️", successMessage: "Herramientas inspeccionadas!" },
  { dragEmoji: "🏋️", dropEmoji: "🧘", dragName: "Pausa Activa", successEmoji: "🤸", successMessage: "Pausa activa realizada!" },
  { dragEmoji: "🚦", dropEmoji: "🛑", dragName: "Semaforo Vial", successEmoji: "🟢", successMessage: "Transito seguro!" },
  { dragEmoji: "🧑‍🚒", dropEmoji: "🔥", dragName: "Brigadista", successEmoji: "🦸", successMessage: "Brigadista en posicion!" },
  { dragEmoji: "🪟", dropEmoji: "🌬️", dragName: "Ventilacion Natural", successEmoji: "💨", successMessage: "Ventilacion adecuada!" },
  { dragEmoji: "🛞", dropEmoji: "🚙", dragName: "Llanta en Buen Estado", successEmoji: "🏎️", successMessage: "Vehiculo revisado!" },
  { dragEmoji: "📌", dropEmoji: "🗂️", dragName: "Registro de Incidentes", successEmoji: "📋", successMessage: "Incidente documentado!" },
  { dragEmoji: "🥇", dropEmoji: "🏆", dragName: "Premio Cero Accidentes", successEmoji: "🎉", successMessage: "Cero accidentes este mes!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "💊", dragName: "Medico Ocupacional", successEmoji: "🩺", successMessage: "Consulta medica OK!" },
  { dragEmoji: "🪫", dropEmoji: "🔌", dragName: "Bateria de Respaldo", successEmoji: "⚡", successMessage: "Energia de emergencia lista!" },
  { dragEmoji: "🎪", dropEmoji: "👷‍♀️", dragName: "Jornada de SST", successEmoji: "🎊", successMessage: "Jornada de seguridad exitosa!" },
  { dragEmoji: "🔭", dropEmoji: "🌄", dragName: "Vigilancia Epidemiologica", successEmoji: "📡", successMessage: "SVE actualizado!" },
  { dragEmoji: "🪝", dropEmoji: "⚓", dragName: "Gancho de Seguridad", successEmoji: "🔗", successMessage: "Punto de anclaje fijo!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "🔬", dragName: "Higienista Industrial", successEmoji: "🧪", successMessage: "Medicion higienica OK!" },
  { dragEmoji: "🎾", dropEmoji: "🏃‍♂️", dragName: "Programa Deportivo", successEmoji: "🏅", successMessage: "Bienestar fisico activo!" },
  { dragEmoji: "🌻", dropEmoji: "🧘‍♀️", dragName: "Programa de Bienestar", successEmoji: "🌸", successMessage: "Bienestar integral!" },
  { dragEmoji: "🔫", dropEmoji: "🚫", dragName: "Control de Armas", successEmoji: "🛡️", successMessage: "Zona libre de armas!" },
  { dragEmoji: "🧲", dropEmoji: "🧲", dragName: "Campo Magnetico", successEmoji: "📡", successMessage: "Radiacion no ionizante OK!" },
  { dragEmoji: "🌋", dropEmoji: "🏔️", dragName: "Plan Volcanico", successEmoji: "🛡️", successMessage: "Plan de contingencia listo!" },
  { dragEmoji: "🌪️", dropEmoji: "🏠", dragName: "Plan contra Tormentas", successEmoji: "☀️", successMessage: "Refugio seguro identificado!" },
  { dragEmoji: "⏱️", dropEmoji: "🕐", dragName: "Control de Jornada", successEmoji: "⌛", successMessage: "Jornada laboral legal!" },
  { dragEmoji: "🪙", dropEmoji: "💰", dragName: "Presupuesto SST", successEmoji: "💵", successMessage: "Recursos asignados!" },
  { dragEmoji: "🖊️", dropEmoji: "📑", dragName: "Firma de Compromiso", successEmoji: "✍️", successMessage: "Compromiso adquirido!" },
  { dragEmoji: "🧑‍🍳", dropEmoji: "🍽️", dragName: "Higiene Alimentaria", successEmoji: "✅", successMessage: "Alimentos seguros!" },
  { dragEmoji: "🎧", dropEmoji: "🔇", dragName: "Tapones Auditivos", successEmoji: "🤫", successMessage: "Ruido controlado!" },
  { dragEmoji: "🚰", dropEmoji: "🧪", dragName: "Calidad del Agua", successEmoji: "💎", successMessage: "Agua potable verificada!" },
  { dragEmoji: "🛗", dropEmoji: "🔧", dragName: "Mantenimiento Ascensor", successEmoji: "✅", successMessage: "Ascensor certificado!" },
  { dragEmoji: "🧯", dropEmoji: "🧑‍🚒", dragName: "Practica con Extintor", successEmoji: "🔥", successMessage: "Practica contra incendios OK!" },
  { dragEmoji: "🪜", dropEmoji: "📏", dragName: "Inspeccion de Escalera", successEmoji: "✅", successMessage: "Escalera aprobada!" },
  { dragEmoji: "🧲", dropEmoji: "🪛", dragName: "Detector de Metales", successEmoji: "🔍", successMessage: "Area libre de objetos!" },
  { dragEmoji: "🌬️", dropEmoji: "🫧", dragName: "Calidad del Aire", successEmoji: "🌿", successMessage: "Aire interior saludable!" },
  { dragEmoji: "🧱", dropEmoji: "🏗️", dragName: "Inspeccion Estructural", successEmoji: "🏛️", successMessage: "Estructura solida!" },
  { dragEmoji: "🏍️", dropEmoji: "🛣️", dragName: "Moto con Casco", successEmoji: "⛑️", successMessage: "Motociclista protegido!" },
  { dragEmoji: "🚌", dropEmoji: "🚏", dragName: "Transporte de Personal", successEmoji: "🚍", successMessage: "Transporte seguro!" },
  { dragEmoji: "🔌", dropEmoji: "🧯", dragName: "Cableado Electrico", successEmoji: "⚡", successMessage: "Instalacion electrica segura!" },
  { dragEmoji: "🧫", dropEmoji: "🦠", dragName: "Protocolo Bioseguridad", successEmoji: "🛡️", successMessage: "Bioseguridad activa!" },
  { dragEmoji: "🗑️", dropEmoji: "♻️", dragName: "Residuos Peligrosos", successEmoji: "🌱", successMessage: "Residuos bien clasificados!" },
  { dragEmoji: "🌙", dropEmoji: "🛏️", dragName: "Turno Nocturno Seguro", successEmoji: "🌟", successMessage: "Turno nocturno protegido!" },
  { dragEmoji: "☔", dropEmoji: "🧥", dragName: "Impermeable de Trabajo", successEmoji: "🌧️", successMessage: "Protegido de la lluvia!" },
  { dragEmoji: "🧯", dropEmoji: "🏪", dragName: "Extintor del Local", successEmoji: "🔥", successMessage: "Local comercial seguro!" },
  { dragEmoji: "📎", dropEmoji: "📚", dragName: "Carpeta de Evidencias", successEmoji: "🗃️", successMessage: "Evidencias organizadas!" },
  { dragEmoji: "🩻", dropEmoji: "🏥", dragName: "Rayos X Ocupacional", successEmoji: "🩺", successMessage: "Examen radiologico OK!" },
  { dragEmoji: "🧑‍✈️", dropEmoji: "✈️", dragName: "Seguridad Aeroportuaria", successEmoji: "🛫", successMessage: "Vuelo seguro!" },
  { dragEmoji: "🚢", dropEmoji: "⚓", dragName: "Seguridad Maritima", successEmoji: "🛟", successMessage: "Navegacion segura!" },
  { dragEmoji: "🧊", dropEmoji: "🥩", dragName: "Cadena de Frio", successEmoji: "❄️", successMessage: "Cadena de frio intacta!" },
  { dragEmoji: "🔆", dropEmoji: "🕶️", dragName: "Proteccion UV", successEmoji: "🌞", successMessage: "Ojos protegidos del sol!" },
  { dragEmoji: "🧑‍🏭", dropEmoji: "🏭", dragName: "Operario Capacitado", successEmoji: "🎓", successMessage: "Operario certificado!" },
  { dragEmoji: "🪛", dropEmoji: "🔩", dragName: "Destornillador Aislado", successEmoji: "🛡️", successMessage: "Herramienta dielectrica!" },
  { dragEmoji: "🚧", dropEmoji: "🛑", dragName: "Barricada de Seguridad", successEmoji: "🚧", successMessage: "Zona demarcada!" },
  { dragEmoji: "📡", dropEmoji: "🌐", dragName: "Sistema de Monitoreo", successEmoji: "🖥️", successMessage: "Monitoreo en tiempo real!" },
  { dragEmoji: "🧪", dropEmoji: "🔥", dragName: "Prueba de Inflamabilidad", successEmoji: "📊", successMessage: "Material no inflamable!" },
  { dragEmoji: "🌾", dropEmoji: "🚜", dragName: "Seguridad Agricola", successEmoji: "🌻", successMessage: "Campo seguro!" },
  { dragEmoji: "⛏️", dropEmoji: "🏔️", dragName: "Seguridad Minera", successEmoji: "💎", successMessage: "Mina asegurada!" },
  { dragEmoji: "🧑‍🔧", dropEmoji: "🔩", dragName: "Tecnico de Mantenimiento", successEmoji: "🔧", successMessage: "Mantenimiento completado!" },
  { dragEmoji: "🎗️", dropEmoji: "👥", dragName: "Campana de Salud", successEmoji: "🏥", successMessage: "Campana de salud exitosa!" },
  { dragEmoji: "🪞", dropEmoji: "🚗", dragName: "Espejo Retrovisor", successEmoji: "👁️", successMessage: "Visibilidad completa!" },
  { dragEmoji: "🔔", dropEmoji: "🏢", dragName: "Alarma Contra Incendios", successEmoji: "🧯", successMessage: "Sistema contra incendios OK!" },
  { dragEmoji: "🩸", dropEmoji: "🏥", dragName: "Banco de Sangre", successEmoji: "❤️", successMessage: "Donacion de sangre activa!" },
  { dragEmoji: "🧯", dropEmoji: "⛽", dragName: "Extintor de Gasolinera", successEmoji: "✅", successMessage: "Estacion de servicio segura!" },
  { dragEmoji: "📲", dropEmoji: "🔔", dragName: "Notificacion de Alerta", successEmoji: "📳", successMessage: "Alerta enviada a todos!" },
  { dragEmoji: "🧑‍💻", dropEmoji: "🖥️", dragName: "Ergonomia Digital", successEmoji: "💺", successMessage: "Pantalla a buena distancia!" },
  { dragEmoji: "🪒", dropEmoji: "🚫", dragName: "Objeto Cortopunzante", successEmoji: "🛡️", successMessage: "Cortopunzante descartado!" },
  { dragEmoji: "🌡️", dropEmoji: "🧑‍⚕️", dragName: "Toma de Temperatura", successEmoji: "✅", successMessage: "Temperatura normal!" },
  { dragEmoji: "🚒", dropEmoji: "🏢", dragName: "Carro de Bomberos", successEmoji: "🧑‍🚒", successMessage: "Bomberos en posicion!" },
  { dragEmoji: "🧲", dropEmoji: "📡", dragName: "Medicion Electromagnetica", successEmoji: "📊", successMessage: "Niveles seguros!" },
  { dragEmoji: "🥊", dropEmoji: "😠", dragName: "Prevencion de Violencia", successEmoji: "🕊️", successMessage: "Ambiente laboral pacifico!" },
  { dragEmoji: "🧮", dropEmoji: "📊", dragName: "Estadisticas de Accidentes", successEmoji: "📉", successMessage: "Tasa de accidentes en baja!" },
  { dragEmoji: "🪪", dropEmoji: "🧑‍💼", dragName: "Credencial de Visitante", successEmoji: "🎫", successMessage: "Visitante registrado!" },
  { dragEmoji: "🧪", dropEmoji: "💧", dragName: "Analisis de Agua", successEmoji: "💎", successMessage: "Agua apta para consumo!" },
  { dragEmoji: "🎪", dropEmoji: "🏃‍♀️", dragName: "Simulacro de Evacuacion", successEmoji: "🏁", successMessage: "Evacuacion en 3 minutos!" },
  { dragEmoji: "📋", dropEmoji: "✅", dragName: "Lista de Chequeo", successEmoji: "📝", successMessage: "Checklist completado!" },
  { dragEmoji: "🌱", dropEmoji: "🏢", dragName: "Planta Purificadora", successEmoji: "🌿", successMessage: "Aire purificado!" },
  { dragEmoji: "🔐", dropEmoji: "💻", dragName: "Ciberseguridad SST", successEmoji: "🛡️", successMessage: "Datos protegidos!" },
  { dragEmoji: "🦺", dropEmoji: "👷‍♀️", dragName: "Chaleco Reflectivo", successEmoji: "🌟", successMessage: "Visibilidad nocturna OK!" },
  { dragEmoji: "🧯", dropEmoji: "🧑‍🍳", dragName: "Extintor de Cocina", successEmoji: "🍳", successMessage: "Cocina industrial segura!" },
  { dragEmoji: "🚲", dropEmoji: "⛑️", dragName: "Ciclista con Casco", successEmoji: "🚴", successMessage: "Ciclista protegido!" },
  { dragEmoji: "🏥", dropEmoji: "🚑", dragName: "Centro Medico", successEmoji: "⛑️", successMessage: "Atencion medica disponible!" },
  { dragEmoji: "🧑‍🎓", dropEmoji: "📖", dragName: "Estudiante en Practica", successEmoji: "🎓", successMessage: "Practicante capacitado!" },
  { dragEmoji: "🪫", dropEmoji: "🔦", dragName: "Recarga de Linterna", successEmoji: "💡", successMessage: "Linterna de emergencia lista!" },
  { dragEmoji: "🧑‍🦽", dropEmoji: "♿", dragName: "Accesibilidad", successEmoji: "🏢", successMessage: "Espacio inclusivo!" },
  { dragEmoji: "🫀", dropEmoji: "🏃", dragName: "Examen Cardiovascular", successEmoji: "❤️", successMessage: "Corazon saludable!" },
  { dragEmoji: "🧪", dropEmoji: "🧲", dragName: "Prueba de Materiales", successEmoji: "✅", successMessage: "Material certificado!" },
  { dragEmoji: "🛻", dropEmoji: "📦", dragName: "Carga Segura", successEmoji: "🔒", successMessage: "Carga bien asegurada!" },
  { dragEmoji: "🧑‍🌾", dropEmoji: "🌾", dragName: "Seguridad en Campo", successEmoji: "🌻", successMessage: "Trabajo rural protegido!" },
  { dragEmoji: "🏊", dropEmoji: "🛟", dragName: "Salvavidas", successEmoji: "🏖️", successMessage: "Rescate acuatico listo!" },
  { dragEmoji: "🌬️", dropEmoji: "🏭", dragName: "Extractor de Humos", successEmoji: "💨", successMessage: "Humos evacuados!" },
  { dragEmoji: "🧑‍🎤", dropEmoji: "📢", dragName: "Vocero de Emergencia", successEmoji: "🎙️", successMessage: "Comunicado emitido!" },
  { dragEmoji: "🗃️", dropEmoji: "📁", dragName: "Archivo de SST", successEmoji: "🗄️", successMessage: "20 anos archivados!" },
  { dragEmoji: "⚖️", dropEmoji: "📜", dragName: "Norma Legal SST", successEmoji: "🏛️", successMessage: "Cumplimiento legal OK!" },
  { dragEmoji: "🛞", dropEmoji: "🔧", dragName: "Rotacion de Llantas", successEmoji: "🚗", successMessage: "Llantas en perfecto estado!" },
  { dragEmoji: "🧪", dropEmoji: "🫁", dragName: "Espirometria", successEmoji: "💨", successMessage: "Funcion pulmonar normal!" },
  { dragEmoji: "🏗️", dropEmoji: "📐", dragName: "Plano de Obra", successEmoji: "🏢", successMessage: "Obra con permisos!" },
  { dragEmoji: "🧊", dropEmoji: "🥤", dragName: "Hidratacion en Calor", successEmoji: "💧", successMessage: "Trabajador hidratado!" },
  { dragEmoji: "🔦", dropEmoji: "🏭", dragName: "Inspeccion Nocturna", successEmoji: "🌙", successMessage: "Turno nocturno revisado!" },
  { dragEmoji: "🧑‍⚖️", dropEmoji: "📋", dragName: "Auditoria Interna", successEmoji: "✅", successMessage: "Auditoria sin hallazgos!" },
  { dragEmoji: "🧲", dropEmoji: "🏗️", dragName: "Grua Electroiman", successEmoji: "🏋️", successMessage: "Carga izada con seguridad!" },
  { dragEmoji: "📯", dropEmoji: "🏢", dragName: "Sirena de Planta", successEmoji: "🔔", successMessage: "Sistema de alarma activo!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "🧫", dragName: "Cultivo Microbiologico", successEmoji: "🔬", successMessage: "Analisis bacteriologico OK!" },
  { dragEmoji: "🚛", dropEmoji: "🛣️", dragName: "Camion de Carga", successEmoji: "📦", successMessage: "Carga pesada asegurada!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "🎓", dragName: "Instructor de SST", successEmoji: "📚", successMessage: "Clase de SST terminada!" },
  { dragEmoji: "🪵", dropEmoji: "🪓", dragName: "Tala Segura", successEmoji: "🌲", successMessage: "Tala con protocolo!" },
  { dragEmoji: "🧲", dropEmoji: "🛗", dragName: "Revision del Ascensor", successEmoji: "✅", successMessage: "Ascensor inspeccionado!" },
  { dragEmoji: "🦷", dropEmoji: "🧑‍⚕️", dragName: "Salud Dental", successEmoji: "😁", successMessage: "Salud oral al dia!" },
  { dragEmoji: "👁️", dropEmoji: "🧑‍⚕️", dragName: "Examen Visual", successEmoji: "👓", successMessage: "Vista en perfecto estado!" },
  { dragEmoji: "🎽", dropEmoji: "🏃", dragName: "Ropa Deportiva SST", successEmoji: "🏅", successMessage: "Actividad fisica realizada!" },
  { dragEmoji: "🧯", dropEmoji: "🏫", dragName: "Extintor Escolar", successEmoji: "🧑‍🏫", successMessage: "Colegio seguro!" },
  { dragEmoji: "🏠", dropEmoji: "💻", dragName: "Teletrabajo Seguro", successEmoji: "🪑", successMessage: "Puesto en casa ergonomico!" },
  { dragEmoji: "🧑‍🍼", dropEmoji: "🏢", dragName: "Proteccion a Gestantes", successEmoji: "🤰", successMessage: "Maternidad protegida!" },
  { dragEmoji: "🚁", dropEmoji: "🏥", dragName: "Helicoptero Medico", successEmoji: "⛑️", successMessage: "Aeroevacuacion lista!" },
  { dragEmoji: "🧑‍🦯", dropEmoji: "🏢", dragName: "Ruta Accesible", successEmoji: "♿", successMessage: "Ruta inclusiva senalizada!" },
  { dragEmoji: "🔩", dropEmoji: "🏗️", dragName: "Andamio Certificado", successEmoji: "✅", successMessage: "Andamio seguro!" },
  { dragEmoji: "🧑‍💻", dropEmoji: "📊", dragName: "Dashboard SST", successEmoji: "📈", successMessage: "Panel de control activo!" },
  { dragEmoji: "🌐", dropEmoji: "📡", dragName: "IoT de Seguridad", successEmoji: "🤖", successMessage: "Sensores conectados!" },
  { dragEmoji: "🧯", dropEmoji: "🏥", dragName: "Extintor Hospitalario", successEmoji: "⛑️", successMessage: "Hospital protegido!" },
  { dragEmoji: "⛽", dropEmoji: "🔥", dragName: "Control de Combustible", successEmoji: "🛡️", successMessage: "Combustible almacenado seguro!" },
  { dragEmoji: "🧑‍🎨", dropEmoji: "🪧", dragName: "Diseno de Senaletica", successEmoji: "🎨", successMessage: "Senalizacion renovada!" },
  { dragEmoji: "🏋️‍♂️", dropEmoji: "💪", dragName: "Manejo Manual de Cargas", successEmoji: "🦾", successMessage: "Tecnica de levantamiento OK!" },
  { dragEmoji: "🔭", dropEmoji: "📊", dragName: "Observacion Preventiva", successEmoji: "👁️", successMessage: "Comportamiento seguro!" },
  { dragEmoji: "🧯", dropEmoji: "🚗", dragName: "Extintor Vehicular", successEmoji: "🚙", successMessage: "Vehiculo con extintor!" },
  { dragEmoji: "📡", dropEmoji: "🌡️", dragName: "Sensor de Temperatura", successEmoji: "🌡️", successMessage: "Temperatura monitoreada!" },
  { dragEmoji: "🧱", dropEmoji: "🚧", dragName: "Muro Cortafuegos", successEmoji: "🔥", successMessage: "Compartimentacion OK!" },
  { dragEmoji: "🦮", dropEmoji: "🏢", dragName: "Perro de Rescate", successEmoji: "🐕", successMessage: "Equipo K9 listo!" },
  { dragEmoji: "🗳️", dropEmoji: "👥", dragName: "Eleccion COPASST", successEmoji: "🗳️", successMessage: "COPASST elegido!" },
  { dragEmoji: "🎼", dropEmoji: "🧘", dragName: "Musicoterapia Laboral", successEmoji: "🎵", successMessage: "Estres laboral reducido!" },
  { dragEmoji: "🥗", dropEmoji: "🍽️", dragName: "Alimentacion Balanceada", successEmoji: "🥦", successMessage: "Nutricion laboral OK!" },
  { dragEmoji: "🚶‍♂️", dropEmoji: "🚸", dragName: "Cruce Peatonal", successEmoji: "✅", successMessage: "Peaton visible y seguro!" },
  { dragEmoji: "🧑‍🦰", dropEmoji: "😊", dragName: "Evaluacion de Clima", successEmoji: "🌤️", successMessage: "Clima laboral positivo!" },
  { dragEmoji: "🚿", dropEmoji: "🧼", dragName: "Estacion de Lavado", successEmoji: "🧴", successMessage: "Higiene de manos OK!" },
  { dragEmoji: "📺", dropEmoji: "📢", dragName: "Video de Seguridad", successEmoji: "🎬", successMessage: "Comunicacion visual efectiva!" },
  { dragEmoji: "🧯", dropEmoji: "🏠", dragName: "Extintor Residencial", successEmoji: "🏡", successMessage: "Hogar seguro!" },
  { dragEmoji: "🔗", dropEmoji: "⛓️", dragName: "Cadena de Custodia", successEmoji: "🔐", successMessage: "Evidencia preservada!" },
  { dragEmoji: "🧪", dropEmoji: "🌡️", dragName: "Termometro Industrial", successEmoji: "📊", successMessage: "Proceso termico controlado!" },
  { dragEmoji: "🛶", dropEmoji: "🌊", dragName: "Chaleco Salvavidas", successEmoji: "🦺", successMessage: "Navegacion con chaleco!" },
  { dragEmoji: "🏗️", dropEmoji: "🪝", dragName: "Grua Torre", successEmoji: "🔒", successMessage: "Izaje controlado!" },
  { dragEmoji: "🧑‍🏭", dropEmoji: "🔬", dragName: "Control de Calidad", successEmoji: "✅", successMessage: "Producto seguro!" },
  { dragEmoji: "🦷", dropEmoji: "😷", dragName: "Tapabocas Industrial", successEmoji: "🛡️", successMessage: "Vias respiratorias protegidas!" },
  { dragEmoji: "🔊", dropEmoji: "📊", dragName: "Sonometria", successEmoji: "📈", successMessage: "Nivel de ruido medido!" },
  { dragEmoji: "🧑‍🔧", dropEmoji: "🔌", dragName: "Electricista Certificado", successEmoji: "⚡", successMessage: "Trabajo electrico seguro!" },
  { dragEmoji: "🪣", dropEmoji: "🧹", dragName: "Programa 5S", successEmoji: "✨", successMessage: "5S implementadas!" },
  { dragEmoji: "🚜", dropEmoji: "⛑️", dragName: "Operador de Maquinaria", successEmoji: "🎓", successMessage: "Operador con licencia!" },
  { dragEmoji: "🗡️", dropEmoji: "🛡️", dragName: "Elemento Cortante", successEmoji: "🧤", successMessage: "Guante anticorte puesto!" },
  { dragEmoji: "🧯", dropEmoji: "🎪", dragName: "Extintor de Evento", successEmoji: "🎉", successMessage: "Evento masivo seguro!" },
  { dragEmoji: "🌳", dropEmoji: "🏢", dragName: "Zona Verde Laboral", successEmoji: "🌿", successMessage: "Espacio verde activo!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "📊", dragName: "Indicadores de Salud", successEmoji: "📈", successMessage: "Indicadores de salud OK!" },
  { dragEmoji: "🔧", dropEmoji: "🚗", dragName: "Revision Tecnicomecanica", successEmoji: "✅", successMessage: "Vehiculo con revision!" },
  { dragEmoji: "🧊", dropEmoji: "🏭", dragName: "Cuarto Frio Seguro", successEmoji: "❄️", successMessage: "Cuarto frio monitoreado!" },
  { dragEmoji: "🧑‍🦱", dropEmoji: "🧢", dragName: "Cofia Industrial", successEmoji: "👨‍🍳", successMessage: "Cabello recogido y seguro!" },
  { dragEmoji: "📋", dropEmoji: "🏢", dragName: "Permiso de Trabajo", successEmoji: "✅", successMessage: "Permiso aprobado!" },
  { dragEmoji: "🦸‍♂️", dropEmoji: "🏢", dragName: "Lider de Emergencia", successEmoji: "📢", successMessage: "Lider designado!" },
  { dragEmoji: "🧲", dropEmoji: "🧯", dragName: "Manometro del Extintor", successEmoji: "✅", successMessage: "Presion adecuada!" },
  { dragEmoji: "🩻", dropEmoji: "🧑‍⚕️", dragName: "Examen de Ingreso", successEmoji: "📋", successMessage: "Apto para trabajar!" },
  { dragEmoji: "🔐", dropEmoji: "📂", dragName: "Datos del Trabajador", successEmoji: "🛡️", successMessage: "Habeas data protegido!" },
  { dragEmoji: "🧑‍🤝‍🧑", dropEmoji: "🤝", dragName: "Trabajo en Equipo", successEmoji: "💪", successMessage: "Equipo SST unido!" },
  { dragEmoji: "🎯", dropEmoji: "📅", dragName: "Meta Anual SST", successEmoji: "🏆", successMessage: "Meta del ano alcanzada!" },
  { dragEmoji: "🌍", dropEmoji: "♻️", dragName: "ISO 14001 Ambiental", successEmoji: "🌿", successMessage: "Gestion ambiental activa!" },
  { dragEmoji: "📜", dropEmoji: "🏛️", dragName: "Resolucion 0312", successEmoji: "⚖️", successMessage: "Estandares minimos cumplidos!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "📊", dragName: "Revision por Direccion", successEmoji: "✅", successMessage: "Alta direccion comprometida!" },
  { dragEmoji: "🌐", dropEmoji: "📋", dragName: "ISO 45001", successEmoji: "🏆", successMessage: "Sistema de gestion certificado!" },
  { dragEmoji: "🔔", dropEmoji: "📱", dragName: "Alerta Temprana", successEmoji: "📳", successMessage: "Alerta recibida a tiempo!" },
  { dragEmoji: "🧯", dropEmoji: "🛢️", dragName: "Extintor Clase B", successEmoji: "🛡️", successMessage: "Liquido inflamable controlado!" },
  { dragEmoji: "🚨", dropEmoji: "🏢", dragName: "Luz Estroboscopica", successEmoji: "🔴", successMessage: "Senalizacion luminosa activa!" },
  { dragEmoji: "🧲", dropEmoji: "📏", dragName: "Luxometro", successEmoji: "💡", successMessage: "Iluminacion adecuada!" },
  { dragEmoji: "🦺", dropEmoji: "🌙", dragName: "Chaleco Nocturno", successEmoji: "🌟", successMessage: "Trabajador visible de noche!" },
  { dragEmoji: "🧪", dropEmoji: "🧴", dragName: "Hoja de Seguridad", successEmoji: "📋", successMessage: "MSDS disponible!" },
  { dragEmoji: "🏥", dropEmoji: "📋", dragName: "Profesiograma", successEmoji: "🩺", successMessage: "Profesiograma actualizado!" },
  { dragEmoji: "🔩", dropEmoji: "🔧", dragName: "Torque de Seguridad", successEmoji: "✅", successMessage: "Tornillos ajustados!" },
  { dragEmoji: "🧑‍🦽", dropEmoji: "🏢", dragName: "Rampa de Acceso", successEmoji: "♿", successMessage: "Accesibilidad garantizada!" },
  { dragEmoji: "🗂️", dropEmoji: "📊", dragName: "Matriz de Riesgos", successEmoji: "📋", successMessage: "Riesgos identificados!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "📈", dragName: "Estudio de Puesto", successEmoji: "💺", successMessage: "Puesto analizado!" },
  { dragEmoji: "🔥", dropEmoji: "🧯", dragName: "Conato de Incendio", successEmoji: "✅", successMessage: "Conato extinguido!" },
  { dragEmoji: "🛡️", dropEmoji: "🧑‍💼", dragName: "Comite de Convivencia", successEmoji: "🤝", successMessage: "Convivencia laboral OK!" },
  { dragEmoji: "📢", dropEmoji: "👷", dragName: "Orden de Servicio", successEmoji: "📋", successMessage: "Contratista informado!" },
  { dragEmoji: "🧪", dropEmoji: "🩸", dragName: "Prueba de Alcoholemia", successEmoji: "✅", successMessage: "Resultado negativo!" },
  { dragEmoji: "🎯", dropEmoji: "📋", dragName: "Plan de Mejora", successEmoji: "📈", successMessage: "Mejora continua activa!" },
  { dragEmoji: "🧑‍🎓", dropEmoji: "📜", dragName: "Curso de 50 Horas", successEmoji: "🎓", successMessage: "Curso virtual aprobado!" },
  { dragEmoji: "🔑", dropEmoji: "🏢", dragName: "Responsable del SG-SST", successEmoji: "👨‍💼", successMessage: "Responsable designado!" },
  { dragEmoji: "🗳️", dropEmoji: "👷", dragName: "Vigia de SST", successEmoji: "👁️", successMessage: "Vigia en funciones!" },
  { dragEmoji: "📊", dropEmoji: "🏥", dragName: "Tasa de Ausentismo", successEmoji: "📉", successMessage: "Ausentismo en descenso!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "📅", dragName: "Examen Periodico", successEmoji: "🩺", successMessage: "Examen periodico al dia!" },
  { dragEmoji: "🔒", dropEmoji: "📱", dragName: "App Segura SST", successEmoji: "🛡️", successMessage: "Aplicacion protegida!" },
  { dragEmoji: "🧯", dropEmoji: "🧑‍🏫", dragName: "Capacitacion Extintor", successEmoji: "🎓", successMessage: "Personal capacitado!" },
  { dragEmoji: "🌡️", dropEmoji: "🏭", dragName: "Control Termico Planta", successEmoji: "❄️", successMessage: "Temperatura optima!" },
  { dragEmoji: "📋", dropEmoji: "🧑‍⚖️", dragName: "Acta de Investigacion", successEmoji: "📝", successMessage: "Incidente investigado!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "👥", dragName: "Capacitacion Mensual", successEmoji: "📚", successMessage: "Equipo capacitado!" },
  { dragEmoji: "🛡️", dropEmoji: "🌐", dragName: "Politica de Prevencion", successEmoji: "📜", successMessage: "Politica socializada!" },
  { dragEmoji: "🏥", dropEmoji: "🧑‍🤝‍🧑", dragName: "EPS del Trabajador", successEmoji: "💚", successMessage: "Afiliacion vigente!" },
  { dragEmoji: "🧑‍🦱", dropEmoji: "🏢", dragName: "Induccion de Ingreso", successEmoji: "🎓", successMessage: "Nuevo empleado inducido!" },
  { dragEmoji: "🔄", dropEmoji: "📋", dragName: "Reinduccion Anual", successEmoji: "🔁", successMessage: "Reinduccion completada!" },
  { dragEmoji: "🏗️", dropEmoji: "📜", dragName: "Licencia de Construccion", successEmoji: "✅", successMessage: "Obra con licencia vigente!" },
  { dragEmoji: "🧯", dropEmoji: "📅", dragName: "Recarga Programada", successEmoji: "🔄", successMessage: "Recarga de extintor al dia!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "📊", dragName: "Indicador de Frecuencia", successEmoji: "📉", successMessage: "IF dentro de meta!" },
  { dragEmoji: "📋", dropEmoji: "⚖️", dragName: "Matriz Legal SST", successEmoji: "📜", successMessage: "Requisitos legales al dia!" },
  { dragEmoji: "🏆", dropEmoji: "👷", dragName: "Reconocimiento Seguro", successEmoji: "🥇", successMessage: "Trabajador del mes seguro!" },
  { dragEmoji: "🧲", dropEmoji: "🔬", dragName: "Dosimetro Personal", successEmoji: "📊", successMessage: "Exposicion dentro de limites!" },
  { dragEmoji: "🦺", dropEmoji: "🚧", dragName: "Proteccion en Via", successEmoji: "🛡️", successMessage: "Trabajador vial protegido!" },
  { dragEmoji: "📱", dropEmoji: "📊", dragName: "Reporte en Linea", successEmoji: "✅", successMessage: "Reporte digital enviado!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "💨", dragName: "Medicion de Polvo", successEmoji: "🌿", successMessage: "Material particulado OK!" },
  { dragEmoji: "🎪", dropEmoji: "🧑‍⚕️", dragName: "Feria de la Salud", successEmoji: "🏥", successMessage: "Feria de salud exitosa!" },
  { dragEmoji: "🛡️", dropEmoji: "🧑‍🦱", dragName: "ARL del Trabajador", successEmoji: "💛", successMessage: "ARL activa y vigente!" },
  { dragEmoji: "📝", dropEmoji: "🏢", dragName: "Contrato de Trabajo", successEmoji: "✍️", successMessage: "Contrato con clausula SST!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "🌐", dragName: "Gestion del Cambio", successEmoji: "🔄", successMessage: "Cambio gestionado!" },
  { dragEmoji: "📊", dropEmoji: "📅", dragName: "Indicador de Severidad", successEmoji: "📉", successMessage: "IS dentro de parametros!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "🧯", dragName: "Entrenamiento Brigada", successEmoji: "🦸", successMessage: "Brigada entrenada!" },
  { dragEmoji: "📋", dropEmoji: "🏥", dragName: "Historia Clinica Laboral", successEmoji: "📂", successMessage: "Historia clinica completa!" },
  { dragEmoji: "🔊", dropEmoji: "🏢", dragName: "Mapa de Ruido", successEmoji: "📊", successMessage: "Mapa de ruido actualizado!" },
  { dragEmoji: "🧪", dropEmoji: "📊", dragName: "Monitoreo Biologico", successEmoji: "🔬", successMessage: "Biomarcadores normales!" },
  { dragEmoji: "🏢", dropEmoji: "📋", dragName: "Concepto Sanitario", successEmoji: "✅", successMessage: "Concepto sanitario favorable!" },
  { dragEmoji: "🧑‍🔧", dropEmoji: "📅", dragName: "Mantenimiento Correctivo", successEmoji: "🔧", successMessage: "Equipo reparado!" },
  { dragEmoji: "🚗", dropEmoji: "📋", dragName: "Preoperacional Vehiculo", successEmoji: "✅", successMessage: "Vehiculo apto para operar!" },
  { dragEmoji: "🌡️", dropEmoji: "📊", dragName: "Mapa de Calor", successEmoji: "🗺️", successMessage: "Zonas criticas identificadas!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "📜", dragName: "Codigo de Etica SST", successEmoji: "⚖️", successMessage: "Etica profesional vigente!" },
  { dragEmoji: "🎯", dropEmoji: "🏢", dragName: "Objetivo Estrategico", successEmoji: "🏆", successMessage: "Objetivo alineado con SST!" },
  { dragEmoji: "🧑‍🦰", dropEmoji: "📋", dragName: "Encuesta de Satisfaccion", successEmoji: "😊", successMessage: "Trabajadores satisfechos!" },
  { dragEmoji: "📢", dropEmoji: "📱", dragName: "Comunicado Interno", successEmoji: "📨", successMessage: "Mensaje de seguridad enviado!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "🧫", dragName: "Prueba de Esterilidad", successEmoji: "✅", successMessage: "Area esteril certificada!" },
  { dragEmoji: "🏗️", dropEmoji: "🧑‍💼", dragName: "Supervisor de Obra", successEmoji: "👷", successMessage: "Supervision activa!" },
  { dragEmoji: "🧯", dropEmoji: "📋", dragName: "Inventario de Extintores", successEmoji: "📊", successMessage: "Inventario actualizado!" },
  { dragEmoji: "🦺", dropEmoji: "🧑‍🏭", dragName: "Dotacion Completa", successEmoji: "👷‍♂️", successMessage: "Dotacion entregada!" },
  { dragEmoji: "📋", dropEmoji: "🏆", dragName: "Acta de Cierre", successEmoji: "✅", successMessage: "Ciclo PHVA cerrado!" },
  { dragEmoji: "🌟", dropEmoji: "👷", dragName: "Estrella de Seguridad", successEmoji: "⭐", successMessage: "Excelencia en SST!" },
  { dragEmoji: "🧑‍🚀", dropEmoji: "🔬", dragName: "Espacio Confinado", successEmoji: "🛡️", successMessage: "Espacio confinado asegurado!" },
  { dragEmoji: "🪫", dropEmoji: "📡", dragName: "UPS de Seguridad", successEmoji: "🔋", successMessage: "UPS en funcionamiento!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "🧬", dragName: "Prueba Genetica Laboral", successEmoji: "🔬", successMessage: "Predisposicion identificada!" },
  { dragEmoji: "🔩", dropEmoji: "🏗️", dragName: "Perno de Seguridad", successEmoji: "🔧", successMessage: "Conexion estructural OK!" },
  { dragEmoji: "🧪", dropEmoji: "🏭", dragName: "Control de Emisiones", successEmoji: "🌿", successMessage: "Emisiones dentro del limite!" },
  { dragEmoji: "🚨", dropEmoji: "🚗", dragName: "Baliza Vehicular", successEmoji: "🔴", successMessage: "Vehiculo senalizado!" },
  { dragEmoji: "📡", dropEmoji: "🏢", dragName: "CCTV de Seguridad", successEmoji: "📹", successMessage: "Videovigilancia activa!" },
  { dragEmoji: "🧑‍🦲", dropEmoji: "🩺", dragName: "Examen de Retiro", successEmoji: "📋", successMessage: "Examen de egreso completo!" },
  { dragEmoji: "🪜", dropEmoji: "🧑‍🔧", dragName: "Plataforma Elevadora", successEmoji: "✅", successMessage: "Plataforma certificada!" },
  { dragEmoji: "🧤", dropEmoji: "🧪", dragName: "Guante de Nitrilo", successEmoji: "🛡️", successMessage: "Proteccion quimica activa!" },
  { dragEmoji: "📋", dropEmoji: "🚗", dragName: "Bitacora de Vehiculo", successEmoji: "📝", successMessage: "Kilometraje registrado!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "📺", dragName: "E-learning SST", successEmoji: "💻", successMessage: "Curso virtual completado!" },
  { dragEmoji: "🔔", dropEmoji: "⏰", dragName: "Recordatorio de EPP", successEmoji: "📳", successMessage: "Recordatorio configurado!" },
  { dragEmoji: "🧊", dropEmoji: "🧯", dragName: "Extintor CO2", successEmoji: "❄️", successMessage: "Extintor clase C listo!" },
  { dragEmoji: "📊", dropEmoji: "🧑‍💼", dragName: "KPI de Seguridad", successEmoji: "📈", successMessage: "KPI en zona verde!" },
  { dragEmoji: "🧯", dropEmoji: "🔌", dragName: "Extintor Clase C", successEmoji: "⚡", successMessage: "Riesgo electrico cubierto!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "🌡️", dragName: "Higiene Termica", successEmoji: "📊", successMessage: "WBGT dentro de limites!" },
  { dragEmoji: "🚲", dropEmoji: "🦺", dragName: "Biciusuario Seguro", successEmoji: "🚴‍♂️", successMessage: "Ciclista con elementos!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "💊", dragName: "Farmacia Empresarial", successEmoji: "💉", successMessage: "Medicamentos disponibles!" },
  { dragEmoji: "📋", dropEmoji: "🔥", dragName: "Plan de Emergencia", successEmoji: "📜", successMessage: "Plan de emergencia vigente!" },
  { dragEmoji: "🧑‍🏭", dropEmoji: "🧪", dragName: "Operador de Caldera", successEmoji: "🎓", successMessage: "Calderista certificado!" },
  { dragEmoji: "🛡️", dropEmoji: "☢️", dragName: "Proteccion Radiologica", successEmoji: "🧑‍🔬", successMessage: "Radiacion bajo control!" },
  { dragEmoji: "🧲", dropEmoji: "🔊", dragName: "Vibrometro", successEmoji: "📊", successMessage: "Vibracion dentro de norma!" },
  { dragEmoji: "📦", dropEmoji: "🚛", dragName: "Embalaje Seguro", successEmoji: "📋", successMessage: "Mercancia bien embalada!" },
  { dragEmoji: "🧑‍🦽", dropEmoji: "🏥", dragName: "Rehabilitacion Laboral", successEmoji: "💪", successMessage: "Trabajador en rehabilitacion!" },
  { dragEmoji: "🔩", dropEmoji: "⚙️", dragName: "Guarda de Maquina", successEmoji: "🛡️", successMessage: "Guarda de proteccion puesta!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "📝", dragName: "Acta de COPASST", successEmoji: "✅", successMessage: "Reunion del COPASST OK!" },
  { dragEmoji: "🦺", dropEmoji: "🏗️", dragName: "Linea de Vida", successEmoji: "🔗", successMessage: "Linea de vida instalada!" },
  { dragEmoji: "🧪", dropEmoji: "🧑‍⚕️", dragName: "Droga Test", successEmoji: "✅", successMessage: "Resultado limpio!" },
  { dragEmoji: "📊", dropEmoji: "⚖️", dragName: "Tasa de Mortalidad", successEmoji: "📉", successMessage: "Tasa de mortalidad cero!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "🧯", dragName: "Practica de Evacuacion", successEmoji: "🏃", successMessage: "Evacuacion en tiempo record!" },
  { dragEmoji: "🔑", dropEmoji: "🗄️", dragName: "Armario de Quimicos", successEmoji: "🔐", successMessage: "Quimicos bajo llave!" },
  { dragEmoji: "🧑‍🔧", dropEmoji: "🪜", dragName: "Inspector de Alturas", successEmoji: "👁️", successMessage: "Alturas inspeccionadas!" },
  { dragEmoji: "📱", dropEmoji: "📊", dragName: "App de Indicadores", successEmoji: "📈", successMessage: "Datos en tiempo real!" },
  { dragEmoji: "🧪", dropEmoji: "🏢", dragName: "Fumigacion Segura", successEmoji: "🌿", successMessage: "Fumigacion con protocolo!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "🫀", dragName: "RCP Basico", successEmoji: "❤️", successMessage: "Personal capacitado en RCP!" },
  { dragEmoji: "🔧", dropEmoji: "🛞", dragName: "Alineacion y Balanceo", successEmoji: "🚗", successMessage: "Vehiculo alineado!" },
  { dragEmoji: "🧑‍💻", dropEmoji: "🔐", dragName: "Backup de Datos SST", successEmoji: "💾", successMessage: "Respaldo de datos seguro!" },
  { dragEmoji: "📋", dropEmoji: "🧑‍🏭", dragName: "Matriz de EPP", successEmoji: "📊", successMessage: "EPP por cargo definido!" },
  { dragEmoji: "🧯", dropEmoji: "🏟️", dragName: "Extintor de Estadio", successEmoji: "🏆", successMessage: "Evento deportivo seguro!" },
  { dragEmoji: "🧑‍🎓", dropEmoji: "📋", dragName: "Curso de 20 Horas", successEmoji: "🎓", successMessage: "Curso basico aprobado!" },
  { dragEmoji: "🌡️", dropEmoji: "🧑‍🦱", dragName: "Fiebre Detectada", successEmoji: "🏥", successMessage: "Trabajador remitido a EPS!" },
  { dragEmoji: "📢", dropEmoji: "🏢", dragName: "Megafono de Emergencia", successEmoji: "📣", successMessage: "Comunicacion de emergencia OK!" },
  { dragEmoji: "🧲", dropEmoji: "🧪", dragName: "Ph-metro Industrial", successEmoji: "📊", successMessage: "pH dentro de parametros!" },
  { dragEmoji: "🚗", dropEmoji: "📱", dragName: "GPS Vehicular", successEmoji: "📡", successMessage: "Vehiculo rastreado!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "🌬️", dragName: "Anemometro", successEmoji: "💨", successMessage: "Velocidad del viento OK!" },
  { dragEmoji: "🏗️", dropEmoji: "🧱", dragName: "Demolicion Controlada", successEmoji: "🛡️", successMessage: "Demolicion con protocolo!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "👁️", dragName: "Optometria Ocupacional", successEmoji: "👓", successMessage: "Lentes prescritos!" },
  { dragEmoji: "🔩", dropEmoji: "🏭", dragName: "Valvula de Seguridad", successEmoji: "✅", successMessage: "Presion regulada!" },
  { dragEmoji: "📋", dropEmoji: "🧑‍⚕️", dragName: "Protocolo de Bioseguridad", successEmoji: "🧫", successMessage: "Protocolo implementado!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "🔥", dragName: "Charla de Incendios", successEmoji: "🧯", successMessage: "Personal preparado!" },
  { dragEmoji: "🛡️", dropEmoji: "📊", dragName: "Plan Estrategico SST", successEmoji: "🎯", successMessage: "Estrategia SST definida!" },
  { dragEmoji: "🧲", dropEmoji: "💧", dragName: "Medicion de Humedad", successEmoji: "📊", successMessage: "Humedad relativa optima!" },
  { dragEmoji: "🦺", dropEmoji: "🧑‍🔧", dragName: "Overol de Seguridad", successEmoji: "👷", successMessage: "Overol limpio y completo!" },
  { dragEmoji: "📡", dropEmoji: "🏭", dragName: "Sensor de Gas", successEmoji: "🔔", successMessage: "Detector de gas activo!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "👥", dragName: "Comite Paritario", successEmoji: "🤝", successMessage: "COPASST en sesion!" },
  { dragEmoji: "🔦", dropEmoji: "🧑‍🚒", dragName: "Lampara Minera", successEmoji: "💡", successMessage: "Iluminacion de mina OK!" },
  { dragEmoji: "🧪", dropEmoji: "📋", dragName: "Ficha Tecnica", successEmoji: "📄", successMessage: "Ficha tecnica disponible!" },
  { dragEmoji: "🏥", dropEmoji: "🧑‍🦽", dragName: "Reincorporacion Laboral", successEmoji: "💪", successMessage: "Trabajador reincorporado!" },
  { dragEmoji: "📊", dropEmoji: "🏢", dragName: "Tasa de Incidencia", successEmoji: "📉", successMessage: "Incidencia en descenso!" },
  { dragEmoji: "🧑‍🎓", dropEmoji: "🌐", dragName: "Diploma SST Virtual", successEmoji: "🎓", successMessage: "Diploma descargado!" },
  { dragEmoji: "🔧", dropEmoji: "📅", dragName: "Mantenimiento Preventivo", successEmoji: "🛠️", successMessage: "Equipo en optimas condiciones!" },
  { dragEmoji: "🧯", dropEmoji: "🧪", dragName: "Extintor Clase D", successEmoji: "🔥", successMessage: "Metal combustible controlado!" },
  { dragEmoji: "🧑‍💻", dropEmoji: "📋", dragName: "Software de SST", successEmoji: "💻", successMessage: "Sistema digital operativo!" },
  { dragEmoji: "📋", dropEmoji: "🧑‍🤝‍🧑", dragName: "Registro de Asistencia", successEmoji: "✅", successMessage: "Asistencia verificada!" },
  { dragEmoji: "🏗️", dropEmoji: "📏", dragName: "Topografia de Obra", successEmoji: "🗺️", successMessage: "Terreno nivelado y seguro!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "🧪", dragName: "Hemograma Laboral", successEmoji: "🩸", successMessage: "Resultados de laboratorio OK!" },
  { dragEmoji: "🔐", dropEmoji: "🏢", dragName: "Control de Acceso", successEmoji: "🪪", successMessage: "Solo personal autorizado!" },
  { dragEmoji: "📢", dropEmoji: "🌐", dragName: "Boletin de Seguridad", successEmoji: "📰", successMessage: "Boletin distribuido!" },
  { dragEmoji: "🧲", dropEmoji: "🔬", dragName: "Microscopio de SST", successEmoji: "🔍", successMessage: "Fibras analizadas!" },
  { dragEmoji: "🦺", dropEmoji: "🚢", dragName: "Chaleco Maritimo", successEmoji: "🛟", successMessage: "Tripulacion con chaleco!" },
  { dragEmoji: "📋", dropEmoji: "🏥", dragName: "Formato FURAT", successEmoji: "📝", successMessage: "FURAT diligenciado!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "🧑‍🦱", dragName: "Mentoria en SST", successEmoji: "🤝", successMessage: "Nuevo lider formado!" },
  { dragEmoji: "🎯", dropEmoji: "📊", dragName: "Accion Correctiva", successEmoji: "✅", successMessage: "No conformidad cerrada!" },
  { dragEmoji: "🎆", dropEmoji: "🏢", dragName: "Cierre Anual SST", successEmoji: "🎊", successMessage: "Ano sin accidentes fatales!" },
];
