export const FRASES_MOTIVACIONALES: string[] = [
  "Tu bienestar es la prioridad. Hoy es un gran dia para cuidarte.",
  "Cada jornada segura es un regalo para tu familia.",
  "Tu salud no tiene precio. Protegela siempre.",
  "Detras de cada norma hay una vida que vale la pena proteger.",
  "Hoy alguien te espera en casa. Trabaja seguro por ellos.",
  "Cuidar tu vida es el acto de valentia mas grande.",
  "Un trabajador seguro es un trabajador feliz.",
  "Tu familia es tu mayor motivacion. Regresa sano cada dia.",
  "La prevencion no es un gasto, es una inversion en tu vida.",
  "Cada dia es una oportunidad para hacer las cosas bien y volver a casa.",
  "Tu vida vale mas que cualquier meta de produccion.",
  "Proteger tu salud es proteger tus suenos.",
  "Nadie puede reemplazarte en tu hogar. Cuidate.",
  "La seguridad empieza contigo. Tu ejemplo inspira a otros.",
  "Hoy tienes la oportunidad de hacer la diferencia. Aprovechala.",
  "Trabajar seguro no es una opcion, es un compromiso con la vida.",
  "Tu sonrisa al volver a casa es la mejor recompensa del dia.",
  "Cada accion segura es un paso hacia un futuro mejor.",
  "Tu bienestar importa. No dejes que la rutina te haga olvidarlo.",
  "La mejor herramienta de trabajo es tu conciencia de seguridad.",
  "Eres insustituible para quienes te aman. Cuidate hoy.",
  "Un minuto de prevencion puede evitar toda una vida de dolor.",
  "Tu salud mental tambien cuenta. Respira, enfoca y avanza.",
  "Hoy es un buen dia para recordar por que haces lo que haces.",
  "Cada amanecer es una nueva oportunidad de proteger lo que amas.",
  "La seguridad no es solo un protocolo, es un acto de amor propio.",
  "Tu cuerpo es tu vehiculo de vida. Mantenlo en las mejores condiciones.",
  "Trabaja con la mente en tu familia y el corazon en la seguridad.",
  "No hay trabajo tan urgente que no pueda hacerse de manera segura.",
  "Tu compromiso con la seguridad protege a todo tu equipo.",
  "Volver a casa sano es el logro mas importante del dia.",
  "La prevencion es el mejor regalo que le puedes dar a tu familia.",
  "Eres mas fuerte cuando cuidas tu salud. No te descuides.",
  "Cada norma de seguridad fue escrita pensando en alguien como tu.",
  "Tu vida tiene un proposito. Protegela con cada decision.",
  "El trabajo seguro construye familias felices.",
  "Hoy es el dia perfecto para priorizar tu bienestar.",
  "La seguridad no tiene horario. Cuidate las 24 horas.",
  "Tu experiencia salva vidas. Comparte lo que sabes.",
  "Un equipo seguro es un equipo que triunfa junto.",
  "Piensa antes de actuar. Esos segundos pueden salvar tu vida.",
  "Tu salud es tu mayor riqueza. Invierte en ella cada dia.",
  "Detras de cada casco hay un padre, una madre, un hijo. Protegete.",
  "La mejor productividad nace de un ambiente seguro y humano.",
  "No te acostumbres al riesgo. La confianza excesiva es peligrosa.",
  "Tu presencia en casa cada noche es tu mayor exito profesional.",
  "Cuida tu espalda, tus manos, tus ojos. Son tu patrimonio.",
  "La seguridad es un habito que se construye dia a dia.",
  "Eres valioso. Tu empresa te necesita sano y motivado.",
  "Hoy alguien depende de que regreses bien. No le falles.",
  "El trabajo dignifica, pero solo si se hace de manera segura.",
  "Tu actitud positiva es contagiosa. Se el ejemplo de seguridad.",
  "Cada dia sin accidentes es una victoria de todo el equipo.",
  "No ignores las senales de tu cuerpo. Descansa cuando lo necesites.",
  "La prevencion es responsabilidad de todos, empezando por ti.",
  "Tu compromiso de hoy es el bienestar de manana.",
  "La vida te da una sola oportunidad. No la arriesgues por prisa.",
  "Trabajar con seguridad es trabajar con inteligencia.",
  "Tu familia confio en que hoy regresaras sano. Honra esa confianza.",
  "La seguridad no tiene atajos. Sigue siempre el procedimiento.",
  "Eres el recurso mas valioso de tu organizacion. Cuidate.",
  "Hoy puedes ser el heroe silencioso que previene un accidente.",
  "Tu bienestar fisico y emocional son igual de importantes.",
  "Cada elemento de proteccion es un abrazo de seguridad.",
  "No dejes para manana lo que puedes prevenir hoy.",
  "Tu energia positiva transforma tu entorno de trabajo.",
  "La seguridad se practica, no se improvisa.",
  "Recuerda: al final del dia, lo mas importante eres tu.",
  "Un ambiente de trabajo saludable es un derecho, no un privilegio.",
  "Tu liderazgo en seguridad inspira a tus companeros.",
  "Cada paso seguro te acerca mas a tus metas personales.",
  "No hay prisa que justifique arriesgar tu integridad.",
  "Tu salud es la base sobre la cual construyes todo lo demas.",
  "Hoy elige ser consciente. Cada decision cuenta.",
  "La cultura de seguridad se construye con personas como tu.",
  "Tu voz importa. Si ves algo inseguro, reportalo.",
  "El cuidado propio no es egoismo, es responsabilidad.",
  "Manana te agradeceras por haber sido prudente hoy.",
  "Tu equipo de proteccion es tu segunda piel. Usalo siempre.",
  "La seguridad une equipos y fortalece companias.",
  "Eres el protagonista de tu propia historia. Escribela con seguridad.",
  "Cada capacitacion es una herramienta mas para proteger tu vida.",
  "Tu compromiso con el autocuidado es admirable. Sigue asi.",
  "Hoy y siempre: primero tu seguridad, despues todo lo demas.",
  "La prevencion es la forma mas inteligente de trabajar.",
  "Tu familia merece verte sonreir cada tarde al regresar.",
  "El respeto por la vida empieza por el respeto a ti mismo.",
  "Cada jornada es una oportunidad para demostrar que la seguridad es posible.",
  "Tu bienestar emocional tambien necesita atencion. No lo olvides.",
  "Un dia mas seguro es un dia mas de vida plena.",
  "Tu determinacion por trabajar seguro marca la diferencia.",
  "La seguridad no es aburrida. Es la forma mas sabia de vivir.",
  "Protege tu presente para disfrutar tu futuro.",
  "Cada companero es parte de tu familia laboral. Cuidate y cuidalo.",
  "Tu disciplina en seguridad es tu mayor fortaleza.",
  "Hoy comienza un nuevo dia. Hazlo seguro, hazlo memorable.",
  "La vida es bella. Protegela con cada accion que tomes.",
  "Tu salud es el motor que impulsa todos tus suenos.",
  "No subestimes los riesgos. La prudencia siempre gana.",
  "Eres mas que un empleado. Eres una persona valiosa e irreemplazable.",
  "El mejor plan de seguridad eres tu, actuando con conciencia.",
  "Hoy es un regalo. Cuidalo como merece.",
  "Tu ejemplo de seguridad deja huella en quienes te rodean.",
  "La prevencion es el lenguaje del amor en el trabajo.",
  "Cada dia seguro es un triunfo silencioso que merece celebrarse.",
  "Tu tranquilidad al trabajar seguro se refleja en tu hogar.",
  "No hay tarea imposible cuando se hace con seguridad y corazon.",
  "Tu bienestar es la base de un equipo exitoso.",
  "La seguridad no descansa. Tu tampoco dejes de practicarla.",
  "Eres la razon por la que alguien sonrie al verte llegar a casa.",
  "Hoy elige la seguridad. Siempre vale la pena.",
  "Tu vida tiene un valor infinito. Protegela en cada momento.",
  "Trabajar seguro es el mejor legado que puedes dejar.",
  "La prevencion empieza en la mente y se refleja en las acciones.",
  "Tu fortaleza esta en saber cuando pedir ayuda. No dudes en hacerlo.",
  "Cada dia es una batalla ganada cuando regresas sano a tu hogar.",
  "Tu compromiso con la vida es lo que te hace extraordinario.",
  "No hay exito profesional que valga mas que tu salud.",
  "Hoy respira profundo y recuerda: tu eres lo mas importante.",
  "La seguridad es un regalo que te das a ti mismo cada dia.",
  "Tu presencia hace la diferencia. Cuidate para seguir estando.",
  "Cada momento de precaucion es un momento de sabiduria.",
  "Tu corazon late por una razon. Protege esa razon cada dia.",
  "El bienestar no se negocia. Es tu derecho fundamental.",
  "Hoy sal a trabajar con la certeza de que volveras bien.",
  "Tu sonrisa es la prueba de que la seguridad funciona.",
  "La prevencion es el camino. Tu bienestar es el destino.",
  "Eres fuerte, eres valioso, eres necesario. Cuidate siempre.",
  "Cada dia que trabajas seguro, gana tu familia entera.",
  "Tu salud integral es la mejor poliza de vida.",
  "No dejes que el cansancio nuble tu juicio. Descansa y sigue.",
  "Tu proposito va mas alla del trabajo. Vive para cumplirlo.",
  "La seguridad es la expresion mas pura del respeto por la vida.",
  "Hoy y todos los dias: tu primero, tu seguridad primero.",
  "Tu determinacion inspira. Tu prudencia protege. Tu ejemplo transforma.",
  "Cada fin de jornada seguro es el comienzo de una noche tranquila.",
  "Tu eres la persona mas importante de tu vida. Actua en consecuencia.",
  "La prevencion no tiene precio. Tu vida tampoco.",
  "Hoy celebra estar aqui. Manana agradeceras haberte cuidado.",
  "Tu bienestar es el pilar de todo lo que construyes.",
  "Eres el guardian de tu propia vida. Ejerce ese poder con responsabilidad.",
  "Cada accion preventiva es una declaracion de amor a la vida.",
  "Tu salud, tu familia, tu futuro. Todo depende de que te cuides hoy.",
  "La seguridad es el idioma universal del amor propio.",
  "Hoy tienes todo para ser tu mejor version. Empieza con seguridad.",
  "Tu legado mas grande sera el ejemplo de cuidado que dejes.",
  "No hay trabajo perfecto, pero si formas perfectas de protegerte.",
  "Tu presencia ilumina tu hogar. Regresa siempre a iluminarlo.",
  "La vida te necesita completo. Cuidate de pies a cabeza.",
  "Eres mas que suficiente. Y mereces volver sano cada dia.",
  "Hoy es el dia ideal para renovar tu compromiso con la vida.",
  "Tu seguridad es la semilla de la felicidad de tu familia.",
  "Cada proteccion que usas es un acto de sabiduria.",
  "Tu valor como ser humano esta por encima de cualquier indicador.",
  "La prevencion es el regalo mas generoso que puedes darte.",
  "Hoy trabaja con pasion, pero sobre todo, con seguridad.",
  "Tu vida es una obra maestra en construccion. No permitas que se detenga.",
  "El autocuidado es la forma mas honesta de quererte.",
  "Cada manana tienes una cita con la vida. No faltes.",
  "Tu eres el motor de tu familia. Mantenlo en optimas condiciones.",
  "La seguridad no limita, libera. Te libera de preocupaciones innecesarias.",
  "Hoy eres mas sabio que ayer. Usa esa sabiduria para protegerte.",
  "Tu compromiso con la seguridad es tu carta de presentacion.",
  "Eres el heroe cotidiano de quienes te aman. No lo olvides.",
  "Cada dia sin incidentes es un dia de victoria para todos.",
  "Tu bienestar no es negociable. Defiendelo siempre.",
  "La seguridad se vive, se respira, se practica. Hazla parte de ti.",
  "Hoy empieza tu jornada con la mejor actitud y la mayor precaucion.",
  "Tu vida merece ser vivida plenamente. Cuida cada paso que das.",
  "El amor propio se demuestra con acciones seguras.",
  "Eres irremplazable. Punto. Cuidate como tal.",
  "Cada medida de seguridad es un escalon hacia una vida plena.",
  "Tu tranquilidad al trabajar se transmite a todo tu entorno.",
  "Hoy y siempre: mereces volver a casa con una sonrisa.",
  "La prevencion es el arte de amar la vida en cada detalle.",
  "Tu fuerza no esta solo en tus brazos, esta en tu capacidad de protegerte.",
  "Cada dia es un lienzo en blanco. Pintalo con seguridad y alegria.",
  "Tu salud es sagrada. Trátala con el respeto que merece.",
  "Eres parte de algo mas grande. Tu seguridad importa para todos.",
  "La vida te sonrie cuando tu la cuidas. Sonriele de vuelta.",
  "Hoy decide ser la mejor version de ti: segura, consciente y valiente.",
  "Tu camino apenas comienza. Asegurate de recorrerlo con proteccion.",
  "Cada respiro es un recordatorio de lo valiosa que es tu vida.",
  "Tu familia te necesita entero. No les falles.",
  "La seguridad es la base de la dignidad en el trabajo.",
  "Hoy celebra tu vida cuidandola. Es el mejor homenaje que puedes hacerte.",
  "Tu eres el proyecto mas importante de tu vida. Invierte en tu seguridad.",
  "Cada decision segura es un paso firme hacia tus suenos.",
  "Tu bienestar construye un mundo mejor para quienes te rodean.",
  "No hay manana sin el cuidado de hoy. Protegete ahora.",
  "Eres luz para muchas personas. No permitas que esa luz se apague.",
  "La seguridad no es una carga, es el camino mas liviano.",
  "Hoy agradece por estar aqui y comprometete a seguir estando.",
  "Tu vida es el regalo mas grande que has recibido. Cuidalo.",
  "Cada jornada segura suma anos de felicidad a tu vida.",
  "Tu determinacion por llegar sano a casa es tu mayor victoria.",
  "La prevencion es inteligencia aplicada a la vida diaria.",
  "Eres extraordinario. Y mereces un lugar de trabajo que te proteja.",
  "Hoy es tu dia. Vivelo con seguridad, vivelo con proposito.",
  "Tu corazon late por quienes te esperan. Regresa siempre por ellos.",
  "La seguridad es silenciosa, pero su ausencia es ensordecedora.",
  "Cada accion consciente es un tributo a la vida.",
  "Tu eres la razon suficiente para trabajar seguro. Siempre.",
  "Hoy tu mejor decision sera cuidarte. Las demas vendran despues.",
  "La vida es corta para desperdiciarla en riesgos innecesarios.",
  "Tu presencia en el mundo importa. Protegela con todo tu ser.",
  "Cada amanecer te dice: vale la pena cuidarse un dia mas.",
  "Tu seguridad es la promesa mas bonita que le haces a tu familia.",
  "Hoy seras mas fuerte porque elegiras ser mas prudente.",
  "La prevencion es la poesia del trabajo bien hecho.",
  "Tu bienestar ilumina todo lo que tocas. No dejes que se apague.",
  "Eres el milagro de cada dia. Cuidate como el tesoro que eres.",
  "Cada paso seguro es un paso hacia la plenitud.",
  "Hoy el mundo te necesita. Presentate completo, seguro y feliz.",
  "Tu vida es la prueba de que vale la pena prevenir.",
  "La seguridad es el abrazo invisible que te protege cada dia.",
  "Eres suficiente, eres valioso, eres amado. Cuidate por ellos y por ti.",
  "Hoy cierra los ojos un segundo y recuerda por quien trabajas. Ahora, hazlo seguro.",
  "Tu compromiso con la vida es la mejor herencia que puedes dejar.",
  "Cada momento de cuidado es un momento de grandeza.",
  "La prevencion es la forma mas elegante de amar la vida.",
  "Hoy tu familia necesita que regreses. Y tu mereces regresar.",
  "Tu eres mas importante que cualquier plazo, meta o indicador.",
  "La seguridad es el fundamento de una vida con proposito.",
  "Cada dia que vuelves sano a casa, gana el amor.",
  "Hoy se fuerte en la prevencion y suave con tu bienestar.",
  "Tu vida es irrepetible. Protegela como la joya que es.",
  "Eres el centro del universo de alguien. No dejes de brillar.",
  "La seguridad es el puente entre tus suenos y tu realidad.",
  "Hoy recuerda: nadie puede cuidarte mejor que tu mismo.",
  "Tu existencia tiene un impacto que ni imaginas. Sigue aqui.",
  "Cada medida preventiva es una carta de amor a tu futuro.",
  "Hoy y siempre: tu eres la razon mas importante para trabajar seguro.",
  "La vida te espera afuera. Asegurate de llegar a vivirla.",
  "Tu seguridad hoy es la paz de tu familia esta noche.",
  "Eres el arquitecto de tu propio cuidado. Construye con sabiduria.",
  "Cada dia seguro es un capitulo feliz en tu historia de vida.",
  "Hoy abraza la prevencion como abrazas a quienes amas.",
  "Tu salud es el cimiento de todos tus logros. No lo descuides.",
  "La seguridad es la melodia que hace armoniosa tu jornada.",
  "Eres parte de una cadena de cuidado. Tu eslabon es vital.",
  "Hoy vive con intencion, trabaja con prevencion.",
  "Tu vida es una bendicion para muchos. Conservala con cariño.",
  "Cada proteccion es una promesa cumplida contigo mismo.",
  "La prevencion es el lenguaje silencioso del amor por la vida.",
  "Hoy comienza con gratitud y termina con seguridad.",
  "Tu eres irreemplazable. Recuerdalo en cada decision que tomes.",
  "La seguridad no se hereda, se practica. Hoy es tu oportunidad.",
  "Cada instante de cuidado vale una vida entera de felicidad.",
  "Hoy tu mejor version se presenta segura, consciente y agradecida.",
  "Tu bienestar es la estrella que guia a tu familia. Brillla siempre.",
  "La vida es el viaje mas hermoso. Recorrelo con seguridad.",
  "Eres el tesoro mas valioso de tu hogar. Protegete sin excusas.",
  "Hoy y cada dia: la seguridad es tu mejor compania.",
  "Tu presencia en el mundo cambia vidas. Asegura la tuya primero.",
  "Cada acto de prevencion es un acto de fe en el futuro.",
  "La seguridad es la raiz de la que crece todo lo bueno.",
  "Hoy eres mas fuerte, mas sabio y mas comprometido con tu vida.",
  "Tu seguridad es la llave que abre la puerta de un manana mejor.",
  "Eres la persona que alguien necesita ver llegar cada tarde.",
  "La prevencion es la forma mas hermosa de decir: me importo.",
  "Hoy cuida tu cuerpo, tu mente y tu espiritu. Los tres te necesitan.",
  "Tu vida es un regalo que merece ser protegido todos los dias.",
  "Cada jornada segura es una victoria silenciosa del amor.",
  "Eres suficiente. Eres necesario. Eres amado. Trabaja seguro.",
];

export function getFraseDelDia(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return FRASES_MOTIVACIONALES[dayOfYear % FRASES_MOTIVACIONALES.length];
}
