export const FRASES_MOTIVACIONALES: string[] = [
  "Tu bienestar es la prioridad. Hoy es un gran día para cuidarte.",
  "Cada jornada segura es un regalo para tu familia.",
  "Tu salud no tiene precio. Protégela siempre.",
  "Detrás de cada norma hay una vida que vale la pena proteger.",
  "Hoy alguien te espera en casa. Trabaja seguro por ellos.",
  "Cuidar tu vida es el acto de valentía más grande.",
  "Un trabajador seguro es un trabajador feliz.",
  "Tu familia es tu mayor motivación. Regresa sano cada día.",
  "La prevención no es un gasto, es una inversión en tu vida.",
  "Cada día es una oportunidad para hacer las cosas bien y volver a casa.",
  "Tu vida vale más que cualquier meta de producción.",
  "Proteger tu salud es proteger tus sueños.",
  "Nadie puede reemplazarte en tu hogar. Cuídate.",
  "La seguridad empieza contigo. Tu ejemplo inspira a otros.",
  "Hoy tienes la oportunidad de hacer la diferencia. Aprovéchala.",
  "Trabajar seguro no es una opción, es un compromiso con la vida.",
  "Tu sonrisa al volver a casa es la mejor recompensa del día.",
  "Cada acción segura es un paso hacia un futuro mejor.",
  "Tu bienestar importa. No dejes que la rutina te haga olvidarlo.",
  "La mejor herramienta de trabajo es tu conciencia de seguridad.",
  "Eres insustituible para quienes te aman. Cuídate hoy.",
  "Un minuto de prevención puede evitar toda una vida de dolor.",
  "Tu salud mental también cuenta. Respira, enfoca y avanza.",
  "Hoy es un buen día para recordar por qué haces lo que haces.",
  "Cada amanecer es una nueva oportunidad de proteger lo que amas.",
  "La seguridad no es solo un protocolo, es un acto de amor propio.",
  "Tu cuerpo es tu vehículo de vida. Mantenlo en las mejores condiciones.",
  "Trabaja con la mente en tu familia y el corazón en la seguridad.",
  "No hay trabajo tan urgente que no pueda hacerse de manera segura.",
  "Tu compromiso con la seguridad protege a todo tu equipo.",
  "Volver a casa sano es el logro más importante del día.",
  "La prevención es el mejor regalo que le puedes dar a tu familia.",
  "Eres más fuerte cuando cuidas tu salud. No te descuides.",
  "Cada norma de seguridad fue escrita pensando en alguien como tú.",
  "Tu vida tiene un propósito. Protégela con cada decisión.",
  "El trabajo seguro construye familias felices.",
  "Hoy es el día perfecto para priorizar tu bienestar.",
  "La seguridad no tiene horario. Cuídate las 24 horas.",
  "Tu experiencia salva vidas. Comparte lo que sabes.",
  "Un equipo seguro es un equipo que triunfa junto.",
  "Piensa antes de actuar. Esos segundos pueden salvar tu vida.",
  "Tu salud es tu mayor riqueza. Invierte en ella cada día.",
  "Detrás de cada casco hay un padre, una madre, un hijo. Protégete.",
  "La mejor productividad nace de un ambiente seguro y humano.",
  "No te acostumbres al riesgo. La confianza excesiva es peligrosa.",
  "Tu presencia en casa cada noche es tu mayor éxito profesional.",
  "Cuida tu espalda, tus manos, tus ojos. Son tu patrimonio.",
  "La seguridad es un hábito que se construye día a día.",
  "Eres valioso. Tu empresa te necesita sano y motivado.",
  "Hoy alguien depende de que regreses bien. No le falles.",
  "El trabajo dignifica, pero solo si se hace de manera segura.",
  "Tu actitud positiva es contagiosa. Sé el ejemplo de seguridad.",
  "Cada día sin accidentes es una victoria de todo el equipo.",
  "No ignores las señales de tu cuerpo. Descansa cuando lo necesites.",
  "La prevención es responsabilidad de todos, empezando por ti.",
  "Tu compromiso de hoy es el bienestar de mañana.",
  "La vida te da una sola oportunidad. No la arriesgues por prisa.",
  "Trabajar con seguridad es trabajar con inteligencia.",
  "Tu familia confió en que hoy regresarás sano. Honra esa confianza.",
  "La seguridad no tiene atajos. Sigue siempre el procedimiento.",
  "Eres el recurso más valioso de tu organización. Cuídate.",
  "Hoy puedes ser el héroe silencioso que previene un accidente.",
  "Tu bienestar físico y emocional son igual de importantes.",
  "Cada elemento de protección es un abrazo de seguridad.",
  "No dejes para mañana lo que puedes prevenir hoy.",
  "Tu energía positiva transforma tu entorno de trabajo.",
  "La seguridad se practica, no se improvisa.",
  "Recuerda: al final del día, lo más importante eres tú.",
  "Un ambiente de trabajo saludable es un derecho, no un privilegio.",
  "Tu liderazgo en seguridad inspira a tus compañeros.",
  "Cada paso seguro te acerca más a tus metas personales.",
  "No hay prisa que justifique arriesgar tu integridad.",
  "Tu salud es la base sobre la cual construyes todo lo demás.",
  "Hoy elige ser consciente. Cada decisión cuenta.",
  "La cultura de seguridad se construye con personas como tú.",
  "Tu voz importa. Si ves algo inseguro, repórtalo.",
  "El cuidado propio no es egoísmo, es responsabilidad.",
  "Mañana te agradecerás por haber sido prudente hoy.",
  "Tu equipo de protección es tu segunda piel. Úsalo siempre.",
  "La seguridad une equipos y fortalece compañías.",
  "Eres el protagonista de tu propia historia. Escríbela con seguridad.",
  "Cada capacitación es una herramienta más para proteger tu vida.",
  "Tu compromiso con el autocuidado es admirable. Sigue así.",
  "Hoy y siempre: primero tu seguridad, después todo lo demás.",
  "La prevención es la forma más inteligente de trabajar.",
  "Tu familia merece verte sonreír cada tarde al regresar.",
  "El respeto por la vida empieza por el respeto a ti mismo.",
  "Cada jornada es una oportunidad para demostrar que la seguridad es posible.",
  "Tu bienestar emocional también necesita atención. No lo olvides.",
  "Un día más seguro es un día más de vida plena.",
  "Tu determinación por trabajar seguro marca la diferencia.",
  "La seguridad no es aburrida. Es la forma más sabia de vivir.",
  "Protege tu presente para disfrutar tu futuro.",
  "Cada compañero es parte de tu familia laboral. Cuídate y cuídalo.",
  "Tu disciplina en seguridad es tu mayor fortaleza.",
  "Hoy comienza un nuevo día. Hazlo seguro, hazlo memorable.",
  "La vida es bella. Protégela con cada acción que tomes.",
  "Tu salud es el motor que impulsa todos tus sueños.",
  "No subestimes los riesgos. La prudencia siempre gana.",
  "Eres más que un empleado. Eres una persona valiosa e irreemplazable.",
  "El mejor plan de seguridad eres tú, actuando con conciencia.",
  "Hoy es un regalo. Cuídalo como merece.",
  "Tu ejemplo de seguridad deja huella en quienes te rodean.",
  "La prevención es el lenguaje del amor en el trabajo.",
  "Cada día seguro es un triunfo silencioso que merece celebrarse.",
  "Tu tranquilidad al trabajar seguro se refleja en tu hogar.",
  "No hay tarea imposible cuando se hace con seguridad y corazón.",
  "Tu bienestar es la base de un equipo exitoso.",
  "La seguridad no descansa. Tú tampoco dejes de practicarla.",
  "Eres la razón por la que alguien sonríe al verte llegar a casa.",
  "Hoy elige la seguridad. Siempre vale la pena.",
  "Tu vida tiene un valor infinito. Protégela en cada momento.",
  "Trabajar seguro es el mejor legado que puedes dejar.",
  "La prevención empieza en la mente y se refleja en las acciones.",
  "Tu fortaleza está en saber cuándo pedir ayuda. No dudes en hacerlo.",
  "Cada día es una batalla ganada cuando regresas sano a tu hogar.",
  "Tu compromiso con la vida es lo que te hace extraordinario.",
  "No hay éxito profesional que valga más que tu salud.",
  "Hoy respira profundo y recuerda: tú eres lo más importante.",
  "La seguridad es un regalo que te das a ti mismo cada día.",
  "Tu presencia hace la diferencia. Cuídate para seguir estando.",
  "Cada momento de precaución es un momento de sabiduría.",
  "Tu corazón late por una razón. Protege esa razón cada día.",
  "El bienestar no se negocia. Es tu derecho fundamental.",
  "Hoy sal a trabajar con la certeza de que volverás bien.",
  "Tu sonrisa es la prueba de que la seguridad funciona.",
  "La prevención es el camino. Tu bienestar es el destino.",
  "Eres fuerte, eres valioso, eres necesario. Cuídate siempre.",
  "Cada día que trabajas seguro, gana tu familia entera.",
  "Tu salud integral es la mejor póliza de vida.",
  "No dejes que el cansancio nuble tu juicio. Descansa y sigue.",
  "Tu propósito va más allá del trabajo. Vive para cumplirlo.",
  "La seguridad es la expresión más pura del respeto por la vida.",
  "Hoy y todos los días: tú primero, tu seguridad primero.",
  "Tu determinación inspira. Tu prudencia protege. Tu ejemplo transforma.",
  "Cada fin de jornada seguro es el comienzo de una noche tranquila.",
  "Tú eres la persona más importante de tu vida. Actúa en consecuencia.",
  "La prevención no tiene precio. Tu vida tampoco.",
  "Hoy celebra estar aquí. Mañana agradecerás haberte cuidado.",
  "Tu bienestar es el pilar de todo lo que construyes.",
  "Eres el guardián de tu propia vida. Ejerce ese poder con responsabilidad.",
  "Cada acción preventiva es una declaración de amor a la vida.",
  "Tu salud, tu familia, tu futuro. Todo depende de que te cuides hoy.",
  "La seguridad es el idioma universal del amor propio.",
  "Hoy tienes todo para ser tu mejor versión. Empieza con seguridad.",
  "Tu legado más grande será el ejemplo de cuidado que dejes.",
  "No hay trabajo perfecto, pero sí formas perfectas de protegerte.",
  "Tu presencia ilumina tu hogar. Regresa siempre a iluminarlo.",
  "La vida te necesita completo. Cuídate de pies a cabeza.",
  "Eres más que suficiente. Y mereces volver sano cada día.",
  "Hoy es el día ideal para renovar tu compromiso con la vida.",
  "Tu seguridad es la semilla de la felicidad de tu familia.",
  "Cada protección que usas es un acto de sabiduría.",
  "Tu valor como ser humano está por encima de cualquier indicador.",
  "La prevención es el regalo más generoso que puedes darte.",
  "Hoy trabaja con pasión, pero sobre todo, con seguridad.",
  "Tu vida es una obra maestra en construcción. No permitas que se detenga.",
  "El autocuidado es la forma más honesta de quererte.",
  "Cada mañana tienes una cita con la vida. No faltes.",
  "Tú eres el motor de tu familia. Mantenlo en óptimas condiciones.",
  "La seguridad no limita, libera. Te libera de preocupaciones innecesarias.",
  "Hoy eres más sabio que ayer. Usa esa sabiduría para protegerte.",
  "Tu compromiso con la seguridad es tu carta de presentación.",
  "Eres el héroe cotidiano de quienes te aman. No lo olvides.",
  "Cada día sin incidentes es un día de victoria para todos.",
  "Tu bienestar no es negociable. Defiéndelo siempre.",
  "La seguridad se vive, se respira, se practica. Hazla parte de ti.",
  "Hoy empieza tu jornada con la mejor actitud y la mayor precaución.",
  "Tu vida merece ser vivida plenamente. Cuida cada paso que das.",
  "El amor propio se demuestra con acciones seguras.",
  "Eres irremplazable. Punto. Cuídate como tal.",
  "Cada medida de seguridad es un escalón hacia una vida plena.",
  "Tu tranquilidad al trabajar se transmite a todo tu entorno.",
  "Hoy y siempre: mereces volver a casa con una sonrisa.",
  "La prevención es el arte de amar la vida en cada detalle.",
  "Tu fuerza no está solo en tus brazos, está en tu capacidad de protegerte.",
  "Cada día es un lienzo en blanco. Píntalo con seguridad y alegría.",
  "Tu salud es sagrada. Trátala con el respeto que merece.",
  "Eres parte de algo más grande. Tu seguridad importa para todos.",
  "La vida te sonríe cuando tú la cuidas. Sonríele de vuelta.",
  "Hoy decide ser la mejor versión de ti: segura, consciente y valiente.",
  "Tu camino apenas comienza. Asegúrate de recorrerlo con protección.",
  "Cada respiro es un recordatorio de lo valiosa que es tu vida.",
  "Tu familia te necesita entero. No les falles.",
  "La seguridad es la base de la dignidad en el trabajo.",
  "Hoy celebra tu vida cuidándola. Es el mejor homenaje que puedes hacerte.",
  "Tú eres el proyecto más importante de tu vida. Invierte en tu seguridad.",
  "Cada decisión segura es un paso firme hacia tus sueños.",
  "Tu bienestar construye un mundo mejor para quienes te rodean.",
  "No hay mañana sin el cuidado de hoy. Protégete ahora.",
  "Eres luz para muchas personas. No permitas que esa luz se apague.",
  "La seguridad no es una carga, es el camino más liviano.",
  "Hoy agradece por estar aquí y comprométete a seguir estando.",
  "Tu vida es el regalo más grande que has recibido. Cuídalo.",
  "Cada jornada segura suma años de felicidad a tu vida.",
  "Tu determinación por llegar sano a casa es tu mayor victoria.",
  "La prevención es inteligencia aplicada a la vida diaria.",
  "Eres extraordinario. Y mereces un lugar de trabajo que te proteja.",
  "Hoy es tu día. Vívelo con seguridad, vívelo con propósito.",
  "Tu corazón late por quienes te esperan. Regresa siempre por ellos.",
  "La seguridad es silenciosa, pero su ausencia es ensordecedora.",
  "Cada acción consciente es un tributo a la vida.",
  "Tú eres la razón suficiente para trabajar seguro. Siempre.",
  "Hoy tu mejor decisión será cuidarte. Las demás vendrán después.",
  "La vida es corta para desperdiciarla en riesgos innecesarios.",
  "Tu presencia en el mundo importa. Protégela con todo tu ser.",
  "Cada amanecer te dice: vale la pena cuidarse un día más.",
  "Tu seguridad es la promesa más bonita que le haces a tu familia.",
  "Hoy serás más fuerte porque elegirás ser más prudente.",
  "La prevención es la poesía del trabajo bien hecho.",
  "Tu bienestar ilumina todo lo que tocas. No dejes que se apague.",
  "Eres el milagro de cada día. Cuídate como el tesoro que eres.",
  "Cada paso seguro es un paso hacia la plenitud.",
  "Hoy el mundo te necesita. Preséntate completo, seguro y feliz.",
  "Tu vida es la prueba de que vale la pena prevenir.",
  "La seguridad es el abrazo invisible que te protege cada día.",
  "Eres suficiente, eres valioso, eres amado. Cuídate por ellos y por ti.",
  "Hoy cierra los ojos un segundo y recuerda por quién trabajas. Ahora, hazlo seguro.",
  "Tu compromiso con la vida es la mejor herencia que puedes dejar.",
  "Cada momento de cuidado es un momento de grandeza.",
  "La prevención es la forma más elegante de amar la vida.",
  "Hoy tu familia necesita que regreses. Y tú mereces regresar.",
  "Tú eres más importante que cualquier plazo, meta o indicador.",
  "La seguridad es el fundamento de una vida con propósito.",
  "Cada día que vuelves sano a casa, gana el amor.",
  "Hoy sé fuerte en la prevención y suave con tu bienestar.",
  "Tu vida es irrepetible. Protégela como la joya que es.",
  "Eres el centro del universo de alguien. No dejes de brillar.",
  "La seguridad es el puente entre tus sueños y tu realidad.",
  "Hoy recuerda: nadie puede cuidarte mejor que tú mismo.",
  "Tu existencia tiene un impacto que ni imaginas. Sigue aquí.",
  "Cada medida preventiva es una carta de amor a tu futuro.",
  "Hoy y siempre: tú eres la razón más importante para trabajar seguro.",
  "La vida te espera afuera. Asegúrate de llegar a vivirla.",
  "Tu seguridad hoy es la paz de tu familia esta noche.",
  "Eres el arquitecto de tu propio cuidado. Construye con sabiduría.",
  "Cada día seguro es un capítulo feliz en tu historia de vida.",
  "Hoy abraza la prevención como abrazas a quienes amas.",
  "Tu salud es el cimiento de todos tus logros. No lo descuides.",
  "La seguridad es la melodía que hace armoniosa tu jornada.",
  "Eres parte de una cadena de cuidado. Tu eslabón es vital.",
  "Hoy vive con intención, trabaja con prevención.",
  "Tu vida es una bendición para muchos. Consérvala con cariño.",
  "Cada protección es una promesa cumplida contigo mismo.",
  "La prevención es el lenguaje silencioso del amor por la vida.",
  "Hoy comienza con gratitud y termina con seguridad.",
  "Tú eres irreemplazable. Recuérdalo en cada decisión que tomes.",
  "La seguridad no se hereda, se practica. Hoy es tu oportunidad.",
  "Cada instante de cuidado vale una vida entera de felicidad.",
  "Hoy tu mejor versión se presenta segura, consciente y agradecida.",
  "Tu bienestar es la estrella que guía a tu familia. Brilla siempre.",
  "La vida es el viaje más hermoso. Recórrelo con seguridad.",
  "Eres el tesoro más valioso de tu hogar. Protégete sin excusas.",
  "Hoy y cada día: la seguridad es tu mejor compañía.",
  "Tu presencia en el mundo cambia vidas. Asegura la tuya primero.",
  "Cada acto de prevención es un acto de fe en el futuro.",
  "La seguridad es la raíz de la que crece todo lo bueno.",
  "Hoy eres más fuerte, más sabio y más comprometido con tu vida.",
  "Tu seguridad es la llave que abre la puerta de un mañana mejor.",
  "Eres la persona que alguien necesita ver llegar cada tarde.",
  "La prevención es la forma más hermosa de decir: me importo.",
  "Hoy cuida tu cuerpo, tu mente y tu espíritu. Los tres te necesitan.",
  "Tu vida es un regalo que merece ser protegido todos los días.",
  "Cada jornada segura es una victoria silenciosa del amor.",
  "Eres suficiente. Eres necesario. Eres amado. Trabaja seguro.",
];

export function getFraseDelDia(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return FRASES_MOTIVACIONALES[dayOfYear % FRASES_MOTIVACIONALES.length];
}
