export interface DailyChallenge {
  dragEmoji: string;
  dropEmoji: string;
  dragName: string;
  article: string;
  successEmoji: string;
  successMessage: string;
}

export const ALL_CHALLENGES: DailyChallenge[] = [
  { dragEmoji: "⛑️", dropEmoji: "👷", dragName: "Casco de Seguridad", article: "el", successEmoji: "👷‍♂️", successMessage: "EPP listo. A trabajar seguro!" },
  { dragEmoji: "🍎", dropEmoji: "❤️", dragName: "Manzana Saludable", article: "la", successEmoji: "💪", successMessage: "Salud ocupacional al día!" },
  { dragEmoji: "🧯", dropEmoji: "🔥", dragName: "Extintor", article: "el", successEmoji: "✅", successMessage: "Emergencia controlada!" },
  { dragEmoji: "📋", dropEmoji: "🎓", dragName: "Plan de Capacitación", article: "el", successEmoji: "🏆", successMessage: "Capacitación registrada!" },
  { dragEmoji: "🛡️", dropEmoji: "⚠️", dragName: "Escudo de Prevención", article: "el", successEmoji: "🦺", successMessage: "Riesgos bajo control!" },
  { dragEmoji: "📊", dropEmoji: "📈", dragName: "Informe de Gestión", article: "el", successEmoji: "💯", successMessage: "Indicadores al día!" },
  { dragEmoji: "🚗", dropEmoji: "🛣️", dragName: "Vehículo Seguro", article: "el", successEmoji: "🏁", successMessage: "PESV: Seguridad vial activa!" },
  { dragEmoji: "🥾", dropEmoji: "🦶", dragName: "Bota de Seguridad", article: "la", successEmoji: "🚶", successMessage: "Pisando firme y seguro!" },
  { dragEmoji: "🧤", dropEmoji: "🤚", dragName: "Guantes de Protección", article: "los", successEmoji: "👐", successMessage: "Manos protegidas!" },
  { dragEmoji: "🥽", dropEmoji: "👀", dragName: "Gafas de Seguridad", article: "las", successEmoji: "👓", successMessage: "Visión protegida!" },
  { dragEmoji: "🔔", dropEmoji: "📢", dragName: "Alarma de Emergencia", article: "la", successEmoji: "🔊", successMessage: "Alerta activada!" },
  { dragEmoji: "💉", dropEmoji: "🏥", dragName: "Vacuna Ocupacional", article: "la", successEmoji: "💊", successMessage: "Salud preventiva al día!" },
  { dragEmoji: "🩺", dropEmoji: "👨‍⚕️", dragName: "Estetoscopio Médico", article: "el", successEmoji: "🏥", successMessage: "Examen médico completado!" },
  { dragEmoji: "📝", dropEmoji: "📂", dragName: "Acta de Reunión", article: "el", successEmoji: "✅", successMessage: "Acta del COPASST archivada!" },
  { dragEmoji: "🔧", dropEmoji: "⚙️", dragName: "Herramienta Segura", article: "la", successEmoji: "🛠️", successMessage: "Mantenimiento preventivo OK!" },
  { dragEmoji: "🪜", dropEmoji: "🏗️", dragName: "Escalera Certificada", article: "la", successEmoji: "🏢", successMessage: "Trabajo en alturas seguro!" },
  { dragEmoji: "🎒", dropEmoji: "🧰", dragName: "Kit de Emergencia", article: "el", successEmoji: "🆘", successMessage: "Brigada preparada!" },
  { dragEmoji: "📖", dropEmoji: "👨‍🏫", dragName: "Manual de SST", article: "el", successEmoji: "📚", successMessage: "Conocimiento es prevención!" },
  { dragEmoji: "🔦", dropEmoji: "🌑", dragName: "Linterna de Emergencia", article: "la", successEmoji: "💡", successMessage: "Ruta de evacuación iluminada!" },
  { dragEmoji: "🪪", dropEmoji: "🏢", dragName: "Carnet de Seguridad", article: "el", successEmoji: "🎫", successMessage: "Acceso autorizado!" },
  { dragEmoji: "🧹", dropEmoji: "🏭", dragName: "Limpieza Industrial", article: "la", successEmoji: "✨", successMessage: "Orden y aseo impecable!" },
  { dragEmoji: "🗺️", dropEmoji: "🚪", dragName: "Plano de Evacuación", article: "el", successEmoji: "🏃", successMessage: "Ruta de evacuación lista!" },
  { dragEmoji: "📻", dropEmoji: "🎙️", dragName: "Radio de Emergencia", article: "el", successEmoji: "📡", successMessage: "Comunicación de crisis activa!" },
  { dragEmoji: "🧲", dropEmoji: "⚡", dragName: "Protección Eléctrica", article: "la", successEmoji: "🔌", successMessage: "Riesgo eléctrico controlado!" },
  { dragEmoji: "🌡️", dropEmoji: "🥵", dragName: "Monitor de Temperatura", article: "el", successEmoji: "❄️", successMessage: "Estrés térmico bajo control!" },
  { dragEmoji: "🫁", dropEmoji: "😷", dragName: "Respirador N95", article: "el", successEmoji: "🌬️", successMessage: "Aire limpio garantizado!" },
  { dragEmoji: "🎯", dropEmoji: "📌", dragName: "Meta de Seguridad", article: "la", successEmoji: "🏅", successMessage: "Objetivo SST cumplido!" },
  { dragEmoji: "📐", dropEmoji: "🪑", dragName: "Evaluación Ergonómica", article: "la", successEmoji: "💺", successMessage: "Puesto de trabajo ajustado!" },
  { dragEmoji: "🔒", dropEmoji: "🚧", dragName: "Candado de Bloqueo", article: "el", successEmoji: "🔐", successMessage: "LOTO aplicado correctamente!" },
  { dragEmoji: "🩹", dropEmoji: "🤕", dragName: "Botiquín de Primeros Auxilios", article: "el", successEmoji: "🏥", successMessage: "Primeros auxilios listos!" },
  { dragEmoji: "📣", dropEmoji: "👥", dragName: "Charla de Seguridad", article: "la", successEmoji: "🗣️", successMessage: "Charla de 5 minutos completada!" },
  { dragEmoji: "🪧", dropEmoji: "🚫", dragName: "Señal de Prohibición", article: "la", successEmoji: "🚷", successMessage: "Zona restringida señalizada!" },
  { dragEmoji: "🔬", dropEmoji: "🧪", dragName: "Muestra de Laboratorio", article: "la", successEmoji: "🧫", successMessage: "Monitoreo ambiental OK!" },
  { dragEmoji: "🎓", dropEmoji: "📜", dragName: "Certificación SST", article: "la", successEmoji: "🏆", successMessage: "Profesional certificado!" },
  { dragEmoji: "🚑", dropEmoji: "🏨", dragName: "Ambulancia", article: "la", successEmoji: "⛑️", successMessage: "Plan de emergencia activo!" },
  { dragEmoji: "🗂️", dropEmoji: "🗄️", dragName: "Expediente del Trabajador", article: "el", successEmoji: "📁", successMessage: "Documentación completa!" },
  { dragEmoji: "📅", dropEmoji: "✏️", dragName: "Cronograma de Actividades", article: "el", successEmoji: "📆", successMessage: "Plan anual actualizado!" },
  { dragEmoji: "🔊", dropEmoji: "👂", dragName: "Protección Auditiva", article: "la", successEmoji: "🎧", successMessage: "Audiometría al día!" },
  { dragEmoji: "🧴", dropEmoji: "☀️", dragName: "Protector Solar", article: "el", successEmoji: "🌤️", successMessage: "Piel protegida del sol!" },
  { dragEmoji: "💧", dropEmoji: "🚰", dragName: "Agua Potable", article: "el", successEmoji: "🥤", successMessage: "Hidratación garantizada!" },
  { dragEmoji: "🪣", dropEmoji: "☣️", dragName: "Kit Antiderrames", article: "el", successEmoji: "🧽", successMessage: "Derrame contenido!" },
  { dragEmoji: "📷", dropEmoji: "🔍", dragName: "Inspección Fotográfica", article: "la", successEmoji: "📸", successMessage: "Evidencia registrada!" },
  { dragEmoji: "🧯", dropEmoji: "🏢", dragName: "Recarga del Extintor", article: "la", successEmoji: "✅", successMessage: "Extintor vigente!" },
  { dragEmoji: "🪖", dropEmoji: "🏗️", dragName: "Casco para Alturas", article: "el", successEmoji: "⛑️", successMessage: "Trabajo en alturas aprobado!" },
  { dragEmoji: "📱", dropEmoji: "🆘", dragName: "App de Emergencia", article: "la", successEmoji: "📲", successMessage: "Reporte inmediato enviado!" },
  { dragEmoji: "🧪", dropEmoji: "💨", dragName: "Medición de Gases", article: "la", successEmoji: "🌿", successMessage: "Atmósfera segura!" },
  { dragEmoji: "🪢", dropEmoji: "🧗", dragName: "Arnés de Seguridad", article: "el", successEmoji: "🦺", successMessage: "Anclaje verificado!" },
  { dragEmoji: "🔋", dropEmoji: "💡", dragName: "Luz de Emergencia", article: "la", successEmoji: "🔦", successMessage: "Iluminación de respaldo OK!" },
  { dragEmoji: "🗓️", dropEmoji: "🩺", dragName: "Cita Médica Ocupacional", article: "la", successEmoji: "👨‍⚕️", successMessage: "Control médico programado!" },
  { dragEmoji: "🚿", dropEmoji: "👁️", dragName: "Ducha Lavaojos", article: "la", successEmoji: "💧", successMessage: "Estación de emergencia lista!" },
  { dragEmoji: "📦", dropEmoji: "🏷️", dragName: "Etiqueta SGA", article: "la", successEmoji: "⚗️", successMessage: "Químico identificado!" },
  { dragEmoji: "🚜", dropEmoji: "🅿️", dragName: "Vehículo Industrial", article: "el", successEmoji: "🏁", successMessage: "Operador certificado!" },
  { dragEmoji: "🌊", dropEmoji: "🏖️", dragName: "Plan de Inundación", article: "el", successEmoji: "🌈", successMessage: "Riesgo natural mitigado!" },
  { dragEmoji: "🦠", dropEmoji: "🧫", dragName: "Control Biológico", article: "el", successEmoji: "🔬", successMessage: "Riesgo biológico controlado!" },
  { dragEmoji: "🎪", dropEmoji: "🏟️", dragName: "Simulacro General", article: "el", successEmoji: "🎖️", successMessage: "Simulacro exitoso!" },
  { dragEmoji: "🪞", dropEmoji: "🧑‍💼", dragName: "Autoevaluación SST", article: "la", successEmoji: "📊", successMessage: "Autoevaluación completada!" },
  { dragEmoji: "🌿", dropEmoji: "🏞️", dragName: "Plan Ambiental", article: "el", successEmoji: "🌍", successMessage: "Ambiente laboral saludable!" },
  { dragEmoji: "🎭", dropEmoji: "🧠", dragName: "Evaluación Psicosocial", article: "la", successEmoji: "😊", successMessage: "Bienestar emocional OK!" },
  { dragEmoji: "🪶", dropEmoji: "📝", dragName: "Política de SST", article: "la", successEmoji: "📄", successMessage: "Política firmada y vigente!" },
  { dragEmoji: "🔑", dropEmoji: "🚪", dragName: "Llave de Seguridad", article: "la", successEmoji: "🔓", successMessage: "Área asegurada!" },
  { dragEmoji: "🎬", dropEmoji: "📺", dragName: "Video de Inducción", article: "el", successEmoji: "🎥", successMessage: "Inducción completada!" },
  { dragEmoji: "🌐", dropEmoji: "💻", dragName: "Reporte Digital SST", article: "el", successEmoji: "🖥️", successMessage: "Reporte enviado al sistema!" },
  { dragEmoji: "🧊", dropEmoji: "🥶", dragName: "Protección contra Frío", article: "la", successEmoji: "🧣", successMessage: "Trabajador abrigado!" },
  { dragEmoji: "🪤", dropEmoji: "🐀", dragName: "Control de Plagas", article: "el", successEmoji: "🧹", successMessage: "Instalaciones libres de plagas!" },
  { dragEmoji: "🔩", dropEmoji: "🏗️", dragName: "Tornillo de Anclaje", article: "el", successEmoji: "🔨", successMessage: "Estructura asegurada!" },
  { dragEmoji: "🧬", dropEmoji: "🏥", dragName: "Perfil Epidemiológico", article: "el", successEmoji: "📊", successMessage: "Perfil de salud actualizado!" },
  { dragEmoji: "🎤", dropEmoji: "👨‍💼", dragName: "Rendición de Cuentas", article: "la", successEmoji: "📢", successMessage: "Gestión transparente!" },
  { dragEmoji: "🧭", dropEmoji: "🗺️", dragName: "Brújula de Prevención", article: "la", successEmoji: "🧭", successMessage: "Rumbo seguro establecido!" },
  { dragEmoji: "💼", dropEmoji: "🏢", dragName: "Maletín del Inspector", article: "el", successEmoji: "🔍", successMessage: "Inspección programada!" },
  { dragEmoji: "🪚", dropEmoji: "🪵", dragName: "Sierra Protegida", article: "la", successEmoji: "🛡️", successMessage: "Herramienta con guarda!" },
  { dragEmoji: "🧰", dropEmoji: "🔧", dragName: "Caja de Herramientas", article: "la", successEmoji: "🛠️", successMessage: "Herramientas inspeccionadas!" },
  { dragEmoji: "🏋️", dropEmoji: "🧘", dragName: "Pausa Activa", article: "la", successEmoji: "🤸", successMessage: "Pausa activa realizada!" },
  { dragEmoji: "🚦", dropEmoji: "🛑", dragName: "Semáforo Vial", article: "el", successEmoji: "🟢", successMessage: "Tránsito seguro!" },
  { dragEmoji: "🧑‍🚒", dropEmoji: "🔥", dragName: "Brigadista", article: "el", successEmoji: "🦸", successMessage: "Brigadista en posición!" },
  { dragEmoji: "🪟", dropEmoji: "🌬️", dragName: "Ventilación Natural", article: "la", successEmoji: "💨", successMessage: "Ventilación adecuada!" },
  { dragEmoji: "🛞", dropEmoji: "🚙", dragName: "Llanta en Buen Estado", article: "la", successEmoji: "🏎️", successMessage: "Vehículo revisado!" },
  { dragEmoji: "📌", dropEmoji: "🗂️", dragName: "Registro de Incidentes", article: "el", successEmoji: "📋", successMessage: "Incidente documentado!" },
  { dragEmoji: "🥇", dropEmoji: "🏆", dragName: "Premio Cero Accidentes", article: "el", successEmoji: "🎉", successMessage: "Cero accidentes este mes!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "💊", dragName: "Médico Ocupacional", article: "el", successEmoji: "🩺", successMessage: "Consulta médica OK!" },
  { dragEmoji: "🪫", dropEmoji: "🔌", dragName: "Batería de Respaldo", article: "la", successEmoji: "⚡", successMessage: "Energía de emergencia lista!" },
  { dragEmoji: "🎪", dropEmoji: "👷‍♀️", dragName: "Jornada de SST", article: "la", successEmoji: "🎊", successMessage: "Jornada de seguridad exitosa!" },
  { dragEmoji: "🔭", dropEmoji: "🌄", dragName: "Vigilancia Epidemiológica", article: "la", successEmoji: "📡", successMessage: "SVE actualizado!" },
  { dragEmoji: "🪝", dropEmoji: "⚓", dragName: "Gancho de Seguridad", article: "el", successEmoji: "🔗", successMessage: "Punto de anclaje fijo!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "🔬", dragName: "Higienista Industrial", article: "el", successEmoji: "🧪", successMessage: "Medición higiénica OK!" },
  { dragEmoji: "🎾", dropEmoji: "🏃‍♂️", dragName: "Programa Deportivo", article: "el", successEmoji: "🏅", successMessage: "Bienestar físico activo!" },
  { dragEmoji: "🌻", dropEmoji: "🧘‍♀️", dragName: "Programa de Bienestar", article: "el", successEmoji: "🌸", successMessage: "Bienestar integral!" },
  { dragEmoji: "🔫", dropEmoji: "🚫", dragName: "Control de Armas", article: "el", successEmoji: "🛡️", successMessage: "Zona libre de armas!" },
  { dragEmoji: "🧲", dropEmoji: "🧲", dragName: "Campo Magnético", article: "el", successEmoji: "📡", successMessage: "Radiación no ionizante OK!" },
  { dragEmoji: "🌋", dropEmoji: "🏔️", dragName: "Plan Volcánico", article: "el", successEmoji: "🛡️", successMessage: "Plan de contingencia listo!" },
  { dragEmoji: "🌪️", dropEmoji: "🏠", dragName: "Plan contra Tormentas", article: "el", successEmoji: "☀️", successMessage: "Refugio seguro identificado!" },
  { dragEmoji: "⏱️", dropEmoji: "🕐", dragName: "Control de Jornada", article: "el", successEmoji: "⌛", successMessage: "Jornada laboral legal!" },
  { dragEmoji: "🪙", dropEmoji: "💰", dragName: "Presupuesto SST", article: "el", successEmoji: "💵", successMessage: "Recursos asignados!" },
  { dragEmoji: "🖊️", dropEmoji: "📑", dragName: "Firma de Compromiso", article: "la", successEmoji: "✍️", successMessage: "Compromiso adquirido!" },
  { dragEmoji: "🧑‍🍳", dropEmoji: "🍽️", dragName: "Higiene Alimentaria", article: "la", successEmoji: "✅", successMessage: "Alimentos seguros!" },
  { dragEmoji: "🎧", dropEmoji: "🔇", dragName: "Tapones Auditivos", article: "los", successEmoji: "🤫", successMessage: "Ruido controlado!" },
  { dragEmoji: "🚰", dropEmoji: "🧪", dragName: "Calidad del Agua", article: "la", successEmoji: "💎", successMessage: "Agua potable verificada!" },
  { dragEmoji: "🛗", dropEmoji: "🔧", dragName: "Mantenimiento Ascensor", article: "el", successEmoji: "✅", successMessage: "Ascensor certificado!" },
  { dragEmoji: "🧯", dropEmoji: "🧑‍🚒", dragName: "Práctica con Extintor", article: "la", successEmoji: "🔥", successMessage: "Práctica contra incendios OK!" },
  { dragEmoji: "🪜", dropEmoji: "📏", dragName: "Inspección de Escalera", article: "la", successEmoji: "✅", successMessage: "Escalera aprobada!" },
  { dragEmoji: "🧲", dropEmoji: "🪛", dragName: "Detector de Metales", article: "el", successEmoji: "🔍", successMessage: "Área libre de objetos!" },
  { dragEmoji: "🌬️", dropEmoji: "🫧", dragName: "Calidad del Aire", article: "la", successEmoji: "🌿", successMessage: "Aire interior saludable!" },
  { dragEmoji: "🧱", dropEmoji: "🏗️", dragName: "Inspección Estructural", article: "la", successEmoji: "🏛️", successMessage: "Estructura sólida!" },
  { dragEmoji: "🏍️", dropEmoji: "🛣️", dragName: "Moto con Casco", article: "la", successEmoji: "⛑️", successMessage: "Motociclista protegido!" },
  { dragEmoji: "🚌", dropEmoji: "🚏", dragName: "Transporte de Personal", article: "el", successEmoji: "🚍", successMessage: "Transporte seguro!" },
  { dragEmoji: "🔌", dropEmoji: "🧯", dragName: "Cableado Eléctrico", article: "el", successEmoji: "⚡", successMessage: "Instalación eléctrica segura!" },
  { dragEmoji: "🧫", dropEmoji: "🦠", dragName: "Protocolo Bioseguridad", article: "el", successEmoji: "🛡️", successMessage: "Bioseguridad activa!" },
  { dragEmoji: "🗑️", dropEmoji: "♻️", dragName: "Residuos Peligrosos", article: "los", successEmoji: "🌱", successMessage: "Residuos bien clasificados!" },
  { dragEmoji: "🌙", dropEmoji: "🛏️", dragName: "Turno Nocturno Seguro", article: "el", successEmoji: "🌟", successMessage: "Turno nocturno protegido!" },
  { dragEmoji: "☔", dropEmoji: "🧥", dragName: "Impermeable de Trabajo", article: "el", successEmoji: "🌧️", successMessage: "Protegido de la lluvia!" },
  { dragEmoji: "🧯", dropEmoji: "🏪", dragName: "Extintor del Local", article: "el", successEmoji: "🔥", successMessage: "Local comercial seguro!" },
  { dragEmoji: "📎", dropEmoji: "📚", dragName: "Carpeta de Evidencias", article: "la", successEmoji: "🗃️", successMessage: "Evidencias organizadas!" },
  { dragEmoji: "🩻", dropEmoji: "🏥", dragName: "Rayos X Ocupacional", article: "los", successEmoji: "🩺", successMessage: "Examen radiológico OK!" },
  { dragEmoji: "🧑‍✈️", dropEmoji: "✈️", dragName: "Seguridad Aeroportuaria", article: "la", successEmoji: "🛫", successMessage: "Vuelo seguro!" },
  { dragEmoji: "🚢", dropEmoji: "⚓", dragName: "Seguridad Marítima", article: "la", successEmoji: "🛟", successMessage: "Navegación segura!" },
  { dragEmoji: "🧊", dropEmoji: "🥩", dragName: "Cadena de Frío", article: "la", successEmoji: "❄️", successMessage: "Cadena de frío intacta!" },
  { dragEmoji: "🔆", dropEmoji: "🕶️", dragName: "Protección UV", article: "la", successEmoji: "🌞", successMessage: "Ojos protegidos del sol!" },
  { dragEmoji: "🧑‍🏭", dropEmoji: "🏭", dragName: "Operario Capacitado", article: "el", successEmoji: "🎓", successMessage: "Operario certificado!" },
  { dragEmoji: "🪛", dropEmoji: "🔩", dragName: "Destornillador Aislado", article: "el", successEmoji: "🛡️", successMessage: "Herramienta dieléctrica!" },
  { dragEmoji: "🚧", dropEmoji: "🛑", dragName: "Barricada de Seguridad", article: "la", successEmoji: "🚧", successMessage: "Zona demarcada!" },
  { dragEmoji: "📡", dropEmoji: "🌐", dragName: "Sistema de Monitoreo", article: "el", successEmoji: "🖥️", successMessage: "Monitoreo en tiempo real!" },
  { dragEmoji: "🧪", dropEmoji: "🔥", dragName: "Prueba de Inflamabilidad", article: "la", successEmoji: "📊", successMessage: "Material no inflamable!" },
  { dragEmoji: "🌾", dropEmoji: "🚜", dragName: "Seguridad Agrícola", article: "la", successEmoji: "🌻", successMessage: "Campo seguro!" },
  { dragEmoji: "⛏️", dropEmoji: "🏔️", dragName: "Seguridad Minera", article: "la", successEmoji: "💎", successMessage: "Mina asegurada!" },
  { dragEmoji: "🧑‍🔧", dropEmoji: "🔩", dragName: "Técnico de Mantenimiento", article: "el", successEmoji: "🔧", successMessage: "Mantenimiento completado!" },
  { dragEmoji: "🎗️", dropEmoji: "👥", dragName: "Campaña de Salud", article: "la", successEmoji: "🏥", successMessage: "Campaña de salud exitosa!" },
  { dragEmoji: "🪞", dropEmoji: "🚗", dragName: "Espejo Retrovisor", article: "el", successEmoji: "👁️", successMessage: "Visibilidad completa!" },
  { dragEmoji: "🔔", dropEmoji: "🏢", dragName: "Alarma Contra Incendios", article: "la", successEmoji: "🧯", successMessage: "Sistema contra incendios OK!" },
  { dragEmoji: "🩸", dropEmoji: "🏥", dragName: "Banco de Sangre", article: "el", successEmoji: "❤️", successMessage: "Donación de sangre activa!" },
  { dragEmoji: "🧯", dropEmoji: "⛽", dragName: "Extintor de Gasolinera", article: "el", successEmoji: "✅", successMessage: "Estación de servicio segura!" },
  { dragEmoji: "📲", dropEmoji: "🔔", dragName: "Notificación de Alerta", article: "la", successEmoji: "📳", successMessage: "Alerta enviada a todos!" },
  { dragEmoji: "🧑‍💻", dropEmoji: "🖥️", dragName: "Ergonomía Digital", article: "la", successEmoji: "💺", successMessage: "Pantalla a buena distancia!" },
  { dragEmoji: "🪒", dropEmoji: "🚫", dragName: "Objeto Cortopunzante", article: "el", successEmoji: "🛡️", successMessage: "Cortopunzante descartado!" },
  { dragEmoji: "🌡️", dropEmoji: "🧑‍⚕️", dragName: "Toma de Temperatura", article: "la", successEmoji: "✅", successMessage: "Temperatura normal!" },
  { dragEmoji: "🚒", dropEmoji: "🏢", dragName: "Carro de Bomberos", article: "el", successEmoji: "🧑‍🚒", successMessage: "Bomberos en posición!" },
  { dragEmoji: "🧲", dropEmoji: "📡", dragName: "Medición Electromagnética", article: "la", successEmoji: "📊", successMessage: "Niveles seguros!" },
  { dragEmoji: "🥊", dropEmoji: "😠", dragName: "Prevención de Violencia", article: "la", successEmoji: "🕊️", successMessage: "Ambiente laboral pacífico!" },
  { dragEmoji: "🧮", dropEmoji: "📊", dragName: "Estadísticas de Accidentes", article: "las", successEmoji: "📉", successMessage: "Tasa de accidentes en baja!" },
  { dragEmoji: "🪪", dropEmoji: "🧑‍💼", dragName: "Credencial de Visitante", article: "la", successEmoji: "🎫", successMessage: "Visitante registrado!" },
  { dragEmoji: "🧪", dropEmoji: "💧", dragName: "Análisis de Agua", article: "el", successEmoji: "💎", successMessage: "Agua apta para consumo!" },
  { dragEmoji: "🎪", dropEmoji: "🏃‍♀️", dragName: "Simulacro de Evacuación", article: "el", successEmoji: "🏁", successMessage: "Evacuación en 3 minutos!" },
  { dragEmoji: "📋", dropEmoji: "✅", dragName: "Lista de Chequeo", article: "la", successEmoji: "📝", successMessage: "Checklist completado!" },
  { dragEmoji: "🌱", dropEmoji: "🏢", dragName: "Planta Purificadora", article: "la", successEmoji: "🌿", successMessage: "Aire purificado!" },
  { dragEmoji: "🔐", dropEmoji: "💻", dragName: "Ciberseguridad SST", article: "la", successEmoji: "🛡️", successMessage: "Datos protegidos!" },
  { dragEmoji: "🦺", dropEmoji: "👷‍♀️", dragName: "Chaleco Reflectivo", article: "el", successEmoji: "🌟", successMessage: "Visibilidad nocturna OK!" },
  { dragEmoji: "🧯", dropEmoji: "🧑‍🍳", dragName: "Extintor de Cocina", article: "el", successEmoji: "🍳", successMessage: "Cocina industrial segura!" },
  { dragEmoji: "🚲", dropEmoji: "⛑️", dragName: "Ciclista con Casco", article: "el", successEmoji: "🚴", successMessage: "Ciclista protegido!" },
  { dragEmoji: "🏥", dropEmoji: "🚑", dragName: "Centro Médico", article: "el", successEmoji: "⛑️", successMessage: "Atención médica disponible!" },
  { dragEmoji: "🧑‍🎓", dropEmoji: "📖", dragName: "Estudiante en Práctica", article: "el", successEmoji: "🎓", successMessage: "Practicante capacitado!" },
  { dragEmoji: "🪫", dropEmoji: "🔦", dragName: "Recarga de Linterna", article: "la", successEmoji: "💡", successMessage: "Linterna de emergencia lista!" },
  { dragEmoji: "🧑‍🦽", dropEmoji: "♿", dragName: "Accesibilidad", article: "la", successEmoji: "🏢", successMessage: "Espacio inclusivo!" },
  { dragEmoji: "🫀", dropEmoji: "🏃", dragName: "Examen Cardiovascular", article: "el", successEmoji: "❤️", successMessage: "Corazón saludable!" },
  { dragEmoji: "🧪", dropEmoji: "🧲", dragName: "Prueba de Materiales", article: "la", successEmoji: "✅", successMessage: "Material certificado!" },
  { dragEmoji: "🛻", dropEmoji: "📦", dragName: "Carga Segura", article: "la", successEmoji: "🔒", successMessage: "Carga bien asegurada!" },
  { dragEmoji: "🧑‍🌾", dropEmoji: "🌾", dragName: "Seguridad en Campo", article: "la", successEmoji: "🌻", successMessage: "Trabajo rural protegido!" },
  { dragEmoji: "🏊", dropEmoji: "🛟", dragName: "Salvavidas", article: "el", successEmoji: "🏖️", successMessage: "Rescate acuático listo!" },
  { dragEmoji: "🌬️", dropEmoji: "🏭", dragName: "Extractor de Humos", article: "el", successEmoji: "💨", successMessage: "Humos evacuados!" },
  { dragEmoji: "🧑‍🎤", dropEmoji: "📢", dragName: "Vocero de Emergencia", article: "el", successEmoji: "🎙️", successMessage: "Comunicado emitido!" },
  { dragEmoji: "🗃️", dropEmoji: "📁", dragName: "Archivo de SST", article: "el", successEmoji: "🗄️", successMessage: "20 años archivados!" },
  { dragEmoji: "⚖️", dropEmoji: "📜", dragName: "Norma Legal SST", article: "la", successEmoji: "🏛️", successMessage: "Cumplimiento legal OK!" },
  { dragEmoji: "🛞", dropEmoji: "🔧", dragName: "Rotación de Llantas", article: "la", successEmoji: "🚗", successMessage: "Llantas en perfecto estado!" },
  { dragEmoji: "🧪", dropEmoji: "🫁", dragName: "Espirometría", article: "la", successEmoji: "💨", successMessage: "Función pulmonar normal!" },
  { dragEmoji: "🏗️", dropEmoji: "📐", dragName: "Plano de Obra", article: "el", successEmoji: "🏢", successMessage: "Obra con permisos!" },
  { dragEmoji: "🧊", dropEmoji: "🥤", dragName: "Hidratación en Calor", article: "la", successEmoji: "💧", successMessage: "Trabajador hidratado!" },
  { dragEmoji: "🔦", dropEmoji: "🏭", dragName: "Inspección Nocturna", article: "la", successEmoji: "🌙", successMessage: "Turno nocturno revisado!" },
  { dragEmoji: "🧑‍⚖️", dropEmoji: "📋", dragName: "Auditoría Interna", article: "la", successEmoji: "✅", successMessage: "Auditoría sin hallazgos!" },
  { dragEmoji: "🧲", dropEmoji: "🏗️", dragName: "Grúa Electroimán", article: "la", successEmoji: "🏋️", successMessage: "Carga izada con seguridad!" },
  { dragEmoji: "📯", dropEmoji: "🏢", dragName: "Sirena de Planta", article: "la", successEmoji: "🔔", successMessage: "Sistema de alarma activo!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "🧫", dragName: "Cultivo Microbiológico", article: "el", successEmoji: "🔬", successMessage: "Análisis bacteriológico OK!" },
  { dragEmoji: "🚛", dropEmoji: "🛣️", dragName: "Camión de Carga", article: "el", successEmoji: "📦", successMessage: "Carga pesada asegurada!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "🎓", dragName: "Instructor de SST", article: "el", successEmoji: "📚", successMessage: "Clase de SST terminada!" },
  { dragEmoji: "🪵", dropEmoji: "🪓", dragName: "Tala Segura", article: "la", successEmoji: "🌲", successMessage: "Tala con protocolo!" },
  { dragEmoji: "🧲", dropEmoji: "🛗", dragName: "Revisión del Ascensor", article: "la", successEmoji: "✅", successMessage: "Ascensor inspeccionado!" },
  { dragEmoji: "🦷", dropEmoji: "🧑‍⚕️", dragName: "Salud Dental", article: "la", successEmoji: "😁", successMessage: "Salud oral al día!" },
  { dragEmoji: "👁️", dropEmoji: "🧑‍⚕️", dragName: "Examen Visual", article: "el", successEmoji: "👓", successMessage: "Vista en perfecto estado!" },
  { dragEmoji: "🎽", dropEmoji: "🏃", dragName: "Ropa Deportiva SST", article: "la", successEmoji: "🏅", successMessage: "Actividad física realizada!" },
  { dragEmoji: "🧯", dropEmoji: "🏫", dragName: "Extintor Escolar", article: "el", successEmoji: "🧑‍🏫", successMessage: "Colegio seguro!" },
  { dragEmoji: "🏠", dropEmoji: "💻", dragName: "Teletrabajo Seguro", article: "el", successEmoji: "🪑", successMessage: "Puesto en casa ergonómico!" },
  { dragEmoji: "🧑‍🍼", dropEmoji: "🏢", dragName: "Protección a Gestantes", article: "la", successEmoji: "🤰", successMessage: "Maternidad protegida!" },
  { dragEmoji: "🚁", dropEmoji: "🏥", dragName: "Helicóptero Médico", article: "el", successEmoji: "⛑️", successMessage: "Aeroevacuación lista!" },
  { dragEmoji: "🧑‍🦯", dropEmoji: "🏢", dragName: "Ruta Accesible", article: "la", successEmoji: "♿", successMessage: "Ruta inclusiva señalizada!" },
  { dragEmoji: "🔩", dropEmoji: "🏗️", dragName: "Andamio Certificado", article: "el", successEmoji: "✅", successMessage: "Andamio seguro!" },
  { dragEmoji: "🧑‍💻", dropEmoji: "📊", dragName: "Dashboard SST", article: "el", successEmoji: "📈", successMessage: "Panel de control activo!" },
  { dragEmoji: "🌐", dropEmoji: "📡", dragName: "IoT de Seguridad", article: "el", successEmoji: "🤖", successMessage: "Sensores conectados!" },
  { dragEmoji: "🧯", dropEmoji: "🏥", dragName: "Extintor Hospitalario", article: "el", successEmoji: "⛑️", successMessage: "Hospital protegido!" },
  { dragEmoji: "⛽", dropEmoji: "🔥", dragName: "Control de Combustible", article: "el", successEmoji: "🛡️", successMessage: "Combustible almacenado seguro!" },
  { dragEmoji: "🧑‍🎨", dropEmoji: "🪧", dragName: "Diseño de Señalética", article: "el", successEmoji: "🎨", successMessage: "Señalización renovada!" },
  { dragEmoji: "🏋️‍♂️", dropEmoji: "💪", dragName: "Manejo Manual de Cargas", article: "el", successEmoji: "🦾", successMessage: "Técnica de levantamiento OK!" },
  { dragEmoji: "🔭", dropEmoji: "📊", dragName: "Observación Preventiva", article: "la", successEmoji: "👁️", successMessage: "Comportamiento seguro!" },
  { dragEmoji: "🧯", dropEmoji: "🚗", dragName: "Extintor Vehicular", article: "el", successEmoji: "🚙", successMessage: "Vehículo con extintor!" },
  { dragEmoji: "📡", dropEmoji: "🌡️", dragName: "Sensor de Temperatura", article: "el", successEmoji: "🌡️", successMessage: "Temperatura monitoreada!" },
  { dragEmoji: "🧱", dropEmoji: "🚧", dragName: "Muro Cortafuegos", article: "el", successEmoji: "🔥", successMessage: "Compartimentación OK!" },
  { dragEmoji: "🦮", dropEmoji: "🏢", dragName: "Perro de Rescate", article: "el", successEmoji: "🐕", successMessage: "Equipo K9 listo!" },
  { dragEmoji: "🗳️", dropEmoji: "👥", dragName: "Elección COPASST", article: "la", successEmoji: "🗳️", successMessage: "COPASST elegido!" },
  { dragEmoji: "🎼", dropEmoji: "🧘", dragName: "Musicoterapia Laboral", article: "la", successEmoji: "🎵", successMessage: "Estrés laboral reducido!" },
  { dragEmoji: "🥗", dropEmoji: "🍽️", dragName: "Alimentación Balanceada", article: "la", successEmoji: "🥦", successMessage: "Nutrición laboral OK!" },
  { dragEmoji: "🚶‍♂️", dropEmoji: "🚸", dragName: "Cruce Peatonal", article: "el", successEmoji: "✅", successMessage: "Peatón visible y seguro!" },
  { dragEmoji: "🧑‍🦰", dropEmoji: "😊", dragName: "Evaluación de Clima", article: "la", successEmoji: "🌤️", successMessage: "Clima laboral positivo!" },
  { dragEmoji: "🚿", dropEmoji: "🧼", dragName: "Estación de Lavado", article: "la", successEmoji: "🧴", successMessage: "Higiene de manos OK!" },
  { dragEmoji: "📺", dropEmoji: "📢", dragName: "Video de Seguridad", article: "el", successEmoji: "🎬", successMessage: "Comunicación visual efectiva!" },
  { dragEmoji: "🧯", dropEmoji: "🏠", dragName: "Extintor Residencial", article: "el", successEmoji: "🏡", successMessage: "Hogar seguro!" },
  { dragEmoji: "🔗", dropEmoji: "⛓️", dragName: "Cadena de Custodia", article: "la", successEmoji: "🔐", successMessage: "Evidencia preservada!" },
  { dragEmoji: "🧪", dropEmoji: "🌡️", dragName: "Termómetro Industrial", article: "el", successEmoji: "📊", successMessage: "Proceso térmico controlado!" },
  { dragEmoji: "🛶", dropEmoji: "🌊", dragName: "Chaleco Salvavidas", article: "el", successEmoji: "🦺", successMessage: "Navegación con chaleco!" },
  { dragEmoji: "🏗️", dropEmoji: "🪝", dragName: "Grúa Torre", article: "la", successEmoji: "🔒", successMessage: "Izaje controlado!" },
  { dragEmoji: "🧑‍🏭", dropEmoji: "🔬", dragName: "Control de Calidad", article: "el", successEmoji: "✅", successMessage: "Producto seguro!" },
  { dragEmoji: "🦷", dropEmoji: "😷", dragName: "Tapabocas Industrial", article: "el", successEmoji: "🛡️", successMessage: "Vías respiratorias protegidas!" },
  { dragEmoji: "🔊", dropEmoji: "📊", dragName: "Sonometría", article: "la", successEmoji: "📈", successMessage: "Nivel de ruido medido!" },
  { dragEmoji: "🧑‍🔧", dropEmoji: "🔌", dragName: "Electricista Certificado", article: "el", successEmoji: "⚡", successMessage: "Trabajo eléctrico seguro!" },
  { dragEmoji: "🪣", dropEmoji: "🧹", dragName: "Programa 5S", article: "el", successEmoji: "✨", successMessage: "5S implementadas!" },
  { dragEmoji: "🚜", dropEmoji: "⛑️", dragName: "Operador de Maquinaria", article: "el", successEmoji: "🎓", successMessage: "Operador con licencia!" },
  { dragEmoji: "🗡️", dropEmoji: "🛡️", dragName: "Elemento Cortante", article: "el", successEmoji: "🧤", successMessage: "Guante anticorte puesto!" },
  { dragEmoji: "🧯", dropEmoji: "🎪", dragName: "Extintor de Evento", article: "el", successEmoji: "🎉", successMessage: "Evento masivo seguro!" },
  { dragEmoji: "🌳", dropEmoji: "🏢", dragName: "Zona Verde Laboral", article: "la", successEmoji: "🌿", successMessage: "Espacio verde activo!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "📊", dragName: "Indicadores de Salud", article: "los", successEmoji: "📈", successMessage: "Indicadores de salud OK!" },
  { dragEmoji: "🔧", dropEmoji: "🚗", dragName: "Revisión Técnico-mecánica", article: "la", successEmoji: "✅", successMessage: "Vehículo con revisión!" },
  { dragEmoji: "🧊", dropEmoji: "🏭", dragName: "Cuarto Frío Seguro", article: "el", successEmoji: "❄️", successMessage: "Cuarto frío monitoreado!" },
  { dragEmoji: "🧑‍🦱", dropEmoji: "🧢", dragName: "Cofia Industrial", article: "la", successEmoji: "👨‍🍳", successMessage: "Cabello recogido y seguro!" },
  { dragEmoji: "📋", dropEmoji: "🏢", dragName: "Permiso de Trabajo", article: "el", successEmoji: "✅", successMessage: "Permiso aprobado!" },
  { dragEmoji: "🦸‍♂️", dropEmoji: "🏢", dragName: "Líder de Emergencia", article: "el", successEmoji: "📢", successMessage: "Líder designado!" },
  { dragEmoji: "🧲", dropEmoji: "🧯", dragName: "Manómetro del Extintor", article: "el", successEmoji: "✅", successMessage: "Presión adecuada!" },
  { dragEmoji: "🩻", dropEmoji: "🧑‍⚕️", dragName: "Examen de Ingreso", article: "el", successEmoji: "📋", successMessage: "Apto para trabajar!" },
  { dragEmoji: "🔐", dropEmoji: "📂", dragName: "Datos del Trabajador", article: "los", successEmoji: "🛡️", successMessage: "Habeas data protegido!" },
  { dragEmoji: "🧑‍🤝‍🧑", dropEmoji: "🤝", dragName: "Trabajo en Equipo", article: "el", successEmoji: "💪", successMessage: "Equipo SST unido!" },
  { dragEmoji: "🎯", dropEmoji: "📅", dragName: "Meta Anual SST", article: "la", successEmoji: "🏆", successMessage: "Meta del año alcanzada!" },
  { dragEmoji: "🌍", dropEmoji: "♻️", dragName: "ISO 14001 Ambiental", article: "el", successEmoji: "🌿", successMessage: "Gestión ambiental activa!" },
  { dragEmoji: "📜", dropEmoji: "🏛️", dragName: "Resolución 0312", article: "la", successEmoji: "⚖️", successMessage: "Estándares mínimos cumplidos!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "📊", dragName: "Revisión por Dirección", article: "la", successEmoji: "✅", successMessage: "Alta dirección comprometida!" },
  { dragEmoji: "🌐", dropEmoji: "📋", dragName: "ISO 45001", article: "el", successEmoji: "🏆", successMessage: "Sistema de gestión certificado!" },
  { dragEmoji: "🔔", dropEmoji: "📱", dragName: "Alerta Temprana", article: "la", successEmoji: "📳", successMessage: "Alerta recibida a tiempo!" },
  { dragEmoji: "🧯", dropEmoji: "🛢️", dragName: "Extintor Clase B", article: "el", successEmoji: "🛡️", successMessage: "Líquido inflamable controlado!" },
  { dragEmoji: "🚨", dropEmoji: "🏢", dragName: "Luz Estroboscópica", article: "la", successEmoji: "🔴", successMessage: "Señalización luminosa activa!" },
  { dragEmoji: "🧲", dropEmoji: "📏", dragName: "Luxómetro", article: "el", successEmoji: "💡", successMessage: "Iluminación adecuada!" },
  { dragEmoji: "🦺", dropEmoji: "🌙", dragName: "Chaleco Nocturno", article: "el", successEmoji: "🌟", successMessage: "Trabajador visible de noche!" },
  { dragEmoji: "🧪", dropEmoji: "🧴", dragName: "Hoja de Seguridad", article: "la", successEmoji: "📋", successMessage: "MSDS disponible!" },
  { dragEmoji: "🏥", dropEmoji: "📋", dragName: "Profesiograma", article: "el", successEmoji: "🩺", successMessage: "Profesiograma actualizado!" },
  { dragEmoji: "🔩", dropEmoji: "🔧", dragName: "Torque de Seguridad", article: "el", successEmoji: "✅", successMessage: "Tornillos ajustados!" },
  { dragEmoji: "🧑‍🦽", dropEmoji: "🏢", dragName: "Rampa de Acceso", article: "la", successEmoji: "♿", successMessage: "Accesibilidad garantizada!" },
  { dragEmoji: "🗂️", dropEmoji: "📊", dragName: "Matriz de Riesgos", article: "la", successEmoji: "📋", successMessage: "Riesgos identificados!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "📈", dragName: "Estudio de Puesto", article: "el", successEmoji: "💺", successMessage: "Puesto analizado!" },
  { dragEmoji: "🔥", dropEmoji: "🧯", dragName: "Conato de Incendio", article: "el", successEmoji: "✅", successMessage: "Conato extinguido!" },
  { dragEmoji: "🛡️", dropEmoji: "🧑‍💼", dragName: "Comité de Convivencia", article: "el", successEmoji: "🤝", successMessage: "Convivencia laboral OK!" },
  { dragEmoji: "📢", dropEmoji: "👷", dragName: "Orden de Servicio", article: "la", successEmoji: "📋", successMessage: "Contratista informado!" },
  { dragEmoji: "🧪", dropEmoji: "🩸", dragName: "Prueba de Alcoholemia", article: "la", successEmoji: "✅", successMessage: "Resultado negativo!" },
  { dragEmoji: "🎯", dropEmoji: "📋", dragName: "Plan de Mejora", article: "el", successEmoji: "📈", successMessage: "Mejora continua activa!" },
  { dragEmoji: "🧑‍🎓", dropEmoji: "📜", dragName: "Curso de 50 Horas", article: "el", successEmoji: "🎓", successMessage: "Curso virtual aprobado!" },
  { dragEmoji: "🔑", dropEmoji: "🏢", dragName: "Responsable del SG-SST", article: "el", successEmoji: "👨‍💼", successMessage: "Responsable designado!" },
  { dragEmoji: "🗳️", dropEmoji: "👷", dragName: "Vigía de SST", article: "el", successEmoji: "👁️", successMessage: "Vigía en funciones!" },
  { dragEmoji: "📊", dropEmoji: "🏥", dragName: "Tasa de Ausentismo", article: "la", successEmoji: "📉", successMessage: "Ausentismo en descenso!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "📅", dragName: "Examen Periódico", article: "el", successEmoji: "🩺", successMessage: "Examen periódico al día!" },
  { dragEmoji: "🔒", dropEmoji: "📱", dragName: "App Segura SST", article: "la", successEmoji: "🛡️", successMessage: "Aplicación protegida!" },
  { dragEmoji: "🧯", dropEmoji: "🧑‍🏫", dragName: "Capacitación Extintor", article: "la", successEmoji: "🎓", successMessage: "Personal capacitado!" },
  { dragEmoji: "🌡️", dropEmoji: "🏭", dragName: "Control Térmico Planta", article: "el", successEmoji: "❄️", successMessage: "Temperatura óptima!" },
  { dragEmoji: "📋", dropEmoji: "🧑‍⚖️", dragName: "Acta de Investigación", article: "el", successEmoji: "📝", successMessage: "Incidente investigado!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "👥", dragName: "Capacitación Mensual", article: "la", successEmoji: "📚", successMessage: "Equipo capacitado!" },
  { dragEmoji: "🛡️", dropEmoji: "🌐", dragName: "Política de Prevención", article: "la", successEmoji: "📜", successMessage: "Política socializada!" },
  { dragEmoji: "🏥", dropEmoji: "🧑‍🤝‍🧑", dragName: "EPS del Trabajador", article: "el", successEmoji: "💚", successMessage: "Afiliación vigente!" },
  { dragEmoji: "🧑‍🦱", dropEmoji: "🏢", dragName: "Inducción de Ingreso", article: "la", successEmoji: "🎓", successMessage: "Nuevo empleado inducido!" },
  { dragEmoji: "🔄", dropEmoji: "📋", dragName: "Reinducción Anual", article: "la", successEmoji: "🔁", successMessage: "Reinducción completada!" },
  { dragEmoji: "🏗️", dropEmoji: "📜", dragName: "Licencia de Construcción", article: "la", successEmoji: "✅", successMessage: "Obra con licencia vigente!" },
  { dragEmoji: "🧯", dropEmoji: "📅", dragName: "Recarga Programada", article: "la", successEmoji: "🔄", successMessage: "Recarga de extintor al día!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "📊", dragName: "Indicador de Frecuencia", article: "el", successEmoji: "📉", successMessage: "IF dentro de meta!" },
  { dragEmoji: "📋", dropEmoji: "⚖️", dragName: "Matriz Legal SST", article: "la", successEmoji: "📜", successMessage: "Requisitos legales al día!" },
  { dragEmoji: "🏆", dropEmoji: "👷", dragName: "Reconocimiento Seguro", article: "el", successEmoji: "🥇", successMessage: "Trabajador del mes seguro!" },
  { dragEmoji: "🧲", dropEmoji: "🔬", dragName: "Dosímetro Personal", article: "el", successEmoji: "📊", successMessage: "Exposición dentro de límites!" },
  { dragEmoji: "🦺", dropEmoji: "🚧", dragName: "Protección en Vía", article: "la", successEmoji: "🛡️", successMessage: "Trabajador vial protegido!" },
  { dragEmoji: "📱", dropEmoji: "📊", dragName: "Reporte en Línea", article: "el", successEmoji: "✅", successMessage: "Reporte digital enviado!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "💨", dragName: "Medición de Polvo", article: "la", successEmoji: "🌿", successMessage: "Material particulado OK!" },
  { dragEmoji: "🎪", dropEmoji: "🧑‍⚕️", dragName: "Feria de la Salud", article: "la", successEmoji: "🏥", successMessage: "Feria de salud exitosa!" },
  { dragEmoji: "🛡️", dropEmoji: "🧑‍🦱", dragName: "ARL del Trabajador", article: "el", successEmoji: "💛", successMessage: "ARL activa y vigente!" },
  { dragEmoji: "📝", dropEmoji: "🏢", dragName: "Contrato de Trabajo", article: "el", successEmoji: "✍️", successMessage: "Contrato con cláusula SST!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "🌐", dragName: "Gestión del Cambio", article: "la", successEmoji: "🔄", successMessage: "Cambio gestionado!" },
  { dragEmoji: "📊", dropEmoji: "📅", dragName: "Indicador de Severidad", article: "el", successEmoji: "📉", successMessage: "IS dentro de parámetros!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "🧯", dragName: "Entrenamiento Brigada", article: "el", successEmoji: "🦸", successMessage: "Brigada entrenada!" },
  { dragEmoji: "📋", dropEmoji: "🏥", dragName: "Historia Clínica Laboral", article: "la", successEmoji: "📂", successMessage: "Historia clínica completa!" },
  { dragEmoji: "🔊", dropEmoji: "🏢", dragName: "Mapa de Ruido", article: "el", successEmoji: "📊", successMessage: "Mapa de ruido actualizado!" },
  { dragEmoji: "🧪", dropEmoji: "📊", dragName: "Monitoreo Biológico", article: "el", successEmoji: "🔬", successMessage: "Biomarcadores normales!" },
  { dragEmoji: "🏢", dropEmoji: "📋", dragName: "Concepto Sanitario", article: "el", successEmoji: "✅", successMessage: "Concepto sanitario favorable!" },
  { dragEmoji: "🧑‍🔧", dropEmoji: "📅", dragName: "Mantenimiento Correctivo", article: "el", successEmoji: "🔧", successMessage: "Equipo reparado!" },
  { dragEmoji: "🚗", dropEmoji: "📋", dragName: "Preoperacional Vehículo", article: "el", successEmoji: "✅", successMessage: "Vehículo apto para operar!" },
  { dragEmoji: "🌡️", dropEmoji: "📊", dragName: "Mapa de Calor", article: "el", successEmoji: "🗺️", successMessage: "Zonas críticas identificadas!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "📜", dragName: "Código de Ética SST", article: "el", successEmoji: "⚖️", successMessage: "Ética profesional vigente!" },
  { dragEmoji: "🎯", dropEmoji: "🏢", dragName: "Objetivo Estratégico", article: "el", successEmoji: "🏆", successMessage: "Objetivo alineado con SST!" },
  { dragEmoji: "🧑‍🦰", dropEmoji: "📋", dragName: "Encuesta de Satisfacción", article: "la", successEmoji: "😊", successMessage: "Trabajadores satisfechos!" },
  { dragEmoji: "📢", dropEmoji: "📱", dragName: "Comunicado Interno", article: "el", successEmoji: "📨", successMessage: "Mensaje de seguridad enviado!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "🧫", dragName: "Prueba de Esterilidad", article: "la", successEmoji: "✅", successMessage: "Área estéril certificada!" },
  { dragEmoji: "🏗️", dropEmoji: "🧑‍💼", dragName: "Supervisor de Obra", article: "el", successEmoji: "👷", successMessage: "Supervisión activa!" },
  { dragEmoji: "🧯", dropEmoji: "📋", dragName: "Inventario de Extintores", article: "el", successEmoji: "📊", successMessage: "Inventario actualizado!" },
  { dragEmoji: "🦺", dropEmoji: "🧑‍🏭", dragName: "Dotación Completa", article: "la", successEmoji: "👷‍♂️", successMessage: "Dotación entregada!" },
  { dragEmoji: "📋", dropEmoji: "🏆", dragName: "Acta de Cierre", article: "el", successEmoji: "✅", successMessage: "Ciclo PHVA cerrado!" },
  { dragEmoji: "🌟", dropEmoji: "👷", dragName: "Estrella de Seguridad", article: "la", successEmoji: "⭐", successMessage: "Excelencia en SST!" },
  { dragEmoji: "🧑‍🚀", dropEmoji: "🔬", dragName: "Espacio Confinado", article: "el", successEmoji: "🛡️", successMessage: "Espacio confinado asegurado!" },
  { dragEmoji: "🪫", dropEmoji: "📡", dragName: "UPS de Seguridad", article: "el", successEmoji: "🔋", successMessage: "UPS en funcionamiento!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "🧬", dragName: "Prueba Genética Laboral", article: "la", successEmoji: "🔬", successMessage: "Predisposición identificada!" },
  { dragEmoji: "🔩", dropEmoji: "🏗️", dragName: "Perno de Seguridad", article: "el", successEmoji: "🔧", successMessage: "Conexión estructural OK!" },
  { dragEmoji: "🧪", dropEmoji: "🏭", dragName: "Control de Emisiones", article: "el", successEmoji: "🌿", successMessage: "Emisiones dentro del límite!" },
  { dragEmoji: "🚨", dropEmoji: "🚗", dragName: "Baliza Vehicular", article: "la", successEmoji: "🔴", successMessage: "Vehículo señalizado!" },
  { dragEmoji: "📡", dropEmoji: "🏢", dragName: "CCTV de Seguridad", article: "el", successEmoji: "📹", successMessage: "Videovigilancia activa!" },
  { dragEmoji: "🧑‍🦲", dropEmoji: "🩺", dragName: "Examen de Retiro", article: "el", successEmoji: "📋", successMessage: "Examen de egreso completo!" },
  { dragEmoji: "🪜", dropEmoji: "🧑‍🔧", dragName: "Plataforma Elevadora", article: "la", successEmoji: "✅", successMessage: "Plataforma certificada!" },
  { dragEmoji: "🧤", dropEmoji: "🧪", dragName: "Guante de Nitrilo", article: "el", successEmoji: "🛡️", successMessage: "Protección química activa!" },
  { dragEmoji: "📋", dropEmoji: "🚗", dragName: "Bitácora de Vehículo", article: "la", successEmoji: "📝", successMessage: "Kilometraje registrado!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "📺", dragName: "E-learning SST", article: "el", successEmoji: "💻", successMessage: "Curso virtual completado!" },
  { dragEmoji: "🔔", dropEmoji: "⏰", dragName: "Recordatorio de EPP", article: "el", successEmoji: "📳", successMessage: "Recordatorio configurado!" },
  { dragEmoji: "🧊", dropEmoji: "🧯", dragName: "Extintor CO2", article: "el", successEmoji: "❄️", successMessage: "Extintor clase C listo!" },
  { dragEmoji: "📊", dropEmoji: "🧑‍💼", dragName: "KPI de Seguridad", article: "el", successEmoji: "📈", successMessage: "KPI en zona verde!" },
  { dragEmoji: "🧯", dropEmoji: "🔌", dragName: "Extintor Clase C", article: "el", successEmoji: "⚡", successMessage: "Riesgo eléctrico cubierto!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "🌡️", dragName: "Higiene Térmica", article: "la", successEmoji: "📊", successMessage: "WBGT dentro de límites!" },
  { dragEmoji: "🚲", dropEmoji: "🦺", dragName: "Biciusuario Seguro", article: "el", successEmoji: "🚴‍♂️", successMessage: "Ciclista con elementos!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "💊", dragName: "Farmacia Empresarial", article: "la", successEmoji: "💉", successMessage: "Medicamentos disponibles!" },
  { dragEmoji: "📋", dropEmoji: "🔥", dragName: "Plan de Emergencia", article: "el", successEmoji: "📜", successMessage: "Plan de emergencia vigente!" },
  { dragEmoji: "🧑‍🏭", dropEmoji: "🧪", dragName: "Operador de Caldera", article: "el", successEmoji: "🎓", successMessage: "Calderista certificado!" },
  { dragEmoji: "🛡️", dropEmoji: "☢️", dragName: "Protección Radiológica", article: "la", successEmoji: "🧑‍🔬", successMessage: "Radiación bajo control!" },
  { dragEmoji: "🧲", dropEmoji: "🔊", dragName: "Vibrómetro", article: "el", successEmoji: "📊", successMessage: "Vibración dentro de norma!" },
  { dragEmoji: "📦", dropEmoji: "🚛", dragName: "Embalaje Seguro", article: "el", successEmoji: "📋", successMessage: "Mercancía bien embalada!" },
  { dragEmoji: "🧑‍🦽", dropEmoji: "🏥", dragName: "Rehabilitación Laboral", article: "la", successEmoji: "💪", successMessage: "Trabajador en rehabilitación!" },
  { dragEmoji: "🔩", dropEmoji: "⚙️", dragName: "Guarda de Máquina", article: "la", successEmoji: "🛡️", successMessage: "Guarda de protección puesta!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "📝", dragName: "Acta de COPASST", article: "el", successEmoji: "✅", successMessage: "Reunión del COPASST OK!" },
  { dragEmoji: "🦺", dropEmoji: "🏗️", dragName: "Línea de Vida", article: "la", successEmoji: "🔗", successMessage: "Línea de vida instalada!" },
  { dragEmoji: "🧪", dropEmoji: "🧑‍⚕️", dragName: "Droga Test", article: "el", successEmoji: "✅", successMessage: "Resultado limpio!" },
  { dragEmoji: "📊", dropEmoji: "⚖️", dragName: "Tasa de Mortalidad", article: "la", successEmoji: "📉", successMessage: "Tasa de mortalidad cero!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "🧯", dragName: "Práctica de Evacuación", article: "la", successEmoji: "🏃", successMessage: "Evacuación en tiempo récord!" },
  { dragEmoji: "🔑", dropEmoji: "🗄️", dragName: "Armario de Químicos", article: "el", successEmoji: "🔐", successMessage: "Químicos bajo llave!" },
  { dragEmoji: "🧑‍🔧", dropEmoji: "🪜", dragName: "Inspector de Alturas", article: "el", successEmoji: "👁️", successMessage: "Alturas inspeccionadas!" },
  { dragEmoji: "📱", dropEmoji: "📊", dragName: "App de Indicadores", article: "la", successEmoji: "📈", successMessage: "Datos en tiempo real!" },
  { dragEmoji: "🧪", dropEmoji: "🏢", dragName: "Fumigación Segura", article: "la", successEmoji: "🌿", successMessage: "Fumigación con protocolo!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "🫀", dragName: "RCP Básico", article: "el", successEmoji: "❤️", successMessage: "Personal capacitado en RCP!" },
  { dragEmoji: "🔧", dropEmoji: "🛞", dragName: "Alineación y Balanceo", article: "la", successEmoji: "🚗", successMessage: "Vehículo alineado!" },
  { dragEmoji: "🧑‍💻", dropEmoji: "🔐", dragName: "Backup de Datos SST", article: "el", successEmoji: "💾", successMessage: "Respaldo de datos seguro!" },
  { dragEmoji: "📋", dropEmoji: "🧑‍🏭", dragName: "Matriz de EPP", article: "la", successEmoji: "📊", successMessage: "EPP por cargo definido!" },
  { dragEmoji: "🧯", dropEmoji: "🏟️", dragName: "Extintor de Estadio", article: "el", successEmoji: "🏆", successMessage: "Evento deportivo seguro!" },
  { dragEmoji: "🧑‍🎓", dropEmoji: "📋", dragName: "Curso de 20 Horas", article: "el", successEmoji: "🎓", successMessage: "Curso básico aprobado!" },
  { dragEmoji: "🌡️", dropEmoji: "🧑‍🦱", dragName: "Fiebre Detectada", article: "la", successEmoji: "🏥", successMessage: "Trabajador remitido a EPS!" },
  { dragEmoji: "📢", dropEmoji: "🏢", dragName: "Megáfono de Emergencia", article: "el", successEmoji: "📣", successMessage: "Comunicación de emergencia OK!" },
  { dragEmoji: "🧲", dropEmoji: "🧪", dragName: "Ph-metro Industrial", article: "el", successEmoji: "📊", successMessage: "pH dentro de parámetros!" },
  { dragEmoji: "🚗", dropEmoji: "📱", dragName: "GPS Vehicular", article: "el", successEmoji: "📡", successMessage: "Vehículo rastreado!" },
  { dragEmoji: "🧑‍🔬", dropEmoji: "🌬️", dragName: "Anemómetro", article: "el", successEmoji: "💨", successMessage: "Velocidad del viento OK!" },
  { dragEmoji: "🏗️", dropEmoji: "🧱", dragName: "Demolición Controlada", article: "la", successEmoji: "🛡️", successMessage: "Demolición con protocolo!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "👁️", dragName: "Optometría Ocupacional", article: "la", successEmoji: "👓", successMessage: "Lentes prescritos!" },
  { dragEmoji: "🔩", dropEmoji: "🏭", dragName: "Válvula de Seguridad", article: "la", successEmoji: "✅", successMessage: "Presión regulada!" },
  { dragEmoji: "📋", dropEmoji: "🧑‍⚕️", dragName: "Protocolo de Bioseguridad", article: "el", successEmoji: "🧫", successMessage: "Protocolo implementado!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "🔥", dragName: "Charla de Incendios", article: "la", successEmoji: "🧯", successMessage: "Personal preparado!" },
  { dragEmoji: "🛡️", dropEmoji: "📊", dragName: "Plan Estratégico SST", article: "el", successEmoji: "🎯", successMessage: "Estrategia SST definida!" },
  { dragEmoji: "🧲", dropEmoji: "💧", dragName: "Medición de Humedad", article: "la", successEmoji: "📊", successMessage: "Humedad relativa óptima!" },
  { dragEmoji: "🦺", dropEmoji: "🧑‍🔧", dragName: "Overol de Seguridad", article: "el", successEmoji: "👷", successMessage: "Overol limpio y completo!" },
  { dragEmoji: "📡", dropEmoji: "🏭", dragName: "Sensor de Gas", article: "el", successEmoji: "🔔", successMessage: "Detector de gas activo!" },
  { dragEmoji: "🧑‍💼", dropEmoji: "👥", dragName: "Comité Paritario", article: "el", successEmoji: "🤝", successMessage: "COPASST en sesión!" },
  { dragEmoji: "🔦", dropEmoji: "🧑‍🚒", dragName: "Lámpara Minera", article: "la", successEmoji: "💡", successMessage: "Iluminación de mina OK!" },
  { dragEmoji: "🧪", dropEmoji: "📋", dragName: "Ficha Técnica", article: "la", successEmoji: "📄", successMessage: "Ficha técnica disponible!" },
  { dragEmoji: "🏥", dropEmoji: "🧑‍🦽", dragName: "Reincorporación Laboral", article: "la", successEmoji: "💪", successMessage: "Trabajador reincorporado!" },
  { dragEmoji: "📊", dropEmoji: "🏢", dragName: "Tasa de Incidencia", article: "la", successEmoji: "📉", successMessage: "Incidencia en descenso!" },
  { dragEmoji: "🧑‍🎓", dropEmoji: "🌐", dragName: "Diploma SST Virtual", article: "el", successEmoji: "🎓", successMessage: "Diploma descargado!" },
  { dragEmoji: "🔧", dropEmoji: "📅", dragName: "Mantenimiento Preventivo", article: "el", successEmoji: "🛠️", successMessage: "Equipo en óptimas condiciones!" },
  { dragEmoji: "🧯", dropEmoji: "🧪", dragName: "Extintor Clase D", article: "el", successEmoji: "🔥", successMessage: "Metal combustible controlado!" },
  { dragEmoji: "🧑‍💻", dropEmoji: "📋", dragName: "Software de SST", article: "el", successEmoji: "💻", successMessage: "Sistema digital operativo!" },
  { dragEmoji: "📋", dropEmoji: "🧑‍🤝‍🧑", dragName: "Registro de Asistencia", article: "el", successEmoji: "✅", successMessage: "Asistencia verificada!" },
  { dragEmoji: "🏗️", dropEmoji: "📏", dragName: "Topografía de Obra", article: "la", successEmoji: "🗺️", successMessage: "Terreno nivelado y seguro!" },
  { dragEmoji: "🧑‍⚕️", dropEmoji: "🧪", dragName: "Hemograma Laboral", article: "el", successEmoji: "🩸", successMessage: "Resultados de laboratorio OK!" },
  { dragEmoji: "🔐", dropEmoji: "🏢", dragName: "Control de Acceso", article: "el", successEmoji: "🪪", successMessage: "Solo personal autorizado!" },
  { dragEmoji: "📢", dropEmoji: "🌐", dragName: "Boletín de Seguridad", article: "el", successEmoji: "📰", successMessage: "Boletín distribuido!" },
  { dragEmoji: "🧲", dropEmoji: "🔬", dragName: "Microscopio de SST", article: "el", successEmoji: "🔍", successMessage: "Fibras analizadas!" },
  { dragEmoji: "🦺", dropEmoji: "🚢", dragName: "Chaleco Marítimo", article: "el", successEmoji: "🛟", successMessage: "Tripulación con chaleco!" },
  { dragEmoji: "📋", dropEmoji: "🏥", dragName: "Formato FURAT", article: "el", successEmoji: "📝", successMessage: "FURAT diligenciado!" },
  { dragEmoji: "🧑‍🏫", dropEmoji: "🧑‍🦱", dragName: "Mentoría en SST", article: "la", successEmoji: "🤝", successMessage: "Nuevo líder formado!" },
  { dragEmoji: "🎯", dropEmoji: "📊", dragName: "Acción Correctiva", article: "la", successEmoji: "✅", successMessage: "No conformidad cerrada!" },
  { dragEmoji: "🎆", dropEmoji: "🏢", dragName: "Cierre Anual SST", article: "el", successEmoji: "🎊", successMessage: "Año sin accidentes fatales!" },
];
